---
sidebar: sidebar 
permalink: upgrade/task_hcc_upgrade_element_software.html 
summary: 作为NetApp SolidFire系统升级的一部分，您需要升级NetApp Element软件。 
keywords: netapp, solidfire, cluster, element, H610S upgrade, hcc, upgrade role 
---
= 升级 Element 软件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
要升级NetApp Element软件，您可以使用NetApp Hybrid Cloud Control UI 或 REST API。  Element 软件升级期间会抑制某些操作，例如添加和删除节点、添加和删除驱动器以及与启动器、卷访问组和虚拟网络相关的命令等。

[CAUTION]
====
管理服务 2.27 捆绑包包含适用于 vCenter Server 5.5 的 Element Plug-in，该插件仅与管理节点 12.8 兼容。当您更新到管理服务 2.27 时，您必须更改升级顺序并在升级到 Element 12.8 之后更新管理服务包，以使管理节点和管理服务之间兼容。

如果您要更新到管理服务 2.21.61 到 2.26.40，则必须在升级到 Element 12.8 之前更新管理服务包。

====
.开始之前
* *管理员权限*：您拥有存储集群管理员权限来执行升级。
* *有效的升级路径*：您已检查要升级到的 Element 版本的升级路径信息，并验证了该升级路径有效。https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_is_the_upgrade_matrix_for_storage_clusters_running_NetApp_Element_software%3F["NetApp知识库：运行NetApp Element软件的存储集群升级矩阵"^]
+
从 Element 12.5 开始， NetApp HealthTools 不再支持 Element 软件升级。如果您运行的是 Element 11.0 或 11.1 版本，则必须首先link:https://docs.netapp.com/us-en/element-software-123/upgrade/task_hcc_upgrade_element_software.html#upgrade-element-software-at-connected-sites-using-healthtools["使用 HealthTools 升级到 Element 12.3.x"^]然后使用NetApp Hybrid Cloud Control 升级到 Element 12.5 或更高版本。

* *系统时间同步*：您已确保所有节点上的系统时间已同步，并且已为存储集群和节点正确配置 NTP。每个节点都必须在其各自的 Web 用户界面中配置 DNS 名称服务器。(`https://[IP address]:442` ）没有与时间偏差相关的未解决的集群故障。
* *系统端口*：如果您使用NetApp Hybrid Cloud Control 进行升级，则必须确保必要的端口已打开。看link:../storage/reference_prereq_network_port_requirements.html["网络端口"]了解更多信息。
* *管理节点*：对于NetApp Hybrid Cloud Control UI 和 API，您环境中的管理节点正在运行版本 11.3。
* *集群健康状况*：您已确认集群已准备好进行升级。看link:task_hcc_upgrade_element_prechecks.html["在升级存储之前，请运行 Element 存储健康检查"]。
* *已更新 H610S 存储节点的基板管理控制器 (BMC)*：您已升级 H610S 节点的BMC版本。查看link:https://docs.netapp.com/us-en/hci/docs/rn_H610S_BMC_3.84.07.html["发行说明和升级说明"^]。


[[element-upgrade-tim]]
* *升级过程时间*：您已安排足够的时间执行升级。当您升级到 Element 软件 12.5 或更高版本时，升级过程时间取决于您当前的 Element 软件版本和固件更新情况。
+
[cols="20,20,20,20,20"]
|===
| 存储节点 | 当前 Element 软件版本 | 每个节点的软件和固件安装大约需要10000秒^1^ | 每个节点的大约数据同步时间^2^ | 每个节点的大约总升级时间 


| 所有配备最新固件的SolidFire和NetApp H 系列节点^3^ | 12.x | 15 分钟 | 10到15分钟 | 20至30分钟 


| H610S 和 H410S | 12.x 和 11.8 | 60分钟 | 30至60分钟 | 90至120分钟 


| H610S | 11.7 及更早版本 | 90分钟 | 40至70分钟 | 130至160分钟 您还必须 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["执行节点完全关闭和断电操作"^]针对每个 H610S 节点。 
|===
+
^1^有关适用于您硬件的固件和驱动程序固件的完整矩阵，请参阅link:../hardware/fw_storage_nodes.html["SolidFire存储节点支持的存储固件版本"]。

+
^2^如果将集群与高写入 IOPS 负载和较长的固件更新时间结合起来，数据同步时间将会增加。

+
^3^ 以下节点不受支持。如果您尝试将这些节点之一升级到不受支持的 Element 版本，您将看到一条错误消息，指出 Element 12.x 不支持该节点：

+
** 从 Element 12.8、SF4805、SF9605、SF19210 和 SF38410 存储节点开始。
** 从 Element 12.7、SF2405 和 SF9608 存储节点以及 FC0025 和 SF-FCN-01 FC 节点开始。


* *最终用户许可协议 (EULA)*：从管理服务 2.20.69 版本开始，您必须先接受并保存 EULA，然后才能使用NetApp Hybrid Cloud Control UI 或 API 升级 Element 软件：
+
.. 在网页浏览器中打开管理节点的IP地址：
+
[listing]
----
https://<ManagementNodeIP>
----
.. 使用存储集群管理员凭据登录NetApp Hybrid Cloud Control。
.. 在界面右上角附近选择“升级”。
.. 最终用户许可协议弹出。向下滚动，选择“我接受当前及所有未来的更新”，然后选择“保存”。




.升级选项
请选择以下 Element 软件升级选项之一：

* <<使用NetApp Hybrid Cloud Control UI 升级 Element 存储>>
* <<使用NetApp Hybrid Cloud Control API 升级 Element 存储>>



IMPORTANT: 如果您要将 H610S 系列节点升级到 Element 12.5 或更高版本，并且该节点当前运行的 Element 版本低于 11.8，则需要执行本文档中的其他升级步骤。 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["知识库文章"^]对于每个存储节点。如果您运行的是 Element 11.8 或更高版本，则无需执行额外的升级步骤。



== 使用NetApp Hybrid Cloud Control UI 升级 Element 存储

使用NetApp Hybrid Cloud Control UI，您可以升级存储集群。


CAUTION: 有关使用NetApp Hybrid Cloud Control 升级存储集群时可能出现的问题及其解决方法，请参阅此文档。 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Potential_issues_and_workarounds_when_running_storage_upgrades_using_NetApp_Hybrid_Cloud_Control["知识库文章"^] 。

.步骤
. 在网页浏览器中打开管理节点的IP地址：
+
[listing]
----
https://<ManagementNodeIP>
----
. 使用存储集群管理员凭据登录NetApp Hybrid Cloud Control。
. 在界面右上角附近选择“升级”。
. 在“升级”页面上，选择“存储”。
+
“存储”选项卡列出了安装中包含的存储集群。如果NetApp Hybrid Cloud Control 无法访问集群，则该集群不会显示在“升级”页面上。

. 请从以下选项中选择，并执行适用于您集群的步骤：
+
[cols="2*"]
|===
| 选项 | 步骤 


| 所有运行 Element 11.8 及更高版本的集群  a| 
.. 选择“浏览”上传您下载的升级包。
.. 等待上传完成。进度条显示上传状态。
+

CAUTION: 如果您离开浏览器窗口，上传的文件将会丢失。

+
文件成功上传并验证后，屏幕上会显示一条消息。验证可能需要几分钟时间。如果您此时离开浏览器窗口，文件上传内容仍会被保留。

.. 选择“开始升级”。
+

TIP: 升级过程中，“升级状态”会发生变化，以反映升级过程的状态。它还会根据您采取的操作而改变，例如暂停升级，或者升级返回错误。看<<升级状态变更>>。

+

NOTE: 升级过程中，您可以离开此页面，稍后再返回查看进度。如果集群行已折叠，则页面不会动态更新状态和当前版本。必须展开集群行才能更新表格，或者您可以刷新页面。

+
升级完成后即可下载日志。





| 您正在升级运行 Element 版本低于 11.8 的 H610S 集群。  a| 
.. 选择要升级的集群旁边的下拉箭头，然后从可用的升级版本中进行选择。
.. 选择“开始升级”。升级完成后，用户界面会提示您执行其他升级步骤。
.. 完成所需的其他步骤。 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["知识库文章"^]并在用户界面中确认您已完成第 2 阶段。


升级完成后即可下载日志。有关各种升级状态变更的信息，请参阅<<升级状态变更>>。

|===




=== 升级状态变更

以下是升级过程中“升级状态”列在升级前、升级过程中和升级后显示的不同状态：

[cols="2*"]
|===
| 升级状态 | 描述 


| 最新 | 集群已升级到最新的 Element 版本。 


| 可用版本 | Element 和/或存储固件的更新版本可供升级。 


| 进行中 | 升级正在进行中。进度条显示升级状态。屏幕消息还会显示节点级故障，并在升级过程中显示集群中每个节点的节点 ID。您可以使用 Element UI 或适用于 vCenter Server UI 的NetApp Element插件来监控每个节点的状态。 


| 正在暂停升级 | 您可以选择暂停升级。根据升级过程的状态，暂停操作可能会成功，也可能会失败。您会看到一个用户界面提示，要求您确认暂停操作。为了确保集群在暂停升级之前处于安全状态，升级操作可能需要长达两个小时才能完全暂停。要恢复升级，请选择“恢复”。 


| 已暂停 | 您已暂停升级。选择“继续”以继续该过程。 


| 错误 | 升级过程中发生错误。您可以下载错误日志并将其发送给NetApp支持部门。解决错误后，您可以返回该页面，然后选择“继续”。恢复升级时，进度条会倒退几分钟，同时系统会运行健康检查并检查升级的当前状态。 


| 完成，但需执行后续操作 | 仅适用于从 Element 版本低于 11.8 升级的 H610S 节点。升级过程的第一阶段完成后，此状态会提示您执行其他升级步骤（请参阅）。 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["知识库文章"^] ）。完成第二阶段并确认已完成后，状态将变为*已更新*。 
|===


== 使用NetApp Hybrid Cloud Control API 升级 Element 存储

您可以使用 API 将集群中的存储节点升级到最新的 Element 软件版本。您可以使用您选择的自动化工具来运行 API。此处记录的 API 工作流程以管理节点上可用的 REST API UI 为例。

.步骤
. 将存储升级包下载到管理节点可访问的设备。
+
前往 Element 软件 https://mysupport.netapp.com/site/products/all/details/element-software/downloads-tab["下载页面"^]并下载最新的存储节点镜像。

. 将存储升级包上传到管理节点：
+
.. 在管理节点上打开管理节点 REST API 用户界面：
+
[listing]
----
https://<ManagementNodeIP>/package-repository/1/
----
.. 选择“授权”，然后完成以下步骤：
+
... 请输入集群用户名和密码。
... 请输入客户端 ID `mnode-client` 。
... 选择“授权”以开始会话。
... 关闭授权窗口。


.. 从 REST API UI 中选择 *POST /packages*。
.. 选择*试用一下*。
.. 选择“浏览”，然后选择升级包。
.. 选择“执行”以开始上传。
.. 从响应中复制并保存包 ID(`"id"` ) 供后续步骤使用。


. 确认上传状态。
+
.. 从 REST API UI 中选择 *GET /packages/{id}/status*。
.. 选择*试用一下*。
.. 在 *id* 中输入您在上一步中复制的包裹 ID。
.. 选择“执行”以发起状态请求。
+
回应表明 `state`作为 `SUCCESS`完成后。



. 找到存储集群 ID：
+
.. 在管理节点上打开管理节点 REST API 用户界面：
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. 选择“授权”，然后完成以下步骤：
+
... 请输入集群用户名和密码。
... 请输入客户端 ID `mnode-client` 。
... 选择“授权”以开始会话。
... 关闭授权窗口。


.. 从 REST API UI 中选择 *GET /installations*。
.. 选择*试用一下*。
.. 选择*执行*。
.. 从响应中复制安装资产 ID(`"id"` ）。
.. 从 REST API UI 中选择 *GET /installations/{id}*。
.. 选择*试用一下*。
.. 将安装资产 ID 粘贴到 *id* 字段中。
.. 选择*执行*。
.. 从响应中复制并保存存储集群 ID(`"id"` ) 您打算升级的集群，以便在后续步骤中使用。


. 运行存储升级：
+
.. 在管理节点上打开存储 REST API 用户界面：
+
[listing]
----
https://<ManagementNodeIP>/storage/1/
----
.. 选择“授权”，然后完成以下步骤：
+
... 请输入集群用户名和密码。
... 请输入客户端 ID `mnode-client` 。
... 选择“授权”以开始会话。
... 关闭授权窗口。


.. 选择 *POST /升级*。
.. 选择*试用一下*。
.. 在参数字段中输入升级包 ID。
.. 在参数字段中输入存储集群 ID。
+
有效载荷应类似于以下示例：

+
[listing]
----
{
  "config": {},
  "packageId": "884f14a4-5a2a-11e9-9088-6c0b84e211c4",
  "storageId": "884f14a4-5a2a-11e9-9088-6c0b84e211c4"
}
----
.. 选择“执行”以启动升级。
+
响应应表明状态为 `initializing`：

+
[listing]
----
{
  "_links": {
    "collection": "https://localhost:442/storage/upgrades",
    "self": "https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1",
    "log": https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1/log
  },
  "storageId": "114f14a4-1a1a-11e9-9088-6c0b84e200b4",
  "upgradeId": "334f14a4-1a1a-11e9-1055`-6c0b84e2001b4",
  "packageId": "774f14a4-1a1a-11e9-8888-6c0b84e200b4",
  "config": {},
  "state": "initializing",
  "status": {
    "availableActions": [
      "string"
    ],
    "message": "string",
    "nodeDetails": [
      {
        "message": "string",
        "step": "NodePreStart",
        "nodeID": 0,
        "numAttempt": 0
      }
    ],
    "percent": 0,
    "step": "ClusterPreStart",
    "timestamp": "2020-04-21T22:10:57.057Z",
    "failedHealthChecks": [
      {
        "checkID": 0,
        "name": "string",
        "displayName": "string",
        "passed": true,
        "kb": "string",
        "description": "string",
        "remedy": "string",
        "severity": "string",
        "data": {},
        "nodeID": 0
      }
    ]
  },
  "taskId": "123f14a4-1a1a-11e9-7777-6c0b84e123b2",
  "dateCompleted": "2020-04-21T22:10:57.057Z",
  "dateCreated": "2020-04-21T22:10:57.057Z"
}
----
.. 复制升级 ID(`"upgradeId"`这是回应的一部分。


. 验证升级进度和结果：
+
.. 选择 *GET /upgrades/{upgradeId}*。
.. 选择*试用一下*。
.. 在 *upgradeId* 中输入上一步得到的升级 ID。
.. 选择*执行*。
.. 如果在升级过程中出现问题或有特殊要求，请执行以下操作之一：
+
[cols="2*"]
|===
| 选项 | 步骤 


| 您需要修复由于以下原因导致的集群健康状况问题： `failedHealthChecks`响应正文中的消息。  a| 
... 请前往每个问题对应的知识库文章或执行指定的解决方法。
... 如果指定了知识库文章，请按照相关知识库文章中描述的步骤完成操作。
... 解决集群问题后，如果需要，请重新进行身份验证，然后选择 *PUT /upgrades/{upgradeId}*。
... 选择*试用一下*。
... 在 *upgradeId* 中输入上一步得到的升级 ID。
... 进入 `"action":"resume"`在请求正文中。
+
[listing]
----
{
  "action": "resume"
}
----
... 选择*执行*。




| 由于维护窗口即将关闭或其他原因，您需要暂停升级。  a| 
... 如果需要，请重新验证身份并选择 *PUT /upgrades/{upgradeId}*。
... 选择*试用一下*。
... 在 *upgradeId* 中输入上一步得到的升级 ID。
... 进入 `"action":"pause"`在请求正文中。
+
[listing]
----
{
  "action": "pause"
}
----
... 选择*执行*。




| 如果您正在升级运行 Element 版本低于 11.8 的 H610S 集群，您将看到以下状态 `finishedNeedsAck`在响应正文中。您必须对每个 H610S 存储节点执行额外的升级步骤。  a| 
... 完成此步骤中的其他升级步骤。 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["知识库文章"^]对于每个节点。
... 如果需要，请重新验证身份并选择 *PUT /upgrades/{upgradeId}*。
... 选择*试用一下*。
... 在 *upgradeId* 中输入上一步得到的升级 ID。
... 进入 `"action":"acknowledge"`在请求正文中。
+
[listing]
----
{
  "action": "acknowledge"
}
----
... 选择*执行*。


|===
.. 根据需要多次运行 *GET /upgrades/{upgradeId}* API，直到过程完成。
+
升级过程中， `status`表示 `running`如果没有遇到错误。随着每个节点的升级， `step`值变化 `NodeFinished`。

+
升级成功完成的标志是： `percent`值是 `100`以及 `state`表示 `finished`。







== 如果使用NetApp Hybrid Cloud Control 进行升级失败会发生什么情况

如果在升级过程中驱动器或节点发生故障，Element UI 将显示集群故障。升级过程不会继续到下一个节点，而是等待集群故障解决。用户界面中的进度条显示，升级正在等待集群故障解决。现阶段，在用户界面中选择“暂停”将不起作用，因为升级需要等待集群运行正常。您需要联系NetApp支持部门协助进行故障调查。

NetApp Hybrid Cloud Control 预设了三个小时的等待期，在此期间可能会出现以下情况之一：

* 集群故障在三小时内得到解决，升级继续进行。在这种情况下，您无需采取任何行动。
* 三个小时后问题仍然存在，升级状态显示“错误”，并带有红色横幅。问题解决后，您可以选择“恢复”来继续升级。
* NetApp支持团队已确定，需要在三小时窗口期之前暂时中止升级，以便采取纠正措施。支持人员将使用 API 来中止升级。



CAUTION: 在节点更新过程中中止集群升级可能会导致驱动器从节点中意外移除。如果驱动器被错误移除，则在升级过程中重新添加驱动器将需要NetApp支持人员的手动干预。节点可能需要更长时间才能完成固件更新或更新后同步活动。如果升级过程似乎停滞不前，请联系NetApp支持部门寻求帮助。

[discrete]
== 查找更多信息

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire和 Element 软件文档"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element vCenter Server 插件"^]

