---
sidebar: sidebar 
permalink: hccstorage/task-hcc-qos-policies.html 
summary: 您可以设置和修改 QoS 策略，以应用于存储集群中的卷。 
keywords: netapp, qos policy, quality of service, qos policies, volumes, element 
---
= 创建和管理卷 QoS 策略
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
QoS（服务质量）策略允许您创建和保存可应用于多个卷的标准化服务质量设置。要使用 QoS 策略，所选集群必须是 Element 10.0 或更高版本；否则，QoS 策略功能将不可用。


NOTE: 有关使用 SolidFire 全闪存存储的更多信息，请参阅SolidFire全闪存存储概念内容。link:../concepts/concept_data_manage_volumes_solidfire_quality_of_service.html#qos-policies["QoS 策略"]而不是单个体积link:../concepts/concept_data_manage_volumes_solidfire_quality_of_service.html["QoS"]。

使用NetApp Hybrid Cloud Control，您可以通过完成以下任务来创建和管理 QoS 策略：

* <<创建 QoS 策略>>
* <<对卷应用 QoS 策略>>
* <<更改卷的 QoS 策略分配>>
* <<编辑 QoS 策略>>
* <<删除 QoS 策略>>




== 创建 QoS 策略

您可以创建 QoS 策略，并将其应用于应具有相同性能的卷。


NOTE: 如果您正在使用 QoS 策略，请不要在卷上使用自定义 QoS。自定义 QoS 将覆盖和调整卷 QoS 设置的 QoS 策略值。

.步骤
. 使用 Element 存储集群管理员凭据登录NetApp Hybrid Cloud Control。
. 从控制面板中，展开存储集群的菜单。
. 选择“存储 > 卷”。
. 选择“QoS策略”选项卡。
. 选择“创建保单”。
. 请输入*保单名称*。
+

TIP: 采用描述性命名最佳实践。如果您的环境中使用了多个集群或 vCenter Server，这一点尤其重要。

. 输入最小 IOPS、最大 IOPS 和突发 IOPS 值。
. 选择“创建QoS策略”。
+
系统会为该策略生成一个系统 ID，并且该策略及其分配的 QoS 值会显示在 QoS 策略页面上。





== 对卷应用 QoS 策略

您可以使用NetApp Hybrid Cloud Control 将现有的 QoS 策略分配给卷。

.你需要什么
您要分配的 QoS 策略已<<创建 QoS 策略,已创建>>。

.关于此任务
本任务描述了如何通过更改设置将 QoS 策略分配给单个卷。最新版本的NetApp Hybrid Cloud Control 没有批量分配多个卷的选项。在未来的版本中提供批量分配功能之前，您可以使用 Element Web UI 或 vCenter 插件 UI 批量分配 QoS 策略。

.步骤
. 使用 Element 存储集群管理员凭据登录NetApp Hybrid Cloud Control。
. 从控制面板中，展开存储集群的菜单。
. 选择“存储 > 卷”。
. 选择要修改的音量旁边的“操作”菜单。
. 在出现的菜单中，选择“编辑”。
. 在对话框中，启用“分配 QoS 策略”，然后从下拉列表中选择要应用于所选卷的 QoS 策略。
+

NOTE: 分配 QoS 将覆盖之前应用的任何单个卷 QoS 值。

. 选择*保存*。




== 更改卷的 QoS 策略分配

您可以从卷中移除 QoS 策略的分配，或者选择不同的 QoS 策略或自定义 QoS。

.你需要什么
您要修改的音量是<<对卷应用 QoS 策略,分配>>服务质量策略。

.步骤
. 使用 Element 存储集群管理员凭据登录NetApp Hybrid Cloud Control。
. 从控制面板中，展开存储集群的菜单。
. 选择“存储 > 卷”。
. 选择要修改的音量旁边的“操作”菜单。
. 在出现的菜单中，选择“编辑”。
. 在对话框中，执行以下操作之一：
+
** 禁用“分配 QoS 策略”，并修改各个卷 QoS 的“最小 IOPS”、“最大 IOPS”和“突发 IOPS”值。
+

NOTE: 禁用 QoS 策略时，除非另行修改，否则卷将使用默认的 QoS IOPS 值。

** 从下拉列表中选择不同的 QoS 策略，以应用于所选卷。


. 选择*保存*。




== 编辑 QoS 策略

您可以更改现有 QoS 策略的名称或编辑与该策略关联的值。更改 QoS 策略性能值会影响与该策略关联的所有卷的 QoS。

.步骤
. 使用 Element 存储集群管理员凭据登录NetApp Hybrid Cloud Control。
. 从控制面板中，展开存储集群的菜单。
. 选择“存储 > 卷”。
. 选择“QoS策略”选项卡。
. 选择要修改的 QoS 策略旁边的“操作”菜单。
. 选择*编辑*。
. 在“编辑 QoS 策略”对话框中，更改以下一项或多项内容：
+
** *名称*：QoS策略的用户自定义名称。
** *最小 IOPS*：保证该卷的最小 IOPS 数。默认值 = 50。
** *最大 IOPS*：卷允许的最大 IOPS 数。默认值 = 15,000。
** *突发IOPS*：在短时间内允许达到的最大IOPS数量。默认值 = 15,000。


. 选择*保存*。
+

TIP: 您可以点击策略的“活动卷”列中的链接，显示分配给该策略的卷的筛选列表。





== 删除 QoS 策略

如果不再需要 QoS 策略，您可以将其删除。删除 QoS 策略时，所有分配了该策略的卷都会保留该策略先前定义的 QoS 值，但会作为单独的卷 QoS 进行设置。与已删除的 QoS 策略的任何关联都将被移除。

.步骤
. 使用 Element 存储集群管理员凭据登录NetApp Hybrid Cloud Control。
. 从控制面板中，展开存储集群的菜单。
. 选择“存储 > 卷”。
. 选择“QoS策略”选项卡。
. 选择要修改的 QoS 策略旁边的“操作”菜单。
. 选择*删除*。
. 确认此操作。


[discrete]
== 查找更多信息

* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element vCenter Server 插件"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire和 Element 软件文档"^]

