---
permalink: concepts/concept_solidfire_concepts_accounts_and_permissions.html 
sidebar: sidebar 
keywords: solidfire, element, cluster admin, storage, account, authoritative cluster 
summary: 要管理和提供对系统存储资源的访问权限，您需要为系统资源设置帐户。 
---
= 帐户和权限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要管理和提供对系统存储资源的访问权限，您需要为系统资源设置帐户。

使用 Element 存储，您可以创建和管理以下类型的帐户：

* <<存储集群管理员帐户,存储集群的管理员用户帐户>>
* <<用户帐户,用于访问存储卷的用户帐户>>
* <<权威集群用户帐户,NetApp Hybrid Cloud Control 的权威集群用户帐户>>




== 存储集群管理员帐户

在运行NetApp Element软件的存储集群中，可以存在两种类型的管理员帐户：

* *主集群管理员帐户*：此管理员帐户在创建集群时创建。该帐户是集群中具有最高访问权限的主要管理帐户。该账户类似于 Linux 系统中的 root 用户。您可以更改此管理员帐户的密码。
* *集群管理员帐户*：您可以授予集群管理员帐户有限的管理权限，使其能够在集群中执行特定任务。分配给每个集群管理员帐户的凭据用于验证存储系统中的 API 和 Element UI 请求。



NOTE: 要通过每个节点的 UI 访问集群中的活动节点，需要本地（非 LDAP）集群管理员帐户。访问尚未加入集群的节点不需要账户凭证。

你可以link:../storage/concept_system_manage_manage_cluster_administrator_users.html["管理集群管理员帐户"]通过创建、删除和编辑集群管理员帐户，更改集群管理员密码，以及配置 LDAP 设置来管理系统用户访问权限。



== 用户帐户

用户帐户用于控制对NetApp Element软件网络上存储资源的访问。创建卷之前至少需要一个用户帐户。

创建卷时，会将其分配给一个帐户。如果您创建了虚拟卷，则该帐户就是存储容器。

以下是一些其他需要考虑的因素：

* 该帐户包含访问分配给它的卷所需的 CHAP 身份验证。
* 一个账户最多可以分配 2000 个卷，但一个卷只能属于一个账户。
* 用户帐户可以通过NetApp Element Management 扩展点进行管理。




== 权威集群用户帐户

权威集群用户帐户可以对与NetApp Hybrid Cloud Control 实例的节点和集群关联的任何存储资产进行身份验证。通过此帐户，您可以管理所有集群中的卷、帐户、访问组等。

权威用户帐户可通过NetApp Hybrid Cloud Control 右上角菜单中的“用户管理”选项进行管理。

这link:../concepts/concept_intro_clusters.html#authoritative-storage-clusters["权威存储集群"]这是NetApp Hybrid Cloud Control 用于验证用户身份的存储集群。

在权威存储集群上创建的所有用户都可以登录到NetApp混合云控制。在其他存储集群上创建的用户_无法_登录混合云控制。

* 如果您的管理节点只有一个存储集群，那么它就是权威集群。
* 如果您的管理节点有两个或多个存储集群，则其中一个集群将被指定为权威集群，并且只有该集群中的用户才能登录到NetApp Hybrid Cloud Control。


虽然NetApp Hybrid Cloud Control 的许多功能可以与多个存储集群配合使用，但身份验证和授权存在必要的限制。身份验证和授权方面的限制是，即使用户不是其他存储集群上的用户，权威集群中的用户也可以对与NetApp Hybrid Cloud Control 关联的其他集群执行操作。在开始管理多个存储集群之前，您应该确保在权威集群上定义的用户在所有其他存储集群上都具有相同的权限。您可以通过NetApp Hybrid Cloud Control 管理用户。



== 批量账户

卷特定帐户仅适用于创建它们的存储集群。这些帐户允许您设置网络中特定卷的权限，但对这些卷之外的内容没有影响。

卷帐户在NetApp混合云控制卷表中进行管理。
