---
permalink: concepts/concept_rn_whats_new_element.html 
sidebar: sidebar 
keywords: netapp, solidfire, element, storage, solidfire enterprise sds 
summary: NetApp会定期更新SolidFire和 Element 软件，为您带来新功能、增强功能和错误修复。 
---
= Element软件的新功能有哪些？
:allow-uri-read: 
:url-peak: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/Element_Software_-_Apache_Log4j_Vulnerability_-_Workaround
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp会定期更新SolidFire和 Element 软件，为您带来新功能、增强功能和错误修复。  Element 12.8 是最新版本，包含安全性和系统组件更新、操作改进以及已解决的问题。


NOTE: 累积软件和固件更新是作为 Element 12.8 升级的一部分安装的，该升级基于存储集群上运行的当前 Element 版本。例如，如果集群当前正在运行 Element 12.5，您可以直接升级到 Element 12.8，以获取 Element 12.7 和 12.8 的累积更新。有关支持的升级路径，请参阅知识库文章。 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_is_the_upgrade_matrix_for_storage_clusters_running_NetApp_Element_software["运行NetApp Element软件的存储集群的升级矩阵是什么？"^] 。



== 元素 12.8

了解 Element 12.8 的新增功能。



=== 卷负载均衡

Element 12.8 引入了容量负载均衡功能。您可以使用此功能，根据每个卷的实际 IOPS 级别（而不是 QoS 策略中配置的最小 IOPS）在节点之间平衡卷。您只能使用卷负载均衡功能来平衡卷。你不能用它来平衡虚拟卷。卷负载均衡功能默认处于禁用状态。您可以使用以下方式启用和禁用它： `VolumeLoadBalanceOnActualIOPS` API 参数与link:../api/reference_element_api_enablefeature.html["启用功能"]和link:../api/reference_element_api_disablefeature.html["禁用功能"]API 方法或通过使用link:../storage/task_system_manage_cluster_volume_load_balancing.html["卷负载均衡"]Element UI 中的选项。



=== 查看节点利用率信息

使用 Element 12.8，您可以查看节点利用率信息，如下所示 `nodeHeat`使用 `GetNodeStats`和 `ListNodeStats`API 方法。这 `nodeHeat`对象是以下成员之一 `nodeStats`对象并显示基于主总 IOPS 或总 IOPS 与配置 IOPS 的比率（随时间平均）的节点利用率信息。

此外，您还可以查看节点利用率的百分比。 `recentPrimaryTotalHeat`在元素用户界面中节点的“查看详细信息”显示中。



=== 查看卷的 I/O 统计信息

使用 Element 12.8，您可以查看卷的 I/O 使用情况统计信息。 `sliceIopsStats`使用 `GetVolumeStats`和 `ListVolumeStatsByVolume`API 方法。 I/O 统计数据是根据卷的读取和写入 IOPS 信息计算得出的，测量时间段为两个时期：最近 24 小时和最近 1 小时。link:../api/reference_element_api_volumestats.html#object-members["了解更多"]。



=== iSCSI 会话的 CHAP 算法

主机 iSCSI 发起程序请求一个质询握手身份验证协议 (CHAP) 算法列表，以便在与 Element iSCSI 目标创建 iSCSI 会话时使用。从 Element 12.8 开始，您可以查看 Element iSCSI 目标选择用于 iSCSI 会话的受支持的 CHAP 算法。



=== 升级虚拟机硬件版本

如果您要将现有管理节点就地升级到 Element 12.8，则在升级之前，必须确保管理节点上的 VM 硬件版本与您的环境兼容 ESXi 6.7（VM 硬件版本 14）或更高版本。link:../upgrade/task_hcc_upgrade_management_node.html#step-1-upgrade-vm-hardware-version-on-a-management-node["了解更多"]。



== 元素 12.7

了解 Element 12.7 的新增功能。



=== 安全的 CHAP 算法

Element 12.7 包括对符合 FIPS 标准的安全挑战握手认证协议 (CHAP) 算法 SHA1、SHA-256 和 SHA3-256 的支持。link:../storage/task_data_manage_accounts_work_with_accounts_task.html["了解更多"]。



=== 动态块（bin）同步输入速率

集群操作，例如节点的添加、升级或维护，或者添加驱动器等，都会触发块（bin）同步，将块数据分发到集群布局中的新节点或更新节点。使用单一的慢速作为默认同步速率会导致这些操作耗时过长，并且无法利用更大节点的更高处理能力。从 Element 12.7 开始，同步速率会根据存储节点上的核心数动态调整，从而使这些操作能够显著加快速度。

例如，当您向现有集群添加运行 Element 12.7 的大型 28 核存储节点（H610S、SF19210 和 SF38410）时，数据同步速率会自动调整为 110Mbps 而不是 60Mbps。此外，当您将这些大型存储节点从节点维护模式中取出时（例如，在使用NetApp Hybrid Cloud Control 从 Element 12.3.x 或更高版本升级到 Element 12.7 时），更改块数据速率的同步输入速率会自动调整为 110Mbps 而不是 20Mbps。

当您将中型 16 核存储节点 (H410S) 和小型 12 核存储节点 (SF4805) 添加到 Element 12.7 集群时，数据同步速率保持在 60Mbps；但是，在从 Element 12.3.x 升级到 Element 12.7 期间，当您将节点从维护模式中取出时，同步已更改的数据块的同步速率会自动调整，中型存储节点的同步速率从 20Mbps 调整到 60Mbps，小型存储节点的同步速率从 40Mbps 调整到 40Mbps。

移除存储节点时，不会影响块同步输出速率，从而避免对客户端 I/O 性能造成影响。



=== 垃圾收集改进

例如，对于拥有较大存储节点的集群，如 H610S-4，其已用空间为 1PB，运行着非常高的工作负载（包括覆盖操作），并且具有很高的重复数据删除和压缩率，由于较大节点的默认布隆过滤器大小已从 700GB 或更大的内存增加到 1048576 位，因此垃圾回收操作现在可以跟上。将存储节点升级到 Element 12.7 后，此更改将自动生效，并且对较小的节点没有影响。



=== 规模改进

使用 Element 12.7，向现有集群添加多个存储节点的块和元数据驱动器时，不再需要遵循特定的顺序。使用 Element UI 或 API，您可以轻松选择所有可用驱动器并同时批量添加它们。 Element 12.7 会自动管理数据同步，以便所有块服务同时同步。当每个节点的块服务完成同步后，该节点上的元数据驱动器即可分配给主机卷。这种规模上的改进显著降低了读取响应延迟，并防止了在新添加的存储节点之间同步数据时性能下降。



=== 存储节点固件更新

Element 12.7 包含存储固件包版本 2.164.0，其中包括对新系统组件的支持。link:https://docs.netapp.com/us-en/hci/docs/rn_storage_firmware_2.164.0.html["了解更多"]。


NOTE: Element 12.7 版本中没有新的固件更新。但是，根据存储节点上运行的当前固件包，升级到 Element 12.7 时会安装累积更新。



=== SolidFire Active IQ文档

在SolidFire Active IQ UI 中，您现在可以导航到 QoS 管理页面，查看集群的建议和节点限速信息。此外，集群仪表板现在会显示快照总数。最近的其他增强功能包括：为活动卷添加主节点和辅助节点信息，以及节点上主卷最近 30 分钟的平均吞吐量、IOPS 和平均延迟。

您现在可以从 Element 软件文档中访问SolidFire Active IQ文档。link:https://docs.netapp.com/us-en/element-software/monitor-storage-active-iq.html["了解更多"]。



=== NetApp Bugs Online 包含已解决和已知问题。

已解决和已知问题列于NetApp Bugs Online 工具中。您可以浏览 Element 软件和其他产品的这些问题，网址为： https://mysupport.netapp.com/site/products/all/details/element-software/bugsonline-tab["NetApp Bug Online"^] 。



== 元素 12.5

了解 Element 12.5 的新增功能。



=== 改进的存储节点访问

Element 12.5 版本通过签名 SSH 证书改进了对单个节点的远程访问。为了提供对存储节点的安全远程访问，需要创建一个新的、权限受限的本地用户帐户，名为 `sfreadonly`现在在存储节点的 RTFI 期间创建。这 `sfreadonly`该帐户允许访问存储节点后端，以进行基本维护或故障排除。您现在可以进行配置了 `supportAdmin`允许集群管理员用户访问集群的访问类型，以便NetApp支持人员根据需要访问集群。



=== 增强的自定义保护域管理能力

Element 12.5 具有全新的用户界面，使您能够快速轻松地查看现有的自定义保护域并配置新的自定义保护域。



=== 新增和改进的集群故障、事件和警报

Element 12.5 引入了新的集群故障代码，增强了系统故障排除功能。 `BmcSelfTestFailed`和 `CpuThermalEventThreshold`。  Element 12.5 还包含对现有集群事件和警报的稳健性改进，例如： `nodeOffline` ， `volumeOffline` ， `driveHealthFault` ， `networkEvent` ， 和	`cSumEvent`。



=== 从“创建集群”用户界面启用静态软件加密

Element 12.5 在创建集群 UI 中添加了一个新复选框，使您可以在创建集群期间为SolidFire全闪存存储集群启用集群范围的静态软件加密。



=== 存储节点固件更新

Element 12.5 包含存储节点的固件更新。link:../concepts/concept_rn_relatedrn_element.html#storage-firmware["了解更多"]。



=== 增强安全性

Element 12.5 包含缓解措施，可消除 Element 软件对 Apache Log4j 漏洞的暴露。启用虚拟卷 (VVols) 功能的NetApp SolidFire存储集群容易受到 Apache Log4j 漏洞的影响。有关NetApp Element软件中 Apache Log4j 漏洞的解决方法的信息，请参阅 {url-peak}[KB 文章^]。

如果您正在运行 Element 11.x、12.0 或 12.2，或者您的存储集群已经是 Element 12.3 或 12.3.1 并启用了 VVols 功能，则应升级到 12.5。

第 12.5 部分还包括 120 多个 CVE 安全漏洞修复措施。



== 查找更多信息

* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["NetApp混合云控制和管理服务发行说明"^]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element vCenter Server 插件"^]
* http://docs.netapp.com/sfe-122/index.jsp["SolidFire和 Element 软件文档中心（适用于先前版本）"^]
* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI文档"^]
* link:../hardware/fw_storage_nodes.html["SolidFire存储节点支持的存储固件版本"]

