---
permalink: concepts/concept_solidfire_concepts_nodes.html 
sidebar: sidebar 
keywords: what is, node, management node, storage node, fibre channel, state, pending, active 
summary: 节点是组成集群的硬件，可以作为块存储或计算资源进行访问。 
---
= 节点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
节点是硬件或虚拟资源，它们被分组到一个集群中，以提供块存储和计算能力。

NetApp Element软件定义了集群中的各种节点角色。节点角色类型如下：

* <<管理节点>>
* <<存储节点>>
* <<光纤通道节点>>


<<节点运行状态,节点状态>>因聚类关联而异。



== 管理节点

管理节点是一台虚拟机，用于升级和提供系统服务，包括监控和遥测、管理集群资产和设置、运行系统测试和实用程序，以及启用NetApp支持以进行故障排除。link:../concepts/concept_intro_management_node.html["了解更多"]



== 存储节点

SolidFire存储节点是一个服务器，其中包含一组驱动器，这些驱动器通过 Bond10G 网络接口相互通信。节点中的驱动器包含用于数据存储和数据管理的块空间和元数据空间。每个节点都包含NetApp Element软件的出厂镜像。

存储节点具有以下特点：

* 每个节点都有一个唯一的名称。如果管理员未指定节点名称，则默认为 SF-XXXX，其中 XXXX 是系统生成的四个随机字符。
* 每个节点都有自己的高性能非易失性随机存取存储器（NVRAM）写入缓存，以提高整体系统性能并降低写入延迟。
* 每个节点都连接到两个网络，存储网络和管理网络，每个网络都有两条独立的链路，以实现冗余和提高性能。每个节点在每个网络上都需要一个IP地址。
* 您可以创建一个包含新存储节点的集群，或者向现有集群添加存储节点，以提高存储容量和性能。
* 您可以随时向集群中添加或删除节点，而不会中断服务。




== 光纤通道节点

SolidFire光纤通道节点提供与光纤通道交换机的连接，您可以将光纤通道客户端连接到该交换机。光纤通道节点充当光纤通道和 iSCSI 协议之间的协议转换器；这使您可以将光纤通道连接添加到任何新的或现有的SolidFire集群。

光纤通道节点具有以下特点：

* 光纤通道交换机管理光纤网络状态，提供优化的互连。
* 两个端口之间的流量仅通过交换机传输；不会传输到任何其他端口。
* 单个端口故障是孤立的，不会影响其他端口的运行。
* 在一个网络结构中，多对端口可以同时进行通信。




== 节点运行状态

根据配置级别的不同，节点可以处于几种状态之一。

* *可用的*
+
该节点没有关联的集群名称，也尚未成为集群的一部分。

* *待办的*
+
节点已配置完毕，可以添加到指定的集群中。

+
访问该节点无需身份验证。

* *待激活*
+
系统正在节点上安装兼容的 Element 软件。完成后，节点将变为活动状态。

* *积极的*
+
该节点正在参与集群。

+
修改节点需要进行身份验证。



在这些状态下，有些字段是只读的。



== 查找更多信息

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire和 Element 软件文档"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element vCenter Server 插件"^]

