---
permalink: concepts/concept_intro_clusters.html 
sidebar: sidebar 
keywords: element, solidfire, cluster, what is, authoritative  cluster, rule of thirds, stranded capacity, storage efficiency, storage cluster quorum 
summary: 集群是SolidFire存储系统的核心，由多个节点组成。要实现SolidFire存储效率，集群中必须至少有四个节点。集群在网络上表现为一个单一的逻辑组，然后可以像块存储一样进行访问。 
---
= 集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
集群是SolidFire存储系统的核心，由多个节点组成。要实现SolidFire存储效率，集群中必须至少有四个节点。集群在网络上表现为一个单一的逻辑组，然后可以像块存储一样进行访问。

创建新集群会将一个节点初始化为集群的通信所有者，并为集群中的每个节点建立网络通信。此过程仅对每个新集群执行一次。您可以使用 Element UI 或 API 创建集群。

您可以通过添加额外的节点来扩展集群。添加新节点时，服务不会中断，集群会自动利用新节点的性能和容量。

管理员和主机可以使用虚拟 IP 地址访问集群。集群中的任何节点都可以托管虚拟 IP 地址。管理虚拟 IP (MVIP) 可通过 1GbE 连接实现集群管理，而存储虚拟 IP (SVIP) 可通过 10GbE 连接实现主机对存储的访问。这些虚拟 IP 地址能够确保连接稳定，无论SolidFire集群的大小或组成如何。如果承载虚拟 IP 地址的节点发生故障，集群中的另一个节点将开始承载该虚拟 IP 地址。


NOTE: 从 Element 版本 11.0 开始，节点可以配置 IPv4、IPv6 或两者的地址作为其管理网络。这适用于存储节点和管理节点，但管理节点 11.3 及更高版本除外，该版本不支持 IPv6。创建集群时，MVIP 只能使用单个 IPv4 或 IPv6 地址，并且必须在所有节点上配置相应的地址类型。

.关于集群的更多信息
* <<权威存储集群>>
* <<三分法>>
* <<搁浅产能>>
* <<存储效率>>
* <<存储集群仲裁>>




== 权威存储集群

权威存储集群是NetApp Hybrid Cloud Control 用于验证用户身份的存储集群。

如果您的管理节点只有一个存储集群，那么它就是权威集群。如果您的管理节点有两个或多个存储集群，则其中一个集群将被指定为权威集群，并且只有该集群中的用户才能登录到NetApp Hybrid Cloud Control。要找出哪个集群是权威集群，可以使用以下方法： `GET /mnode/about` API。响应中包含 IP 地址 `token_url`该字段是权威存储集群的管理虚拟 IP 地址 (MVIP)。如果您尝试以不在权威集群上的用户身份登录NetApp Hybrid Cloud Control，则登录尝试将失败。

NetApp Hybrid Cloud Control 的许多功能旨在与多个存储集群配合使用，但身份验证和授权存在局限性。身份验证和授权方面的限制是，即使用户不是其他存储集群上的用户，权威集群中的用户也可以对与NetApp Hybrid Cloud Control 关联的其他集群执行操作。

在开始管理多个存储集群之前，您应该确保在权威集群上定义的用户在所有其他存储集群上都具有相同的权限。您可以从以下位置管理用户link:../storage/concept_system_manage_manage_cluster_administrator_users.html["Element软件用户界面"]。

看link:../mnode/task_mnode_manage_storage_cluster_assets.html["创建和管理存储集群资产"]有关使用管理节点存储集群资产的更多信息。



== 三分法

在NetApp SolidFire存储集群中混合使用存储节点类型时，任何单个存储节点的容量都不能超过整个存储集群容量的 33%。



== 搁浅产能

如果新添加的节点占集群总容量的 50% 以上，则该节点的部分容量将被禁用（“闲置”），以使其符合容量规则。在增加更多存储容量之前，这种情况将一直持续下去。如果添加一个非常大的节点，并且该节点也违反容量规则，则先前被困的节点将不再被困，而新添加的节点将变为被困。为避免这种情况发生，容量应该始终成对添加。当节点发生孤立状态时，会抛出相应的集群故障。



== 存储效率

Netapp SolidFire存储集群利用重复数据删除、压缩和精简配置来减少存储卷所需的物理存储空间。

* *压缩*
+
压缩通过将数据块组合成压缩组来减少卷所需的物理存储空间，每个压缩组都作为一个单独的块存储。

* *去重*
+
数据去重通过丢弃重复的数据块来减少卷所需的物理存储空间。

* *精简配置*
+
精简配置卷或 LUN 是指没有预先预留存储空间的卷或 LUN。相反，存储空间是根据需要动态分配的。当卷或 LUN 中的数据被删除时，可用空间将被释放回存储系统。





== 存储集群仲裁

Element 软件从选定的节点创建一个存储集群，该集群维护一个集群配置的复制数据库。为了维持集群的弹性，集群集成至少需要三个节点参与。
