---
permalink: concepts/concept_solidfire_concepts_data_protection.html 
sidebar: sidebar 
keywords: what is, element, solidfire, replication, clone, snapshot, protection domain, double helix 
summary: 数据保护功能包括远程复制、卷快照、卷克隆、保护域以及采用双螺旋技术的高可用性。 
---
= 数据保护
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
数据保护功能包括远程复制、卷快照、卷克隆、保护域以及采用双螺旋技术的高可用性。

元素存储数据保护包括以下概念：

* <<远程复制类型>>
* <<用于数据保护的卷快照>>
* <<卷克隆>>
* <<Element存储的备份和恢复流程概述>>
* <<保护域>>
* <<custom_pd,自定义保护域>>
* <<双螺旋高可用性>>




== 远程复制类型

远程数据复制可以采取以下几种形式：

* <<集群间的同步和异步复制>>
* <<仅快照复制>>
* <<使用SnapMirror在 Element 和ONTAP集群之间进行复制>>


更多信息请参见 https://www.netapp.com/pdf.html?item=/media/10607-tr4741pdf.pdf["TR-4741： NetApp Element软件远程复制"^]。



=== 集群间的同步和异步复制

对于运行NetApp Element软件的集群，实时复制可以快速创建卷数据的远程副本。

您可以将一个存储集群与最多四个其他存储集群配对。对于故障转移和故障恢复场景，您可以从集群对中的任一集群同步或异步复制卷数据。



==== 同步复制

同步复制会将数据从源集群持续复制到目标集群，但会受到延迟、丢包、抖动和带宽的影响。

同步复制适用于以下情况：

* 在短距离内复制多个系统
* 灾难恢复站点的地理位置应与源站点相近
* 时间敏感型应用和数据库保护
* 业务连续性应用程序要求在主站点宕机时，备用站点能够充当主站点。




==== 异步复制

异步复制会持续地将数据从源集群复制到目标集群，而无需等待目标集群的确认。在异步复制过程中，写入操作在源集群上提交后，会向客户端（应用程序）发出确认通知。

异步复制适用于以下情况：

* 灾难恢复站点距离源头很远，而且应用程序无法容忍网络延迟。
* 连接源集群和目标集群的网络带宽有限。




=== 仅快照复制

仅快照数据保护会在特定时间点将已更改的数据复制到远程集群。只有在源集群上创建的快照才会被复制。来自源卷的活动写入操作不会发生。

您可以设置快照复制的频率。

快照复制不会影响异步复制或同步复制。



=== 使用SnapMirror在 Element 和ONTAP集群之间进行复制

借助NetApp SnapMirror技术，您可以将使用NetApp Element软件拍摄的快照复制到ONTAP ，以用于灾难恢复。在SnapMirror关系中，Element 是一个端点， ONTAP是另一个端点。

SnapMirror是NetApp 的快照复制技术，可实现灾难恢复，专为从主存储故障转移到地理位置偏远的辅助存储而设计。 SnapMirror技术会在辅助存储中创建工作数据的副本或镜像，以便在主站点发生故障时继续提供数据。数据在卷级别上进行镜像。

主存储器中的源卷与辅助存储器中的目标卷之间的关系称为数据保护关系。集群被称为卷所在的端点，包含复制数据的卷必须相互连接。对等关系使集群和卷能够安全地交换数据。

SnapMirror可在NetApp ONTAP控制器上原生运行，并集成到 Element 中，Element 可在NetApp HCI和SolidFire集群上运行。控制SnapMirror的逻辑位于ONTAP软件中；因此，所有SnapMirror关系都必须至少涉及一个ONTAP系统来执行协调工作。用户主要通过 Element UI 管理 Element 和ONTAP集群之间的关系；但是，一些管理任务位于NetApp ONTAP系统管理器中。用户还可以通过 CLI 和 API 管理SnapMirror ，这两种方式在ONTAP和 Element 中均可用。

看 https://fieldportal.netapp.com/content/616239["TR-4651： NetApp SolidFire SnapMirror架构和配置"^]（需要登录）

您必须使用 Element 软件在集群级别手动启用SnapMirror功能。  SnapMirror功能默认处于禁用状态，并且在新安装或升级过程中不会自动启用。

启用SnapMirror后，您可以从 Element 软件中的“数据保护”选项卡创建SnapMirror关系。

NetApp Element软件 10.1 及更高版本支持SnapMirror功能，可复制和恢复ONTAP系统的快照。

运行 Element 10.1 及更高版本的系统包含可以直接与运行 9.3 或更高版本的ONTAP系统上的SnapMirror通信的代码。 Element API 提供了在集群、卷和快照上启用SnapMirror功能的方法。此外，Element UI 还包含管理 Element 软件和ONTAP系统之间SnapMirror关系的功能。

从 Element 10.3 和ONTAP 9.4 系统开始，您可以在特定用例中将ONTAP源卷复制到 Element 卷，但功能有限。

有关详细信息，请参阅 link:../storage/element-replication-index.html["NetApp Element软件与ONTAP (ONTAP CLI) 之间的复制"]。



== 用于数据保护的卷快照

卷快照是卷在特定时间点的副本，您可以稍后使用该副本将卷还原到该特定时间点。

虽然快照与卷克隆类似，但快照只是卷元数据的副本，因此您无法挂载或写入它们。创建卷快照也只需要少量系统资源和空间，因此快照创建速度比克隆更快。

您可以将快照复制到远程集群，并将其用作卷的备份副本。这样，您就可以使用复制快照将卷回滚到特定时间点；您还可以从复制快照创建卷的克隆。

您可以将 Element 集群中的快照备份到外部对象存储，或者备份到另一个 Element 集群。将快照备份到外部对象存储时，必须与该对象存储建立允许读/写操作的连接。

您可以对单个卷或多个卷进行快照以保护数据。



== 卷克隆

单个卷或多个卷的克隆是数据在特定时间点的副本。克隆卷时，系统会创建卷的快照，然后创建快照引用的数据的副本。

这是一个异步过程，该过程所需的时间取决于您要克隆的卷的大小和当前的集群负载。

集群一次最多支持每个卷运行两个克隆请求，一次最多支持八个活动卷克隆操作。超出这些限制的请求将被排队，稍后处理。



== Element存储的备份和恢复流程概述

您可以将卷备份和恢复到其他SolidFire存储，以及与 Amazon S3 或 OpenStack Swift 兼容的辅助对象存储。

您可以将卷备份到以下位置：

* SolidFire存储集群
* 亚马逊 S3 对象存储
* OpenStack Swift 对象存储


从 OpenStack Swift 或 Amazon S3 恢复卷时，需要原始备份过程中的清单信息。如果您要恢复备份在SolidFire存储系统上的卷，则不需要清单信息。



== 保护域

保护域是指将一个或多个节点组合在一起，使得其中任何部分甚至全部发生故障，都能保持数据可用性。保护域使存储集群能够从机箱（机箱亲和性）或整个域（机箱组）的丢失中自动恢复。

您可以使用NetApp Element Plugin for vCenter Server 中的NetApp Element配置扩展点手动启用保护域监控。您可以根据节点域或机箱域选择保护域阈值。您还可以使用 Element API 或 Web UI 启用保护域监控。

保护域布局将每个节点分配到一个特定的保护域。

支持两种不同的保护域布局，称为保护域级别。

* 在节点级别，每个节点都有自己的保护域。
* 在机箱级别，只有共享同一机箱的节点才处于同一保护域中。
+
** 当节点添加到集群时，机箱级布局会根据硬件自动确定。
** 在每个节点都位于独立机箱中的集群中，这两个级别的功能是相同的。




创建新集群时，如果您使用的是位于共享机箱中的存储节点，则可能需要考虑使用保护域功能来设计机箱级故障保护。



== 自定义保护域

您可以定义一个自定义保护域布局，使其与您的特定机箱和节点布局相匹配，其中每个节点都与一个且仅一个自定义保护域相关联。默认情况下，每个节点都分配到同一个默认自定义保护域。

如果未分配任何自定义保护域：

* 集群运行不受影响。
* 自定义级别既不宽容也不灵活。


为集群配置自定义保护域时，有三个可能的保护级别，您可以在 Element Web UI 仪表板中查看这些级别：

* 未受保护：存储集群未受到保护，无法抵御其某个自定义保护域的故障。要解决此问题，请向集群添加额外的存储容量，或重新配置集群的自定义保护域，以保护集群免受可能的数据丢失。
* 容错性：存储集群具有足够的可用容量，以防止其某个自定义保护域发生故障后数据丢失。
* 容错能力强：存储集群具有足够的可用容量，可以在其某个自定义保护域发生故障后进行自我修复。修复过程完成后，即使其他域发生故障，集群也能免受数据丢失的影响。


如果分配了多个自定义保护域，则每个子系统会将重复项分配给不同的自定义保护域。如果无法做到这一点，则退而求其次，将重复项分配到不同的节点。每个子系统（例如，箱子、切片、协议端点提供程序和集合）独立地执行此操作。

您可以使用 Element UI 来link:../storage/task_data_protection_configure_custom_protection_domains.html["配置自定义保护域"]或者，您可以使用以下 API 方法：

* link:../api/reference_element_api_getprotectiondomainlayout.html["获取保护域布局"]- 显示每个节点所在的机箱和自定义保护域。
* link:../api/reference_element_api_setprotectiondomainlayout.html["设置保护域布局"]- 允许为每个节点分配自定义保护域。




== 双螺旋高可用性

双螺旋数据保护是一种复制方法，它将至少两个冗余数据副本分布在系统内的所有驱动器上。  “无 RAID”方法使系统能够承受存储系统所有层级上的多个并发故障，并快速修复。
