---
permalink: storage/concept_data_manage_vvol_manage_storage_containers.html 
sidebar: sidebar 
keywords: storage container, storage containers, about storage containers, cluster, vvols, create, view details, chap, edit, delete 
summary: 存储容器是在运行 Element 软件的集群上创建的 vSphere 数据存储表示。 
---
= 管理存储容器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
存储容器是在运行 Element 软件的集群上创建的 vSphere 数据存储表示。

创建存储容器并将其与NetApp Element帐户关联。在 Element 存储上创建的存储容器在 vCenter 和 ESXi 中显示为 vSphere 数据存储。存储容器不会在 Element 存储上分配任何空间。它们的作用仅仅是将虚拟卷在逻辑上关联起来。

每个集群最多支持四个存储容器。要启用 VVols 功能，至少需要一个存储容器。



== 创建一个存储容器

您可以在 Element UI 中创建存储容器，并在 vCenter 中发现它们。要开始配置 VVol 支持的虚拟机，您必须至少创建一个存储容器。

开始之前，请在集群的 Element UI 中启用 VVols 功能。

.步骤
. 选择 *VVols* > *存储容器*。
. 点击“创建存储容器”按钮。
. 在“创建新存储容器”对话框中输入存储容器信息：
+
.. 请输入存储容器的名称。
.. 配置 CHAP 的发起方密钥和目标密钥。
+

TIP: 将 CHAP 设置字段留空以自动生成密钥。

.. 点击“创建存储容器”按钮。


. 确认新存储容器出现在“存储容器”子选项卡的列表中。
+

NOTE: 由于NetApp Element帐户 ID 会自动创建并分配给存储容器，因此无需手动创建帐户。





== 查看存储容器详情

在 VVols 选项卡的“存储容器”页面上，您可以查看集群上所有活动存储容器的信息。

* *帐户 ID*：与存储容器关联的NetApp Element帐户的 ID。
* *名称*：存储容器的名称。
* *状态*：存储容器的状态。可能值：
+
** 活动状态：存储容器正在使用中。
** 已锁定：储物容器已锁定。


* *PE 类型*：协议端点类型（SCSI 是 Element 软件唯一可用的协议）。
* *存储容器 ID*：虚拟卷存储容器的 UUID。
* *活动虚拟卷*：与存储容器关联的活动虚拟卷的数量。




== 查看单个存储容器的详细信息

您可以通过在 VVols 选项卡的“存储容器”页面上选择单个存储容器来查看其存储容器信息。

* *帐户 ID*：与存储容器关联的NetApp Element帐户的 ID。
* *名称*：存储容器的名称。
* *状态*：存储容器的状态。可能值：
+
** 活动状态：存储容器正在使用中。
** 已锁定：储物容器已锁定。


* *CHAP发起者秘密*：发起者独有的CHAP秘密。
* *CHAP目标秘密*：针对目标的独特CHAP秘密。
* *存储容器 ID*：虚拟卷存储容器的 UUID。
* *协议端点类型*：指示协议端点类型（SCSI 是唯一可用的协议）。




== 编辑存储容器

您可以在 Element UI 中修改存储容器的 CHAP 身份验证。

. 选择 *VVols* > *存储容器*。
. 点击要编辑的存储容器旁边的“操作”图标。
. 在出现的菜单中，选择“编辑”。
. 在 CHAP 设置中，编辑用于身份验证的发起方密钥和目标密钥凭据。
+

TIP: 如果您不更改 CHAP 设置凭据，则它们将保持不变。如果将凭据字段留空，系统会自动生成新的密钥。

. 点击“保存更改”。




== 删除存储容器

您可以从 Element 用户界面删除存储容器。

.你需要什么
确保所有虚拟机都已从 VVol 数据存储中删除。

.步骤
. 选择 *VVols* > *存储容器*。
. 点击要删除的存储容器旁边的“操作”图标。
. 在出现的菜单中，选择“删除”。
. 确认此操作。
. 刷新“存储容器”子选项卡中的存储容器列表，以确认存储容器已被删除。

