---
permalink: storage/concept_data_manage_data_management.html 
sidebar: sidebar 
keywords: virtual volumes, volumes, manage 
summary: '您可以通过 Element UI 中的“管理”选项卡管理运行 Element 软件的集群中的数据。可用的集群管理功能包括创建和管理数据卷、用户帐户、卷访问组、发起程序和服务质量 (QoS) 策略。' 
---
= 了解如何管理卷和虚拟卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过 Element UI 中的“管理”选项卡管理运行 Element 软件的集群中的数据。可用的集群管理功能包括创建和管理数据卷、卷访问组、发起程序和服务质量 (QoS) 策略。



== 使用卷

SolidFire系统使用卷来配置存储。卷是可通过网络由 iSCSI 或光纤通道客户端访问的块设备。在“管理”选项卡的“卷”页面上，您可以创建、修改、克隆和删除节点上的卷。您还可以查看有关卷带宽和 I/O 使用情况的统计信息。

link:../storage/concept_data_manage_volumes_quality_of_service_policies.html["了解如何处理卷"]



== 使用虚拟卷

您可以使用 Element UI 查看虚拟卷及其关联的存储容器、协议端点、绑定和主机的信息并执行相关任务。

NetApp Element软件存储系统出厂时默认禁用虚拟卷 (VVols) 功能。您必须通过 Element UI 手动启用 vSphere VVol 功能，此操作为一次性任务。

启用 VVol 功能后，用户界面中会出现一个 VVols 选项卡，提供与 VVols 相关的监控和有限的管理选项。此外，一个名为 VASA Provider 的存储端软件组件充当 vSphere 的存储感知服务。大多数 VVols 命令（例如 VVol 创建、克隆和编辑）由 vCenter Server 或 ESXi 主机发起，并由 VASA Provider 转换为 Element 软件存储系统的 Element API。可以使用 Element UI 发起创建、删除和管理存储容器以及删除虚拟卷的命令。

使用 Element 软件存储系统的虚拟卷功能所需的大部分配置都在 vSphere 中完成。请参阅《VMware vSphere Virtual Volumes for SolidFire Storage Configuration Guide》以在 vCenter 中注册 VASA Provider、创建和管理 VVol 数据存储以及根据策略管理存储。


NOTE: 对于 Element 12.5 及更早版本，请勿向单个 vCenter 实例注册多个NetApp Element VASA 提供程序。如果添加了第二个NetApp Element VASA 提供程序，则所有 VVOL 数据存储都将无法访问。


NOTE: 如果您已将 VASA 提供商注册到 vCenter，则可通过升级补丁获得对多个 vCenter 的 VASA 支持。要安装，请从以下位置下载 VASA39 .tar.gz 文件： https://mysupport.netapp.com/products/element_software/VASA39/index.html["NetApp软件下载"]前往现场并按照清单上的说明进行操作。 NetApp Element VASA 提供程序使用NetApp证书。通过此补丁，vCenter 可以直接使用未经修改的证书，以支持多个 vCenter 用于 VASA 和 VVols。请勿修改证书。  VASA 不支持自定义 SSL 证书。

link:../storage/task_data_manage_vvol_enable_virtual_volumes.html["了解如何使用虚拟卷"]



== 与批量访问组和发起者合作

您可以使用 iSCSI 发起程序或光纤通道发起程序来访问卷访问组中定义的卷。

您可以通过映射卷集合中的 iSCSI 发起程序 IQN 或光纤通道 WWPN 来创建访问组。添加到访问组的每个 IQN 都可以访问组中的每个卷，而无需 CHAP 身份验证。

CHAP认证方法有两种类型：

* 账户级 CHAP 认证：您可以为账户分配 CHAP 认证。
* 发起方级 CHAP 身份验证：您可以为特定发起方分配唯一的 CHAP 目标和密钥，而无需在单个帐户中绑定到单个 CHAP。这种发起方级别的 CHAP 身份验证取代了帐户级别的凭据。


（可选）使用每个发起方的 CHAP，您可以强制执行发起方授权和每个发起方的 CHAP 身份验证。这些选项可以根据每个发起者进行定义，一个访问组可以包含具有不同选项的多个发起者。

将每个 WWPN 添加到访问组即可启用对访问组中卷的光纤通道网络访问。


NOTE: 卷访问组具有以下限制：

* 一个访问组中最多允许有 64 个 IQN 或 WWPN。
* 一个访问组最多可以包含 2000 卷。
* 一个 IQN 或 WWPN 只能属于一个访问组。
* 一个卷册最多可以属于四个访问组。


link:../storage/task_data_manage_vol_access_group_create_a_volume_access_group.html["了解如何与批量访问组和发起者合作"]



== 了解更多信息

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire和 Element 软件文档"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element vCenter Server 插件"^]

