---
permalink: storage/concept_system_manage_manage_cluster_administrator_users.html 
sidebar: sidebar 
keywords: element, solidfire, cluster admin, account, create, change, configure, administrator access, edit permissions, change passwords 
summary: 您可以管理SolidFire存储系统的集群管理员帐户。可用的集群管理员管理功能包括创建、删除和编辑集群管理员帐户，更改集群管理员密码，以及配置 LDAP 设置以管理系统用户访问权限。 
---
= 管理集群管理员用户帐户
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以管理SolidFire存储系统的集群管理员帐户，方法是创建、删除和编辑集群管理员帐户，更改集群管理员密码，以及配置 LDAP 设置以管理系统用户访问权限。



== 存储集群管理员帐户类型

在运行NetApp Element软件的存储集群中，可以存在两种类型的管理员帐户：主集群管理员帐户和集群管理员帐户。

* *主集群管理员帐户*
+
此管理员帐户是在创建集群时创建的。该帐户是集群中具有最高访问权限的主要管理帐户。该账户类似于 Linux 系统中的 root 用户。您可以更改此管理员帐户的密码。

* *集群管理员帐户*
+
您可以授予集群管理员帐户有限的管理权限，使其能够在集群内执行特定任务。分配给每个集群管理员帐户的凭据用于验证存储系统中的 API 和 Element UI 请求。




NOTE: 要通过每个节点的 UI 访问集群中的活动节点，需要本地（非 LDAP）集群管理员帐户。访问尚未加入集群的节点不需要账户凭证。



== 查看集群管理员详细信息

. 要创建集群范围（非 LDAP）的集群管理员帐户，请执行以下操作：
+
.. 点击“用户”>“集群管理员”。


. 在“用户”选项卡的“集群管理员”页面上，您可以查看以下信息。
+
** *ID*：分配给集群管理员帐户的顺序编号。
** *用户名*：创建集群管理员帐户时赋予该帐户的名称。
** *访问权限*：分配给用户帐户的用户权限。可能值：
+
*** read
*** reporting
*** 节点
*** 驱动
*** 卷
*** 账户
*** 集群管理员
*** administrator
*** 支持管理员




+
[NOTE]
====
所有权限均对管理员访问类型可用。

通过 API 可以访问 Element UI 中没有的某些访问类型。

====
+
** *类型*：集群管理员的类型。可能值：
+
*** 集群
*** LDAP


** *属性*：如果集群管理员帐户是使用 Element API 创建的，则此列显示使用该方法设置的任何名称-值对。
+
看link:../api/concept_element_api_about_the_api.html["NetApp Element软件 API 参考"]。







== 创建集群管理员帐户

您可以创建新的集群管理员帐户，并授予其权限以允许或限制对存储系统特定区域的访问。设置集群管理员帐户权限时，系统会授予您未分配给集群管理员的任何权限的只读权限。

如果要创建 LDAP 集群管理员帐户，请确保在开始之前已在集群上配置 LDAP。

link:concept_system_manage_manage_ldap.html["使用 Element 用户界面启用 LDAP 身份验证"]

之后您可以更改集群管理员帐户的报表、节点、驱动器、卷、帐户和集群级访问权限。启用权限后，系统会为该级别分配写入权限。系统会授予管理员用户只读权限，仅对您未选择的级别有效。

之后您还可以删除系统管理员创建的任何集群管理员用户帐户。您无法删除创建集群时创建的主集群管理员帐户。

. 要创建集群范围（非 LDAP）的集群管理员帐户，请执行以下操作：
+
.. 点击“用户”>“集群管理员”。
.. 点击“创建集群管理员”。
.. 选择“集群”用户类型。
.. 输入账号和密码，并确认密码。
.. 选择要应用于帐户的用户权限。
.. 选中此复选框即表示您同意最终用户许可协议。
.. 点击“创建集群管理员”。


. 要在 LDAP 目录中创建集群管理员帐户，请执行以下操作：
+
.. 点击“集群”>“LDAP”。
.. 请确保已启用 LDAP 身份验证。
.. 点击“测试用户身份验证”，复制显示的用户或用户所属组之一的专有名称，以便稍后粘贴。
.. 点击“用户”>“集群管理员”。
.. 点击“创建集群管理员”。
.. 选择 LDAP 用户类型。
.. 在“专有名称”字段中，按照文本框中的示例输入用户或组的完整专有名称。或者，从你之前复制的专有名称中粘贴。
+
如果专有名称属于某个组，则 LDAP 服务器上该组的任何成员用户都将拥有此管理员帐户的权限。

+
要添加 LDAP 集群管理员用户或组，用户名的通用格式为“`LDAP:<完整可分辨名称>`”。

.. 选择要应用于帐户的用户权限。
.. 选中此复选框即表示您同意最终用户许可协议。
.. 点击“创建集群管理员”。






== 编辑集群管理员权限

您可以更改集群管理员帐户的报表、节点、驱动器、卷、帐户和集群级访问权限。启用权限后，系统会为该级别分配写入权限。系统会授予管理员用户只读权限，仅对您未选择的级别有效。

. 点击“用户”>“集群管理员”。
. 单击要编辑的集群管理员旁边的“操作”图标。
. 单击“*编辑*”。
. 选择要应用于帐户的用户权限。
. 点击“保存更改”。




== 更改集群管理员帐户的密码

您可以使用 Element UI 更改集群管理员密码。

. 点击“用户”>“集群管理员”。
. 单击要编辑的集群管理员旁边的“操作”图标。
. 单击“*编辑*”。
. 在“更改密码”字段中，输入新密码并确认。
. 点击“保存更改”。


.相关信息
* link:../api/reference_element_api_app_b_access_control.html["了解 Element API 可用的访问类型"]
* link:concept_system_manage_manage_ldap.html["使用 Element 用户界面启用 LDAP 身份验证"]
* link:concept_system_manage_manage_ldap.html["禁用 LDAP"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element vCenter Server 插件"^]

