---
permalink: storage/concept_data_protection.html 
sidebar: sidebar 
keywords: data protection, protect your data, snapshots, replication, back up 
summary: NetApp Element软件能够以多种方式保护您的数据，其功能包括：为单个卷或卷组创建快照、在 Element 上运行的集群和卷之间进行复制，以及复制到ONTAP系统。 
---
= 保护您的数据
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Element软件能够以多种方式保护您的数据，其功能包括：为单个卷或卷组创建快照、在 Element 上运行的集群和卷之间进行复制，以及复制到ONTAP系统。

* *快照*
+
仅快照数据保护会在特定时间点将已更改的数据复制到远程集群。只有在源集群上创建的快照才会被复制。来自源卷的活动写入操作不会发生。

+
xref:task_data_protection_using_volume_snapshots.adoc[使用卷快照进行数据保护]

* *在 Element 上运行的集群和卷之间的远程复制*
+
您可以同步或异步地从集群对中的任何一个集群复制卷数据，这两个集群都在 Element 上运行，以实现故障转移和故障恢复场景。

+
xref:task_replication_perform_remote_replication_between_element_clusters.adoc[在运行NetApp Element软件的集群之间执行远程复制]

* *使用SnapMirror技术在 Element 和ONTAP集群之间进行复制*
+
借助NetApp SnapMirror技术，您可以将使用 Element 拍摄的快照复制到ONTAP ，以用于灾难恢复。在SnapMirror关系中，Element 是一个端点， ONTAP是另一个端点。

+
xref:task_snapmirror_use_replication_between_element_and_ontap_clusters.adoc[在 Element 和ONTAP集群之间使用SnapMirror复制]

* *备份和恢复来自SolidFire、S3 或 Swift 对象存储的卷*
+
您可以将卷备份和恢复到其他SolidFire存储，以及与 Amazon S3 或 OpenStack Swift 兼容的辅助对象存储。

+
xref:task_data_protection_back_up_and_restore_volumes.adoc[将卷备份和恢复到SolidFire、S3 或 Swift 对象存储]





== 了解更多信息

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire和 Element 软件文档"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element vCenter Server 插件"^]

