---
permalink: storage/concept_troubleshoot_basic_mdss_drive_troubleshooting.html 
sidebar: sidebar 
keywords: mdss drives, troubleshoot, multi-drive slice service 
summary: 如果一个或两个元数据驱动器发生故障，您可以通过将元数据（或切片）驱动器重新添加到集群来恢复它们。如果节点上已启用 MDSS 功能，则可以在NetApp Element UI 中执行恢复操作。 
---
= MDSS驱动器基本故障排除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果一个或两个元数据驱动器发生故障，您可以通过将元数据（或切片）驱动器重新添加到集群来恢复它们。如果节点上已启用 MDSS 功能，则可以在NetApp Element UI 中执行恢复操作。

如果节点中的一个或两个元数据驱动器发生故障，切片服务将关闭，并且来自两个驱动器的数据将备份到节点中的不同驱动器。

以下场景概述了可能出现的故障情况，并提供了纠正问题的基本建议：



== 系统切片驱动器故障

* 在这种情况下，槽位 2 经过验证后恢复为可用状态。
* 必须先重新安装系统切片驱动器，才能恢复切片服务。
* 当系统分区驱动器可用时，您应该更换系统分区驱动器，同时添加该驱动器和插槽 2 驱动器。



NOTE: 你不能单独将硬盘添加到插槽 2 中作为元数据硬盘。必须同时将两个硬盘添加到节点中。



== 插槽 2 故障

* 在这种情况下，系统切片驱动器经过验证后恢复到可用状态。
* 当插槽 2 可用时，应将插槽 2 更换为备用硬盘，同时添加系统切片硬盘和插槽 2 硬盘。




== 系统切片驱动器和插槽 2 故障

* 您应该将系统分区驱动器和插槽 2 都更换为备用驱动器。当两个硬盘都可用时，同时添加系统切片硬盘和插槽 2 硬盘。




== 操作顺序

* 用备用硬盘替换故障的硬件硬盘（如果两个硬盘都发生故障，则两个硬盘都需更换）。
* 当驱动器重新加载完毕且处于可用状态时，将其重新添加到集群中。




== 验证操作

* 确认插槽 0（或内部）和插槽 2 中的驱动器在“活动驱动器”列表中被识别为元数据驱动器。
* 确认所有切片平衡已完成（至少 30 分钟内事件日志中没有进一步移动切片的消息）。




== 了解更多信息

xref:task_troubleshoot_add_mdss_drives.adoc[添加 MDSS 驱动器]
