---
permalink: storage/concept_monitor_understand_cluster_fullness_levels.html 
sidebar: sidebar 
keywords: cluster fullness levels, understanding, fullness levels 
summary: 运行 Element 软件的集群会在集群容量不足时生成集群故障，以警告存储管理员。集群填充程度分为三个级别，所有这些级别都会显示在NetApp Element UI 中：警告、错误和严重。 
---
= 了解集群填充程度
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
运行 Element 软件的集群会在集群容量不足时生成集群故障，以警告存储管理员。集群填充程度分为三个级别，所有这些级别都会显示在NetApp Element UI 中：警告、错误和严重。

系统使用 BlockClusterFull 错误代码来警告集群块存储已满。您可以在 Element UI 的“警报”选项卡中查看集群满负荷严重级别。

以下列表包含有关 BlockClusterFull 严重级别的信息：

* *警告*
+
这是一个客户可配置的警告，当集群的块容量接近错误严重级别时，该警告会显示。默认情况下，此级别设置为比错误级别低 3%，可通过 Element UI 和 API 进行调整。您必须尽快增加容量或释放容量。

* *错误*
+
当集群处于这种状态时，如果一个节点丢失，集群中将没有足够的容量来重建双螺旋数据保护。如果集群处于此状态，则不允许创建新卷、执行克隆和生成快照。任何集群都不应处于这种安全或推荐的状态。您必须增加容量或立即释放容量。

* *批判的*
+
出现此严重错误是因为集群资源已 100% 使用。它处于只读状态，无法与集群建立新的 iSCSI 连接。达到这个阶段后，您必须立即释放或增加更多容量。



系统使用 MetadataClusterFull 错误代码来警告集群元数据存储空间已满。您可以在 Element UI 的“报告”选项卡的“概览”页面上的“集群容量”部分查看集群元数据存储已满情况。

以下列表包含有关 MetadataClusterFull 严重级别的信息：

* *警告*
+
这是一个客户可配置的警告，当集群的元数据容量接近错误严重级别时，该警告会显示。默认情况下，此级别设置为比错误级别低 3%，可通过 Element API 进行调整。您必须尽快增加容量或释放容量。

* *错误*
+
当集群处于这种状态时，如果一个节点丢失，集群中将没有足够的容量来重建双螺旋数据保护。如果集群处于此状态，则不允许创建新卷、执行克隆和生成快照。任何集群都不应处于这种安全或推荐的状态。您必须增加容量或立即释放容量。

* *批判的*
+
出现此严重错误是因为集群资源已 100% 使用。它处于只读状态，无法与集群建立新的 iSCSI 连接。达到这个阶段后，您必须立即释放或增加更多容量。




NOTE: 以下内容适用于双节点集群阈值：

* 元数据完整性错误率比临界值低 20%。
* 块容量不足错误是指比临界容量少 1 个块驱动器（包括闲置容量）；这意味着比临界容量少了 2 个块驱动器的容量。

