---
permalink: storage/element-replication-index.html 
sidebar: sidebar 
keywords: ontap, cli, replication, element, software, ontap, business continuity, snapmirror, replicate, snapshot, copies, volume 
summary: 您可以使用SnapMirror将 Element 卷的快照副本复制到ONTAP目标，从而确保 Element 系统上的业务连续性。 
---
= NetApp Element软件与ONTAP之间的复制概览（ONTAP CLI）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用SnapMirror将 Element 卷的快照副本复制到ONTAP目标，从而确保 Element 系统上的业务连续性。如果 Element 站点发生灾难，您可以从ONTAP系统向客户端提供数据，然后在服务恢复后重新激活 Element 系统。

从ONTAP 9.4 开始，您可以将ONTAP节点上创建的 LUN 快照副本复制回 Element 系统。您可能在 Element 站点发生故障期间创建了 LUN，或者您可能正在使用 LUN 将数据从ONTAP迁移到 Element 软件。

如果符合以下条件，您应该使用 Element 进行ONTAP备份：

* 你应该采用最佳实践，而不是探索所有可行的方案。
* 您应该使用ONTAP命令行界面 (CLI)，而不是系统管理器或自动脚本工具。
* 您正在使用 iSCSI 向客户端提供数据。


如果您需要更多关于SnapMirror配置或概念方面的信息，请参阅link:https://docs.netapp.com/us-en/ontap/data-protection-disaster-recovery/index.html["数据保护概述"^]。



== 关于 Element 和ONTAP之间的复制

从ONTAP 9.3 开始，您可以使用SnapMirror将 Element 卷的快照副本复制到ONTAP目标。如果 Element 站点发生灾难，您可以从ONTAP系统向客户端提供数据，然后在服务恢复后重新激活 Element 源卷。

从ONTAP 9.4 开始，您可以将ONTAP节点上创建的 LUN 快照副本复制回 Element 系统。您可能在 Element 站点发生故障期间创建了 LUN，或者您可能正在使用 LUN 将数据从ONTAP迁移到 Element 软件。



=== 数据保护关系类型

SnapMirror提供两种数据保护关系。对于每种类型， SnapMirror会在初始化或更新关系之前创建 Element 源卷的快照副本：

* 在灾难恢复 (DR) 数据保护关系中，目标卷仅包含SnapMirror创建的快照副本，在主站点发生灾难时，您可以从中继续提供数据。
* 在长期保留数据保护关系中，目标卷包含 Element 软件创建的时间点快照副本，以及SnapMirror创建的快照副本。例如，您可能希望保留 20 年间创建的每月快照副本。




=== 默认策略

首次调用SnapMirror时，它会执行从源卷到目标卷的_基线传输_。  _SnapMirror 策略_ 定义了基线的内容以及任何更新。

创建数据保护关系时，您可以使用默认策略或自定义策略。策略类型决定了要包含哪些快照副本以及要保留多少个副本。

下表显示了默认策略。使用 `MirrorLatest`制定建立传统DR关系的政策。使用 `MirrorAndVault`或者 `Unified7year`创建统一复制关系的策略，其中灾难恢复和长期保留配置在同一目标卷上。

[cols="25,25,50"]
|===


| 策略 | 策略类型 | 更新行为 


 a| 
Mirror最新
 a| 
async-mirror
 a| 
传输由SnapMirror创建的快照副本。



 a| 
MirrorAndVault
 a| 
mirror-vault
 a| 
传输由SnapMirror创建的快照副本以及自上次更新以来创建的任何较旧的快照副本，前提是它们带有SnapMirror标签“`daily`”或“`weekly`”。



 a| 
Unified7year
 a| 
mirror-vault
 a| 
传输由SnapMirror创建的快照副本以及自上次更新以来创建的任何较旧的快照副本，前提是它们带有SnapMirror标签“`daily`”、“`weekly`”或“`monthly`”。

|===
[NOTE]
====
有关SnapMirror策略的完整背景信息，包括使用哪种策略的指南，请参阅link:https://docs.netapp.com/us-en/ontap/data-protection-disaster-recovery/index.html["数据保护概述"^]。

====


=== 了解SnapMirror标签

所有具有“`mirror-vault`”策略类型的策略都必须有一条规则，指定要复制哪些快照副本。例如，“`daily`”规则表示只有被赋予SnapMirror标签“`daily`”的快照副本才应该被复制。配置元素快照副本时，您可以分配SnapMirror标签。



=== 从 Element 源集群到ONTAP目标集群的复制

您可以使用SnapMirror将 Element 卷的快照副本复制到ONTAP目标系统。如果 Element 站点发生灾难，您可以从ONTAP系统向客户端提供数据，然后在服务恢复后重新激活 Element 源卷。

Element 容量大致相当于ONTAP LUN。当 Element 软件和ONTAP之间建立数据保护关系时， SnapMirror会创建一个与 Element 卷同名的 LUN。如果 LUN 满足 Element 到ONTAP复制的要求， SnapMirror会将数据复制到现有 LUN。

复制规则如下：

* 一个ONTAP卷只能包含来自一个 Element 卷的数据。
* 您无法将ONTAP卷中的数据复制到多个 Element 卷。




=== 从ONTAP源集群复制到 Element 目标集群

从ONTAP 9.4 开始，您可以将ONTAP系统上创建的 LUN 快照副本复制回 Element 卷：

* 如果 Element 源和ONTAP目标之间已经存在SnapMirror关系，则在从目标提供数据时创建的 LUN 会在源重新激活时自动复制。
* 否则，您必须在ONTAP源集群和 Element 目标集群之间创建并初始化SnapMirror关系。


复制规则如下：

* 复制关系必须具有“`async-mirror`”类型的策略。
+
不支持类型为“`mirror-vault`”的策略。

* 仅支持 iSCSI LUN。
* 一次只能将ONTAP卷中的单个 LUN 复制到 Element 卷。
* 您无法将ONTAP卷中的 LUN 复制到多个 Element 卷。




=== 前提条件

在配置 Element 和ONTAP之间的数据保护关系之前，您必须完成以下任务：

* Element 集群必须运行NetApp Element软件版本 10.1 或更高版本。
* ONTAP集群必须运行ONTAP 9.3 或更高版本。
* SnapMirror必须已在ONTAP集群上获得许可。
* 您必须在 Element 和ONTAP集群上配置足够大的卷，以处理预期的数据传输。
* 如果您使用的是“`mirror-vault`”策略类型，则必须配置SnapMirror标签才能复制 Element 快照副本。
+
[NOTE]
====
你只能在以下情况下执行此任务：link:concept_snapmirror_labels.html["Element 软件 Web 用户界面"]或使用link:../api/concept_element_api_snapshots_overview.html["API 方法"]。

====
* 您必须确保端口 5010 可用。
* 如果您预见到可能需要移动目标卷，则必须确保源和目标之间存在全网状连接。  Element 源集群上的每个节点都必须能够与ONTAP目标集群上的每个节点通信。




=== 支持详情

下表显示了 Element 到ONTAP备份的支持详情。

[cols="25,75"]
|===


| 资源或功能 | 支持详情 


 a| 
SnapMirror
 a| 
* 不支持SnapMirror恢复功能。
* 这 `MirrorAllSnapshots`和 `XDPDefault`不支持策略。
* 不支持“`vault`”策略类型。
* 系统定义的规则“`all_source_snapshots`”不受支持。
* “`mirror-vault`”策略类型仅支持从Element软件复制到ONTAP。使用“`async-mirror`”将ONTAP复制到 Element 软件。
* 这 `-schedule`和 `-prefix`选项 `snapmirror policy add-rule`不支持。
* 这 `-preserve`和 `-quick-resync`选项 `snapmirror resync`不支持。
* 存储效率无法保持。
* 不支持扇出式和级联式数据保护部署。




 a| 
ONTAP
 a| 
* ONTAP Select从ONTAP 9.4 和 Element 10.3 开始受支持。
* 从ONTAP 9.5 和 Element 11.0 开始支持Cloud Volumes ONTAP 。




 a| 
Element
 a| 
* 体积大小限制为 8 TiB。
* 卷块大小必须为 512 字节。不支持 4K 字节的块大小。
* 卷大小必须是 1 MiB 的倍数。
* 容量属性未被保留。
* 要复制的快照副本最大数量为 30。




 a| 
网络
 a| 
* 每次传输只允许建立一个 TCP 连接。
* 元素节点必须指定为 IP 地址。不支持DNS主机名查找。
* 不支持IP空间。




 a| 
SnapLock
 a| 
不支持SnapLock卷。



 a| 
FlexGroup
 a| 
不支持FlexGroup卷。



 a| 
支持向量机预测
 a| 
SVM DR 配置中的ONTAP卷不受支持。



 a| 
MetroCluster
 a| 
MetroCluster配置中的ONTAP卷不受支持。

|===