---
permalink: storage/reference_monitor_event_types.html 
sidebar: sidebar 
keywords: event types, monitor, event log 
summary: 该系统会报告多种类型的事件；每个事件都是系统已完成的一项操作。事件可以是例行、正常的事件，也可以是需要管理员关注的事件。事件日志页面上的“事件类型”列指示事件发生在系统的哪个部分。 
---
= 事件类型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
该系统会报告多种类型的事件；每个事件都是系统已完成的一项操作。事件可以是例行、正常的事件，也可以是需要管理员关注的事件。事件日志页面上的“事件类型”列指示事件发生在系统的哪个部分。


NOTE: 系统不会在事件日志中记录只读 API 命令。

以下列表描述了事件日志中出现的事件类型：

* *apiEvent*
+
用户通过 API 或 Web UI 发起的、修改设置的事件。

* *binAssignmentsEvent*
+
与数据箱分配相关的事件。箱子本质上是保存数据的容器，它们在集群中相互映射。

* *binSyncEvent*
+
与数据在块服务之间重新分配相关的系统事件。

* *bsCheckEvent*
+
与块服务检查相关的系统事件。

* *bsKillEvent*
+
与块服务终止相关的系统事件。

* *批量操作事件*
+
与对整个卷执行的操作相关的事件，例如备份、还原、快照或克隆。

* *克隆事件*
+
与卷克隆相关的事件。

* *集群主事件*
+
集群初始化时或集群配置更改时（例如添加或删除节点）出现的事件。

* [[csum_event]]*cSumEvent*
+
与端到端校验和验证过程中检测到校验和不匹配相关的事件。

+
检测到校验和不匹配的服务将自动停止，并且在生成此事件后不会重新启动。

* *数据事件*
+
与数据读写相关的事件。

* *dbEvent*
+
与集群中集成节点维护的全局数据库相关的事件。

* *driveEvent*
+
与驱动操作相关的事件。

* *encryptionAtRestEvent*
+
与集群加密过程相关的事件。

* *合奏活动*
+
与集合中节点数量增加或减少相关的事件。

* *光纤通道事件*
+
与节点配置和连接相关的事件。

* *gcEvent*
+
与进程相关的事件每 60 分钟运行一次，以回收块驱动器上的存储空间。这个过程也称为垃圾回收。

* *ieEvent*
+
内部系统错误。

* *安装事件*
+
自动软件安装事件。软件正在自动安装到待处理的节点上。

* *iSCSI事件*
+
与系统中的 iSCSI 问题相关的事件。

* *limitEvent*
+
与账户或集群中的卷或虚拟卷数量接近允许的最大值相关的事件。

* *维护模式事件*
+
与节点维护模式相关的事件，例如禁用节点。

* [[network_event]]*networkEvent*
+
与每个物理网络接口卡 (NIC) 接口的网络错误报告相关的事件。

+
当 10 分钟监控间隔内，任何接口的错误计数超过默认阈值 1000 时，就会触发这些事件。这些事件适用于网络错误，例如接收丢失、循环冗余校验 (CRC) 错误、长度错误、溢出错误和帧错误。

* *平台硬件事件*
+
与硬件设备上检测到的问题相关的事件。

* *远程集群事件*
+
与远程集群配对相关的事件。

* *调度器事件*
+
与计划快照相关的事件。

* *服务事件*
+
与系统服务状态相关的事件。

* *切片事件*
+
与 Slice 服务器相关的事件，例如删除元数据驱动器或卷。

+
切片重新分配事件有三种类型，其中包含有关卷分配到的服务的信息：

+
** 翻转：将主要服务更改为新的主要服务
+
[listing]
----
sliceID oldPrimaryServiceID->newPrimaryServiceID
----
** 迁移：将辅助服务更改为新的辅助服务
+
[listing]
----
sliceID {oldSecondaryServiceID(s)}->{newSecondaryServiceID(s)}
----
** 修剪：从一组服务中移除一个卷
+
[listing]
----
sliceID {oldSecondaryServiceID(s)}
----


* *snmpTrapEvent*
+
与 SNMP 陷阱相关的事件。

* *statEvent*
+
与系统统计相关的事件。

* *tsEvent*
+
与系统传输服务相关的事件。

* *意外异常*
+
与意外系统异常相关的事件。

* *ureEvent*
+
与从存储设备读取数据时发生的不可恢复的读取错误相关的事件。

* *vasaProviderEvent*
+
与 VASA（vSphere APIs for Storage Awareness）提供程序相关的事件。


