---
permalink: storage/reference_monitor_cluster_fault_codes.html 
sidebar: sidebar 
keywords: cluster fault codes, alerts, error codes, view 
summary: 系统通过生成故障代码来报告错误或可能感兴趣的状态，该故障代码列在“警报”页面上。这些代码可以帮助您确定系统的哪个组件收到了警报以及警报生成的原因。 
---
= 集群故障代码
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
系统通过生成故障代码来报告错误或可能感兴趣的状态，该故障代码列在“警报”页面上。这些代码可以帮助您确定系统的哪个组件收到了警报以及警报生成的原因。

以下列表概述了不同类型的代码：

* *authenticationServiceFault*
+
一个或多个集群节点上的身份验证服务未按预期运行。

+
联系 NetApp 支持部门获得帮助。

* *可用虚拟网络IP地址少*
+
IP地址块中的虚拟网络地址数量较少。

+
要解决此故障，请向虚拟网络地址块中添加更多 IP 地址。

* *blockClusterFull*
+
没有足够的可用块存储空间可用于承受单节点丢失。有关集群填充程度的详细信息，请参阅 GetClusterFullThreshold API 方法。此集群故障表明存在以下情况之一：

+
** stage3Low（警告）：已超过用户定义的阈值。调整集群已满设置或添加更多节点。
** stage4Critical（错误）：没有足够的空间从 1 个节点故障中恢复。不允许创建卷、快照和克隆。
** stage5完全消耗（严重）1；不允许写入或建立新的iSCSI连接。现有 iSCSI 连接将保持不变。在集群增加更多容量之前，写入操作将会失败。


+
要解决此故障，请清除或删除卷，或者向存储集群添加另一个存储节点。

* *blocksDegraded*
+
由于故障，数据块不再完全复制。

+
|===


| 严重性 | 描述 


 a| 
警告
 a| 
只有两份完整的数据块副本可供访问。



 a| 
错误
 a| 
只能访问到数据块的完整副本。



 a| 
批判的
 a| 
无法获取完整的数据块副本。

|===
+
*注意：*此警告状态只会在三螺旋系统中出现。

+
要解决此故障，请恢复任何离线节点或阻止服务，或联系NetApp支持寻求帮助。

* *blockServiceTooFull*
+
一个块服务占用了过多的空间。

+
要解决此故障，请增加已配置容量。

* *阻止服务不健康*
+
检测到某个阻塞服务运行状况不佳：

+
** 严重程度 = 警告：不采取任何措施。此警告期将在 cTimeUntilBSIsKilledMSec=330000 毫秒后到期。
** 严重性 = 错误：系统正在自动停用数据并将其数据重新复制到其他正常驱动器。
** 严重性 = 严重：多个节点上的块服务出现故障，故障数量大于或等于复制计数（双螺旋为 2）。数据不可用，箱体同步将无法完成。
+
检查网络连接问题和硬件错误。如果特定硬件组件发生故障，则会出现其他故障。当阻塞服务恢复正常或服务停用后，故障将会清除。



* *BmcSelfTest失败*
+
基板管理控制器（BMC）自检失败。

+
请联系NetApp支持部门寻求帮助。

+
在升级到 Element 12.5 或更高版本期间， `BmcSelfTestFailed`如果节点上的BMC已发生故障，或者节点的BMC在升级过程中发生故障，则不会生成故障。升级过程中自检失败的 BMC 将发出警告 `BmcSelfTestFailed`整个集群升级完成后出现警告故障。

* *时钟偏差超过故障阈值*
+
集群主节点与提供令牌的节点之间的时间偏差超过了建议的阈值。存储集群无法自动纠正节点间的时间偏差。

+
要解决此故障，请使用网络内部的 NTP 服务器，而不是安装默认服务器。如果您使用的是内部 NTP 服务器，请联系NetApp支持部门寻求帮助。

* *集群无法同步*
+
空间不足，离线块存储驱动器上的数据无法同步到仍在活动的驱动器。

+
要解决此故障，请增加存储空间。

* *集群已满*
+
存储集群中已无可用存储空间。

+
要解决此故障，请增加存储空间。

* *集群IOPS配置过高*
+
集群IOPS配置过高。所有最小 QoS IOPS 之和大于集群的预期 IOPS。无法同时为所有卷维持最低服务质量要求。

+
要解决此问题，请降低卷的最小 QoS IOPS 设置。

* *CPU热事件阈值*
+
一个或多个 CPU 上的 CPU 热事件数量超过了设定的阈值。

+
如果在十分钟内未检测到新的 CPU 过热事件，则警告将自动解除。

* *禁用驱动器安全失败*
+
集群未配置为启用驱动器安全（静态加密），但至少有一个驱动器启用了驱动器安全，这意味着禁用这些驱动器上的驱动器安全失败了。该故障被记录为“警告”级别。

+
要解决此故障，请检查故障详细信息，找出无法禁用驱动器安全功能的原因。可能的原因有：

+
** 无法获取加密密钥，请调查密钥访问或外部密钥服务器方面的问题。
** 驱动器上的禁用操作失败，请确定是否可能获取了错误的密钥。


+
如果以上两种情况都不是故障原因，则可能需要更换硬盘。

+
即使提供了正确的身份验证密钥，如果驱动器无法成功禁用安全功能，您也可以尝试恢复该驱动器。要执行此操作，请将驱动器移至“可用”位置，从系统中移除驱动器，对驱动器执行安全擦除，然后将其移回“活动”位置。

* *已断开连接的集群对*
+
集群对已断开连接或配置错误。

+
检查集群之间的网络连接。

* *已断开连接的远程节点*
+
远程节点已断开连接或配置错误。

+
检查节点间的网络连接情况。

* *已断开连接的SnapMirror端点*
+
远程SnapMirror端点已断开连接或配置错误。

+
检查集群与远程 SnapMirrorEndpoint 之间的网络连接。

* *可驾车*
+
集群中有一个或多个驱动器可用。一般来说，所有集群都应该添加所有驱动器，并且没有驱动器处于可用状态。如果此故障意外出现，请联系NetApp支持。

+
要解决此故障，请将所有可用驱动器添加到存储集群。

* *驱动器故障*
+
当一个或多个驱动器发生故障时，集群会返回此故障，表明存在以下情况之一：

+
** 驱动器管理器无法访问该驱动器。
** 切片或块服务失败次数过多，可能是由于驱动器读取或写入失败造成的，无法重新启动。
** 硬盘丢失。
** 节点的主服务无法访问（节点中的所有驱动器均被视为丢失/故障）。
** 硬盘已被锁定，无法获取硬盘的身份验证密钥。
** 驱动器已锁定，解锁操作失败。
+
要解决此问题：

** 检查节点的网络连接情况。
** 更换硬盘。
** 请确保身份验证密钥可用。


* *驱动器健康故障*
+
硬盘未通过 SMART 健康检查，因此，硬盘的功能有所降低。该故障的严重程度等级为“严重”：

+
** 序列号为 <序列号> 的驱动器，位于插槽：<节点插槽><驱动器插槽>，SMART 整体健康检查未通过。


+
要解决此故障，请更换驱动器。

* *驱动磨损故障*
+
硬盘剩余寿命已低于阈值，但仍可正常工作。此故障有两种严重程度级别：严重和警告。

+
** 序列号为<序列号>的驱动器位于插槽：<节点插槽><驱动器插槽>，磨损程度严重。
** 序列号为<序列号>的驱动器位于插槽：<节点插槽><驱动器插槽>，磨损储备较低。
+
要解决此故障，请尽快更换硬盘。



* *重复集群主候选对象*
+
检测到多个存储集群主节点候选者。

+
联系 NetApp 支持部门获得帮助。

* *启用驱动器安全失败*
+
集群配置为需要驱动器安全（静态加密），但至少有一个驱动器无法启用驱动器安全。该故障被记录为“警告”级别。

+
要解决此故障，请检查故障详细信息，找出无法启用驱动器安全功能的原因。可能的原因有：

+
** 无法获取加密密钥，请调查密钥访问或外部密钥服务器方面的问题。
** 驱动器启用操作失败，请确定是否可能获取了错误的密钥。如果以上两种情况都不是故障原因，则可能需要更换硬盘。


+
即使提供了正确的身份验证密钥，如果驱动器无法成功启用安全功能，您也可以尝试恢复该驱动器。要执行此操作，请将驱动器移至“可用”位置，从系统中移除驱动器，对驱动器执行安全擦除，然后将其移回“活动”位置。

* *合奏退化*
+
一个或多个集合节点已断开网络连接或已断电。

+
要解决此故障，请恢复网络连接或电源。

* *例外*
+
报告的故障并非例行故障。这些故障不会自动从故障队列中清除。

+
联系 NetApp 支持部门获得帮助。

* *空间已满*
+
阻塞服务不响应数据写入请求。这会导致切片服务没有足够的空间来存储失败的写入操作。

+
要解决此故障，请恢复块服务功能，以允许写入正常继续，并将故障空间从切片服务中刷新出来。

* *风扇传感器*
+
风扇传感器故障或缺失。

+
要解决此故障，请更换任何故障硬件。

* *光纤通道接入降级*
+
一段时间内，光纤通道节点无法通过其存储 IP 响应存储集群中的其他节点。在这种状态下，节点将被视为无响应，并产生集群故障。

+
检查网络连接。

* *光纤通道接入不可用*
+
所有光纤通道节点均无响应。显示节点 ID。

+
检查网络连接。

* *光纤通道主动式IxL*
+
IxL Nexus 的数量已接近每个光纤通道节点 8000 个活动会话的支持上限。

+
** 最佳实践限制为 5500。
** 警告限值为 7500。
** 最大限制（不强制执行）为 8192。


+
要解决此故障，请将 IxL Nexus 数量减少到 5500 以下的最佳实践限制。

* *光纤通道配置*
+
此集群故障表明存在以下情况之一：

+
** PCI 插槽上意外地出现了一个光纤通道端口。
** 出现了一款意想不到的光纤通道 HBA 型号。
** 光纤通道 HBA 的固件存在问题。
** 光纤通道端口未上线。
** 配置光纤通道直通功能时一直存在问题。


+
联系 NetApp 支持部门获得帮助。

* *光纤通道IOPS*
+
集群中光纤通道节点的总 IOPS 计数已接近 IOPS 限制。限制条件是：

+
** FC0025：每个光纤通道节点在 4K 块大小下 IOPS 限制为 450K。
** FCN001：每个光纤通道节点在 4K 块大小下，OPS 限制为 625K。


+
要解决此故障，请在所有可用的光纤通道节点上平衡负载。

* *fibreChannelStaticIxL*
+
IxL Nexus 的数量已接近每个光纤通道节点支持的静态会话数上限 16000。

+
** 最佳实践限制为 11000。
** 警告限值为 15000。
** 最大限制（强制执行）为 16384。


+
要解决此故障，请将 IxL Nexus 数量减少到 11000 以下的最佳实践限制。

* *fileSystemCapacityLow*
+
其中一个文件系统空间不足。

+
要解决此故障，请增加文件系统的容量。

* *fileSystemIsReadOnly*
+
文件系统已进入只读模式。

+
联系 NetApp 支持部门获得帮助。

* *fips驱动器不匹配*
+
将非 FIPS 驱动器物理插入到支持 FIPS 的存储节点中，或者将 FIPS 驱动器物理插入到非 FIPS 存储节点中。每个节点生成一个故障报告，列出所有受影响的驱动器。

+
要解决此故障，请移除或更换有问题的不匹配的硬盘驱动器。

* *fipsDrivesOutOfCompliance*
+
系统检测到启用 FIPS 驱动器功能后，静态数据加密功能被禁用。当启用 FIPS 驱动器功能并且存储集群中存在非 FIPS 驱动器或节点时，也会产生此故障。

+
要解决此故障，请启用静态数据加密或从存储集群中移除非 FIPS 硬件。

* *fips自检失败*
+
FIPS 子系统在自检过程中检测到故障。

+
联系 NetApp 支持部门获得帮助。

* *硬件配置不匹配*
+
此集群故障表明存在以下情况之一：

+
** 配置与节点定义不匹配。
** 此类型的节点使用了不正确的驱动器容量。
** 检测到不支持的驱动器。一个可能的原因是已安装的 Element 版本无法识别此驱动器。建议更新此节点上的 Element 软件。
** 驱动器固件不匹配。
** 驱动器加密功能状态与节点不匹配。


+
联系 NetApp 支持部门获得帮助。

* *idPCertificateExpiration*
+
集群的服务提供商 SSL 证书（用于第三方身份提供商 (IdP)）即将到期或已经到期。该故障根据紧急程度采用以下严重级别：

+
|===


| 严重性 | 描述 


 a| 
警告
 a| 
证书有效期为30天。



 a| 
错误
 a| 
证书有效期为7天。



 a| 
批判的
 a| 
证书将在3天内过期或已经过期。

|===
+
要解决此故障，请在 SSL 证书过期前更新它。使用 UpdateIdpConfiguration API 方法 `refreshCertificateExpirationTime=true`提供更新后的SSL证书。

* *不一致的键合模式*
+
VLAN 设备上的绑定模式缺失。此故障将显示预期的键合模式和当前使用的键合模式。



* *不一致的Mtus*
+
此集群故障表明存在以下情况之一：

+
** Bond1G 不匹配：在 Bond1G 接口上检测到不一致的 MTU。
** Bond10G 不匹配：在 Bond10G 接口上检测到不一致的 MTU。


+
此故障会显示相关节点以及关联的 MTU 值。

* *路由规则不一致*
+
此接口的路由规则不一致。

* *子网掩码不一致*
+
VLAN 设备上的网络掩码与内部记录的 VLAN 网络掩码不匹配。此故障会显示预期的网络掩码和当前使用的网络掩码。

* *错误的BondPortCount*
+
绑定端口的数量不正确。

* *无效的已配置光纤通道节点计数*
+
两个预期的光纤通道节点连接中，有一个连接性能下降。当仅连接一个光纤通道节点时，就会出现此故障。

+
要解决此故障，请检查集群网络连接和网络布线，并检查是否存在故障服务。如果没有网络或服务问题，请联系NetApp支持部门更换光纤通道节点。

* *irqBalanceFailed*
+
尝试平衡中断时发生异常。

+
联系 NetApp 支持部门获得帮助。

* *kmip证书故障*
+
** 根证书颁发机构（CA）证书即将到期。
+
要解决此故障，请从根 CA 获取一个有效期至少还有 30 天的新证书，并使用 ModifyKeyServerKmip 提供更新后的根 CA 证书。

** 客户端证书即将到期。
+
要解决此故障，请使用 GetClientCertificateSigningRequest 创建一个新的 CSR，对其进行签名，确保新的到期日期至少还有 30 天，然后使用 ModifyKeyServerKmip 将即将到期的 KMIP 客户端证书替换为新证书。

** 根证书颁发机构（CA）证书已过期。
+
要解决此故障，请从根 CA 获取一个有效期至少还有 30 天的新证书，并使用 ModifyKeyServerKmip 提供更新后的根 CA 证书。

** 客户端证书已过期。
+
要解决此故障，请使用 GetClientCertificateSigningRequest 创建一个新的 CSR，对其进行签名，确保新的到期日期至少还有 30 天，然后使用 ModifyKeyServerKmip 将过期的 KMIP 客户端证书替换为新证书。

** 根证书颁发机构（CA）证书错误。
+
要解决此故障，请检查是否提供了正确的证书，如有必要，请从根 CA 重新获取证书。使用 ModifyKeyServerKmip 安装正确的 KMIP 客户端证书。

** 客户端证书错误。
+
要解决此故障，请检查是否已安装正确的 KMIP 客户端证书。客户端证书的根 CA 应该安装在 EKS 上。使用 ModifyKeyServerKmip 安装正确的 KMIP 客户端证书。



* *kmipServerFault*
+
** 连接失败
+
要解决此故障，请检查外部密钥服务器是否正常运行且可通过网络访问。使用 TestKeyServerKimp 和 TestKeyProviderKmip 测试您的连接。

** 身份验证失败
+
要解决此故障，请检查是否使用了正确的根 CA 和 KMIP 客户端证书，以及私钥和 KMIP 客户端证书是否匹配。

** 服务器错误
+
要解决此故障，请检查错误详情。根据返回的错误信息，可能需要对外部密钥服务器进行故障排除。



* *内存Ecc阈值*
+
检测到大量可纠正或不可纠正的ECC错误。该故障根据紧急程度采用以下严重级别：

+
|===


| 事件 | 严重性 | 描述 


 a| 
单个 DIMM cErrorCount 达到 cDimmCorrectableErrWarnThreshold。
 a| 
警告
 a| 
DIMM 内存插槽上超过阈值的可纠正 ECC 内存错误：<处理器> <DIMM 插槽>



 a| 
单个 DIMM 的 cErrorCount 会一直高于 cDimmCorrectableErrWarnThreshold，直到 DIMM 的 cErrorFaultTimer 超时为止。
 a| 
错误
 a| 
DIMM 内存条上超过阈值的可纠正 ECC 内存错误：<处理器> <DIMM>



 a| 
内存控制器报告 cErrorCount 高于 cMemCtlrCorrectableErrWarnThreshold，并且指定了 cMemCtlrCorrectableErrWarnDuration。
 a| 
警告
 a| 
内存控制器上超过阈值的可纠正ECC内存错误：<处理器> <内存控制器>



 a| 
内存控制器报告的 cErrorCount 超过 cMemCtlrCorrectableErrWarnThreshold，直到内存控制器的 cErrorFaultTimer 超时为止。
 a| 
错误
 a| 
DIMM 内存条上超过阈值的可纠正 ECC 内存错误：<处理器> <DIMM>



 a| 
单个 DIMM 报告的 uErrorCount 大于零，但小于 cDimmUncorrectableErrFaultThreshold。
 a| 
警告
 a| 
DIMM 内存条上检测到不可纠正的 ECC 内存错误：<处理器> <DIMM 插槽>



 a| 
单个 DIMM 报告的 uErrorCount 至少为 cDimmUncorrectableErrFaultThreshold。
 a| 
错误
 a| 
DIMM 内存条上检测到不可纠正的 ECC 内存错误：<处理器> <DIMM 插槽>



 a| 
内存控制器报告的 uErrorCount 大于零，但小于 cMemCtlrUncorrectableErrFaultThreshold。
 a| 
警告
 a| 
内存控制器上检测到不可纠正的 ECC 内存错误：<处理器> <内存控制器>



 a| 
内存控制器报告的 uErrorCount 至少为 cMemCtlrUncorrectableErrFaultThreshold。
 a| 
错误
 a| 
内存控制器上检测到不可纠正的 ECC 内存错误：<处理器> <内存控制器>

|===
+
要解决此故障，请联系NetApp支持部门寻求帮助。

* *内存使用阈值*
+
内存使用量高于正常水平。该故障根据紧急程度采用以下严重级别：

+

NOTE: 有关故障类型的更多详细信息，请参阅错误故障中的“详细信息”标题。

+
|===


| 严重性 | 描述 


 a| 
警告
 a| 
系统内存不足。



 a| 
错误
 a| 
系统内存严重不足。



 a| 
批判的
 a| 
系统内存已完全耗尽。

|===
+
要解决此故障，请联系NetApp支持部门寻求帮助。

* *metadataClusterFull*
+
可用的元数据存储空间不足以应对单个节点的丢失。有关集群填充程度的详细信息，请参阅 GetClusterFullThreshold API 方法。此集群故障表明存在以下情况之一：

+
** stage3Low（警告）：已超过用户定义的阈值。调整集群已满设置或添加更多节点。
** stage4Critical（错误）：没有足够的空间从 1 个节点故障中恢复。不允许创建卷、快照和克隆。
** stage5完全消耗（严重）1；不允许写入或建立新的iSCSI连接。现有 iSCSI 连接将保持不变。在集群增加更多容量之前，写入操作将会失败。清除或删除数据，或添加更多节点。


+
要解决此故障，请清除或删除卷，或者向存储集群添加另一个存储节点。

* *mtuCheckFailure*
+
网络设备的 MTU 大小配置不正确。

+
要解决此故障，请确保所有网络接口和交换机端口都配置为巨型帧（MTU 最大可达 9000 字节）。

* *网络配置*
+
此集群故障表明存在以下情况之一：

+
** 未找到预期的接口。
** 存在重复接口。
** 已配置的接口已关闭。
** 需要重启网络。


+
联系 NetApp 支持部门获得帮助。

* *无可用虚拟网络IP地址*
+
该IP地址块中没有可用的虚拟网络地址。

+
** virtualNetworkID # TAG(\###) 没有可用的存储 IP 地址。无法向集群添加其他节点。


+
要解决此故障，请向虚拟网络地址块中添加更多 IP 地址。

* *nodeHardwareFault（网络接口<名称>已关闭或网线已拔出）*
+
网络接口出现故障或网线被拔出。

+
要解决此故障，请检查节点或多个节点的网络连接。

* *nodeHardwareFault（驱动器加密功能状态与节点中插槽 <节点插槽><驱动器插槽> 内的驱动器的加密功能状态不匹配）*
+
硬盘的加密功能与其安装的存储节点不匹配。

* *nodeHardwareFault（此节点类型的<驱动器类型>驱动器容量<实际容量>不正确 - 预期容量>）*
+
存储节点中包含一个容量与该节点不匹配的驱动器。

* *nodeHardwareFault（在插槽<节点插槽><驱动器插槽>中检测到不支持的驱动器；驱动器统计信息和健康信息将不可用）*
+
存储节点中包含它不支持的驱动器。

* *nodeHardwareFault（插槽 <node slot><drive slot> 中的驱动器应使用固件版本 <expected version>，但当前使用的是不支持的版本 <actual version>）*
+
存储节点中包含一个运行不受支持的固件版本的驱动器。

* *节点维护模式*
+
一个节点已置于维护模式。该故障根据紧急程度采用以下严重级别：

+
|===


| 严重性 | 描述 


 a| 
警告
 a| 
表示该节点仍处于维护模式。



 a| 
错误
 a| 
表示维护模式未能禁用，很可能是由于备用电源故障或处于活动状态所致。

|===
+
要解决此故障，请在维护完成后禁用维护模式。如果错误级别故障仍然存在，请联系NetApp支持部门寻求帮助。

* *nodeOffline*
+
Element软件无法与指定节点通信。检查网络连接。

* *未使用LACP债券模式*
+
LACP 绑定模式未配置。

+
要解决此故障，请在部署存储节点时使用 LACP 绑定；如果未启用或正确配置 LACP，客户端可能会遇到性能问题。

* *ntp服务器不可达*
+
存储集群无法与指定的 NTP 服务器通信。

+
要解决此故障，请检查 NTP 服务器、网络和防火墙的配置。

* *ntpTimeNotInSync*
+
存储集群时间与指定的 NTP 服务器时间相差过大。存储集群无法自动纠正这种差异。

+
要解决此故障，请使用网络内部的 NTP 服务器，而不是安装默认服务器。如果您使用的是内部 NTP 服务器且问题仍然存在，请联系NetApp支持部门寻求帮助。

* *nvramDeviceStatus*
+
NVRAM设备出现错误、正在发生故障或已经发生故障。该故障的严重程度如下：

+
|===


| 严重性 | 描述 


 a| 
警告
 a| 
硬件检测到警告。这种情况可能是暂时的，例如温度警告。

** nvmLifetimeError
** nvmLifetimeStatus
** 能源来源生命周期状态
** 能源来源温度状态
** 警告阈值已超出




 a| 
错误
 a| 
硬件检测到错误或严重状态。集群主控尝试将切片驱动器从运行中移除（这将生成一个驱动器移除事件）。如果辅助分区服务不可用，则不会移除驱动器。除了警告级别的错误之外，还返回了以下错误：

** NVRAM设备挂载点不存在。
** NVRAM设备分区不存在。
** NVRAM设备分区存在，但未挂载。




 a| 
批判的
 a| 
硬件检测到错误或严重状态。集群主控尝试将切片驱动器从运行中移除（这将生成一个驱动器移除事件）。如果辅助分区服务不可用，则不会移除驱动器。

** 持久性丢失
** armStatusSaveNArmed
** csaveStatusError


|===
+
更换节点中任何故障的硬件。如果此方法无法解决问题，请联系NetApp支持部门寻求帮助。

* *电源错误*
+
此集群故障表明存在以下情况之一：

+
** 电源缺失。
** 电源故障。
** 电源输入缺失或超出范围。


+
要解决此故障，请确认所有节点均已提供冗余电源。联系 NetApp 支持部门获得帮助。

* *预留空间已满*
+
集群的整体配置容量已满。

+
要解决此故障，请添加更多已配置空间，或删除并清除卷。

* *远程复制异步延迟超过限制*
+
配置的异步复制延迟已超过设定值。检查集群间的网络连接。

* *远程副本集群已满*
+
由于目标存储集群已满，卷已暂停远程复制。

+
要解决此故障，请释放目标存储集群上的一些空间。

* *remoteRepSnapshotClusterFull*
+
由于目标存储集群已满，卷已暂停快照的远程复制。

+
要解决此故障，请释放目标存储集群上的一些空间。

* *远程副本快照超出限制*
+
由于目标存储集群卷已超出其快照限制，因此卷已暂停远程快照复制。

+
要解决此故障，请增加目标存储集群上的快照限制。

* *scheduleActionError*
+
一项或多项预定活动已运行，但失败了。

+
如果计划的活动再次运行并成功，或者计划的活动被删除，或者活动被暂停并恢复，则故障将被清除。

* *传感器读取失败*
+
传感器无法与基板管理控制器（BMC）通信。

+
联系 NetApp 支持部门获得帮助。

* *服务未运行*
+
所需服务未运行。

+
联系 NetApp 支持部门获得帮助。

* *sliceServiceTooFull*
+
切片服务的预置容量过少。

+
要解决此故障，请增加已配置容量。

* *sliceServiceUnhealthy*
+
系统检测到某个切片服务运行状况不佳，正在自动将其停用。

+
** 严重程度 = 警告：不采取任何措施。此警告期将在 6 分钟后结束。
** 严重性 = 错误：系统正在自动停用数据并将其数据重新复制到其他正常驱动器。


+
检查网络连接问题和硬件错误。如果特定硬件组件发生故障，则会出现其他故障。当切片服务可访问或服务已停用时，故障将清除。

* *已启用 SSH*
+
SSH 服务已在存储集群中的一个或多个节点上启用。

+
要解决此故障，请禁用相应节点上的 SSH 服务，或联系NetApp支持寻求帮助。

* *ssl证书过期时间*
+
与此节点关联的 SSL 证书即将过期或已过期。该故障根据紧急程度采用以下严重级别：

+
|===


| 严重性 | 描述 


 a| 
警告
 a| 
证书有效期为30天。



 a| 
错误
 a| 
证书有效期为7天。



 a| 
批判的
 a| 
证书将在3天内过期或已经过期。

|===
+
要解决此故障，请更新 SSL 证书。如有需要，请联系NetApp支持部门寻求帮助。

* *搁浅容量*
+
单个节点占用了存储集群一半以上的容量。

+
为了保持数据冗余，系统会降低最大节点的容量，使其部分数据块容量闲置（未使用）。

+
要解决此故障，请向现有存储节点添加更多驱动器或向集群添加存储节点。

* *温度传感器*
+
温度传感器显示温度高于正常值。此故障可能与电源错误或风扇传感器故障同时触发。

+
要解决此故障，请检查存储集群附近是否存在气流阻塞。如有需要，请联系NetApp支持部门寻求帮助。

* *升级*
+
升级工作已持续超过24小时。

+
要解决此故障，请恢复升级或联系NetApp支持寻求帮助。

* *无响应服务*
+
服务已停止响应。

+
联系 NetApp 支持部门获得帮助。

* *虚拟网络配置*
+
此集群故障表明存在以下情况之一：

+
** 接口不存在。
** 接口中存在错误的命名空间。
** 子网掩码不正确。
** IP地址错误。
** 接口未启动并运行。
** 节点上存在多余的接口。


+
联系 NetApp 支持部门获得帮助。

* *音量降低*
+
辅助卷尚未完成复制和同步。同步完成后，该消息将被清除。

* *卷离线*
+
存储集群中的一个或多个卷处于脱机状态。同时还会出现 *volumeDegraded* 故障。

+
联系 NetApp 支持部门获得帮助。


