---
permalink: storage/task_per_node_run_system_tests.html 
sidebar: sidebar 
keywords: storage nodes, running system tests,s ystem tests, network settings, testing changes 
summary: 将网络设置更改提交到网络配置后，即可对其进行测试。您可以运行测试以确保存储节点稳定，并且可以毫无问题地上线。 
---
= 使用节点级用户界面运行系统测试。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
将网络设置更改提交到网络配置后，即可对其进行测试。您可以运行测试以确保存储节点稳定，并且可以毫无问题地上线。

您已登录到存储节点的单节点用户界面。

. 点击“系统测试”。
. 单击要运行的测试旁边的“运行测试”或选择“运行所有测试”。
+

NOTE: 运行所有测试操作可能很耗时，并且只能在NetApp支持人员的指导下进行。

+
** *测试连接集成*
+
测试并验证与数据库集合的连接性。默认情况下，测试使用节点所属集群的集成模型。或者，您可以提供不同的组件来测试连接性。

** *测试连接Mvip*
+
ping 指定的管理虚拟 IP (MVIP) 地址，然后向 MVIP 执行简单的 API 调用以验证连接性。默认情况下，测试使用节点所属集群的 MVIP。

** *测试连接Svip*
+
使用与网络适配器上设置的最大传输单元 (MTU) 大小相匹配的 Internet 控制消息协议 (ICMP) 数据包来 ping 指定的存储虚拟 IP (SVIP) 地址。然后它作为 iSCSI 发起程序连接到 SVIP。默认情况下，测试使用节点所属集群的 SVIP。

** *测试硬件配置*
+
测试所有硬件配置是否正确，验证固件版本是否正确，并确认所有驱动器均已安装并正常运行。这与工厂测试相同。

+

NOTE: 此测试会占用大量资源，仅应在NetApp支持部门要求时运行。

** *测试本地连接*
+
通过 ping 集群 IP (CIP) 来测试与集群中所有其他节点的连接性。只有当节点属于活动集群时，此测试才会显示在该节点上。

** *测试定位集群*
+
验证节点是否可以找到集群配置中指定的集群。

** *测试网络配置*
+
验证配置的网络设置与系统上使用的网络设置是否匹配。本测试并非旨在检测节点在集群中积极参与运行时发生的硬件故障。

** *测试 Ping*
+
对指定的主机列表进行 ping 操作；如果没有指定主机，则动态构建集群中所有已注册节点的列表，并对每个节点进行 ping 操作以实现简单的连接。

** *测试远程连接*
+
通过 ping 集群 IP (CIP) 来测试与远程配对集群中所有节点的连接性。只有当节点属于活动集群时，此测试才会显示在该节点上。




