---
permalink: storage/task_post_deploy_credential_change_ipmi_password.html 
sidebar: sidebar 
keywords: ipmi, password, intelligent platform management interface, netapp, element, h410s, h610s 
summary: '只要您拥有对节点的远程 IPMI 访问权限，即可更改默认的智能平台管理接口 (IPMI) 管理员密码。如果安装有任何更新，您可能需要执行此操作。' 
---
= 更改节点的默认 IPMI 密码
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
只要您拥有对节点的远程 IPMI 访问权限，即可更改默认的智能平台管理接口 (IPMI) 管理员密码。如果安装有任何更新，您可能需要执行此操作。

有关配置节点 IPM 访问权限的详细信息，请参阅link:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_final_prep.html["为每个节点配置 IPMI"^]。

您可以更改以下节点的 IPM 密码：

* H410S节点
* H610S节点




== 更改 H410S 节点的默认 IPMI 密码

配置 IPMI 网络端口后，应立即更改每个存储节点上 IPMI 管理员帐户的默认密码。

.你需要什么
您应该为每个存储节点配置 IPMI IP 地址。

.步骤
. 在能够访问 IPMI 网络的计算机上打开网页浏览器，并浏览到节点的 IPMI IP 地址。
. 请输入用户名 `ADMIN`和密码 `ADMIN`在登录提示符中。
. 登录后，点击“配置”选项卡。
. 点击“用户”。
. 选择 `ADMIN`用户并点击*修改用户*。
. 选中“更改密码”复选框。
. 请在“密码”和“确认密码”字段中输入新密码。
. 点击“修改”，然后点击“确定”。
. 对其他所有使用默认 IPMI 密码的 H410S 节点重复此过程。




== 更改 H610S 节点的默认 IPMI 密码

配置 IPMI 网络端口后，应立即更改每个存储节点上 IPMI 管理员帐户的默认密码。

.你需要什么
您应该为每个存储节点配置 IPMI IP 地址。

.步骤
. 在能够访问 IPMI 网络的计算机上打开网页浏览器，并浏览到节点的 IPMI IP 地址。
. 请输入用户名 `root`和密码 `calvin`在登录提示符中。
. 登录后，点击页面左上角的菜单导航图标，打开侧边栏抽屉。
. 点击“设置”。
. 点击“用户管理”。
. 从列表中选择*管理员*用户。
. 启用“更改密码”复选框。
. 请在“密码”和“确认密码”字段中输入新的、强密码。
. 点击页面底部的“保存”。
. 对其他所有使用默认 IPMI 密码的 H610S 节点重复此过程。




== 查找更多信息

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire和 Element 软件文档"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element vCenter Server 插件"^]

