---
permalink: storage/task_system_manage_nodes_adding_a_node_to_a_cluster.html 
sidebar: sidebar 
keywords: nodes, add, config, cluster, pending, pairs, capacity, rule 
summary: 当需要更多存储空间时，或者在创建集群之后，您可以向集群添加节点。节点首次上电时需要进行初始配置。节点配置完成后，它将出现在待处理节点列表中，您可以将其添加到集群中。 
---
= 向集群添加节点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当需要更多存储空间时，或者在创建集群之后，您可以向集群添加节点。节点首次上电时需要进行初始配置。节点配置完成后，它将出现在待处理节点列表中，您可以将其添加到集群中。

集群中每个节点上的软件版本必须兼容。向集群添加节点时，集群会根据需要在新节点上安装集群版本的NetApp Element软件。

您可以向现有集群添加容量较小或较大的节点。您可以向集群添加更大容量的节点，以满足容量增长的需求。向包含较小节点的集群中添加较大节点时，必须成对添加。这样就为 Double Helix 留出了足够的空间，以便在较大的节点之一发生故障时能够转移数据。您可以向较大的节点集群中添加较小的节点容量，以提高性能。


NOTE: 如果新添加的节点占集群总容量的 50% 以上，则该节点的部分容量将被禁用（“闲置”），以使其符合容量规则。在增加更多存储空间之前，这种情况将一直持续下去。如果添加一个非常大的节点，并且该节点也违反容量规则，则先前被困的节点将不再被困，而新添加的节点将变为被困。为避免这种情况发生，容量应该始终成对添加。当节点发生故障时，会抛出 strandedCapacity 集群故障。

https://www.youtube.com/embed/2smVHWkikXY?rel=0["NetApp视频：按需扩展：扩展SolidFire集群"^]

您可以向NetApp HCI设备添加节点。

.步骤
. 选择“集群”>“节点”。
. 点击“待处理”查看待处理节点列表。
+
添加节点的过程完成后，它们将出现在“活动节点”列表中。在此之前，待处理节点会出现在待处理活动列表中。

+
当您将节点添加到集群时， SolidFire会在待添加节点上安装集群的 Element 软件版本。这可能需要几分钟。

. 执行以下操作之一：
+
** 要添加单个节点，请单击要添加的节点旁边的“操作”图标。
** 要添加多个节点，请选中要添加的节点的复选框，然后选择“批量操作”。 *注意：*如果您添加的节点的 Element 软件版本与集群上运行的版本不同，则集群会异步地将该节点更新为集群主节点上运行的 Element 软件版本。节点更新后，会自动添加到集群中。在此异步过程中，节点将处于 pendingActive 状态。


. 单击“*添加*”。
+
该节点出现在活动节点列表中。





== 查找更多信息

xref:concept_system_manage_nodes_node_versioning_and_compatibility.adoc[Node 版本控制和兼容性]
