---
permalink: storage/task-element-replication-define-rule-policy.html 
sidebar: sidebar 
keywords: ontap, cli, define, rule, policy 
summary: 对于“mirror-vault”策略类型的自定义策略，您必须至少定义一条规则来确定在初始化和更新期间传输哪些快照副本。您还可以为“mirror-vault”策略类型定义默认策略规则。 
---
= 为策略定义规则
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
对于“`mirror-vault`”策略类型的自定义策略，您必须至少定义一条规则来确定在初始化和更新期间传输哪些快照副本。您还可以使用“`mirror-vault`”策略类型定义默认策略的规则。

.关于此任务
所有具有“`mirror-vault`”策略类型的策略都必须有一条规则，指定要复制哪些快照副本。例如，“`bi-monthly`”规则表示只有分配了SnapMirror标签“`bi-monthly`”的快照副本才应该被复制。配置元素快照副本时，您可以分配SnapMirror标签。

每种策略类型都与一条或多条系统定义的规则相关联。当您指定策略类型时，这些规则会自动分配给该策略。下表显示了系统定义的规则。

|===


| 系统定义的规则 | 用于政策类型 | 结果 


 a| 
sm_created
 a| 
异步镜像，镜像库
 a| 
SnapMirror创建的快照副本会在初始化和更新时传输。



 a| 
每日
 a| 
mirror-vault
 a| 
初始化和更新时，源上带有SnapMirror标签“`daily`”的新快照副本将被传输。



 a| 
weekly
 a| 
mirror-vault
 a| 
初始化和更新时，源上带有SnapMirror标签“`weekly`”的新快照副本将被传输。



 a| 
月度
 a| 
mirror-vault
 a| 
初始化和更新时，源上带有SnapMirror标签“`monthly`` 的新快照副本将被传输。

|===
您可以根据需要为默认策略或自定义策略指定其他规则。例如：

* 默认情况下 `MirrorAndVault`策略方面，您可以创建一个名为“`bi-monthly`”的规则，将源上的快照副本与带有“`bi-monthly`” SnapMirror标签的副本进行匹配。
* 对于具有“`mirror-vault`”策略类型的自定义策略，您可以创建一个名为“`bi-weekly`”的规则，以匹配源上带有“`bi-weekly`” SnapMirror标签的快照副本。


.步骤
. 为策略定义规则：
+
`snapmirror policy add-rule -vserver _SVM_ -policy _policy_for_rule_ -snapmirror-label _snapmirror-label_ -keep _retention_count_`

+
有关完整的命令语法，请参见手册页。

+
以下示例添加了一条带有SnapMirror标签的规则 `bi-monthly`恢复默认设置 `MirrorAndVault`政策：

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy MirrorAndVault -snapmirror-label bi-monthly -keep 6
----
+
以下示例添加了一条带有SnapMirror标签的规则 `bi-weekly`按照习俗 `my_snapvault`政策：

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy my_snapvault -snapmirror-label bi-weekly -keep 26
----
+
以下示例添加了一条带有SnapMirror标签的规则 `app_consistent`按照习俗 `Sync`政策：

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy Sync -snapmirror-label app_consistent -keep 1
----
+
然后，您可以从源集群复制与此SnapMirror标签匹配的快照副本：

+
[listing]
----
cluster_src::> snapshot create -vserver vs1 -volume vol1 -snapshot snapshot1 -snapmirror-label app_consistent
----

