---
permalink: storage/task_snapmirror_performing_failback_when_source_volume_no_longer_exists.html 
sidebar: sidebar 
keywords: element, ui, failback, perform, source, volume, snapmirror, dr, disaster, recovery 
summary: 您可以使用NetApp Element UI 重新同步原始源卷并进行故障恢复。本节适用于原始源卷丢失但原始集群仍然完好无损的情况。有关如何恢复到新集群的说明，请参阅NetApp支持网站上的文档。 
---
= 当源卷不存在时，执行故障恢复。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用NetApp Element UI 重新同步原始源卷并进行故障恢复。本节适用于原始源卷丢失但原始集群仍然完好无损的情况。有关如何恢复到新集群的说明，请参阅NetApp支持网站上的文档。

.你需要什么
* Element 卷和ONTAP卷之间的复制关系已断开。
* 《元素》卷已彻底丢失。
* 原始卷名显示为“未找到”。


.步骤
. 在 Element UI 中，找到您为了执行故障转移而断开的关系。
+
*最佳实践：* 记下SnapMirror政策和原始破裂关系的日程安排详情。重建关系时需要这些信息。

. 点击“操作”图标，然后点击“反向重新同步”。
. 确认此操作。
+

NOTE: 反向重新同步操作会创建一个新的关系，其中原始源卷和目标卷的角色互换（这将导致两个关系，因为原始关系仍然存在）。由于原始卷已不存在，系统将创建一个新的 Element 卷，其卷名称和卷大小与原始源卷相同。新卷被分配了名为 sm-recovery 的默认 QoS 策略，并与名为 sm-recovery 的默认帐户关联。您需要手动编辑SnapMirror创建的所有卷的帐户和 QoS 策略，以替换已销毁的原始源卷。

+
作为反向重新同步操作的一部分，最新快照中的数据传输到新卷。您可以继续访问目标端的活动卷并向其写入数据，但您需要断开所有主机与活动卷的连接，并在稍后的步骤中恢复原始主关系之前执行SnapMirror更新。完成反向同步后，请确保目标端卷上没有活动会话连接，并且最新数据位于原始主卷上，然后继续执行以下步骤以完成故障恢复并重新激活原始主卷：

. 单击在反向同步操作期间创建的反向关系的“操作”图标，然后单击“断开”。
. 单击原始关系的“操作”图标（其中源卷不存在），然后单击“删除”。
. 点击您在步骤 4 中断开的反向关系的 *操作* 图标，然后点击 *反向重新同步*。
. 这将源和目标互换，从而得到与原始关系具有相同卷源和卷目标的关系。
. 点击“操作”图标，然后点击“编辑”，即可使用您记下的原始 QoS 策略和计划设置更新此关系。
. 现在可以安全地删除您在步骤 6 中反向同步的反向关系了。




== 查找更多信息

xref:concept_snapmirror_failback_scenarios.adoc[SnapMirror故障恢复场景]
