---
permalink: storage/task_per_node_run_system_utilities.html 
sidebar: sidebar 
keywords: storage nodes, running system utilities, system utilities, network settings, testing changes, reboot the node, power cycle, shuts down the node 
summary: 您可以使用存储节点的单节点 UI 来创建或删除支持包、重置驱动器的配置设置以及重新启动网络或集群服务。 
---
= 使用节点级用户界面运行系统实用程序
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用存储节点的单节点 UI 来创建或删除支持包、重置驱动器的配置设置以及重新启动网络或集群服务。

您已登录到存储节点的单节点用户界面。

. 点击“系统实用工具”。
. 单击要运行的系统实用程序对应的按钮。
+
** *控制功率*
+
重启、断电或关闭节点。

+

IMPORTANT: 此操作会导致网络连接暂时中断。

+
请指定以下参数：

+
*** 操作：选项包括重启和停止（关机）。
*** 唤醒延迟：节点重新上线前的任何额外时间。


** *收集节点日志*
+
在节点的 /tmp/bundles 目录下创建一个支持包。

+
请指定以下参数：

+
*** 捆绑包名称：每个创建的支持捆绑包的唯一名称。如果没有提供名称，则使用“supportbundle”和节点名称作为文件名。
*** 额外参数：此参数将传递给 sf_make_support_bundle 脚本。此参数仅应在NetApp支持部门要求时使用。
*** 超时秒数：指定等待每个 ping 响应的秒数。


** *删除节点日志*
+
删除节点上所有使用 *创建集群支持包* 或 CreateSupportBundle API 方法创建的当前支持包。

** *重置驱动器*
+
初始化驱动器并删除驱动器上当前存储的所有数据。您可以将该驱动器重新用于现有节点或升级后的节点。

+
请指定以下参数：

+
*** 驱动器：要重置的设备名称列表（不是驱动器 ID）。


** *重置网络配置*
+
帮助解决单个节点的网络配置问题，并将单个节点的网络配置重置为出厂默认设置。

** *重置节点*
+
将节点重置为出厂设置。在此操作过程中，所有数据将被删除，但节点的网络设置将被保留。只有当节点未分配给集群且处于可用状态时，才能重置节点。

+

IMPORTANT: 使用此选项时，节点上的所有数据、软件包（软件升级）、配置和日志文件都将被删除。

** *重启网络连接*
+
重启节点上的所有网络服务。

+

IMPORTANT: 此操作可能会导致网络连接暂时中断。

** *重启服务*
+
重启节点上的 Element 软件服务。

+

IMPORTANT: 此操作可能会导致节点服务暂时中断。此操作应仅在NetApp支持人员的指导下执行。

+
请指定以下参数：

+
*** 服务：要重启的服务名称。
*** 操作：要对服务执行的操作。选项包括启动、停止和重启。





