---
permalink: storage/task_data_manage_accounts_work_with_accounts_task.html 
sidebar: sidebar 
keywords: element, solidfire, accounts, create, delete, change, chap, view, edit 
summary: 在SolidFire存储系统中，租户可以使用帐户使客户端能够连接到节点上的卷。帐户包含访问分配给它的卷所需的 CHAP 身份验证。创建卷时，会将其分配给特定帐户。 
---
= 使用 CHAP 处理账户
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在SolidFire存储系统中，租户可以使用帐户使客户端能够连接到集群上的卷。帐户包含访问分配给它的卷所需的质询握手身份验证协议 (CHAP) 身份验证。创建卷时，会将其分配给特定帐户。

一个账户最多可以分配两千卷，但一卷只能属于一个账户。



== CHAP算法

从 Element 12.7 开始，支持符合 FIPS 标准的 CHAP 安全算法 SHA1、SHA-256 和 SHA3-256。当主机 iSCSI 发起程序与 Element iSCSI 目标创建 iSCSI 会话时，它会请求要使用的 CHAP 算法列表。 Element iSCSI 目标从主机 iSCSI 发起程序请求的列表中选择它支持的第一个算法。要确认 Element iSCSI 目标选择最安全的算法，必须配置主机 iSCSI 发起程序发送算法列表，该列表按安全性从高到低排序，例如 SHA3-256 或 SHA1 或 MD5。当主机 iSCSI 发起程序未请求 SHA 算法时，Element iSCSI 目标选择 MD5，假设主机提出的算法列表中包含 MD5。您可能需要更新主机 iSCSI 发起程序配置，以启用对安全算法的支持。

在 Element 12.7 或更高版本升级期间，如果您已将主机 iSCSI 发起程序配置更新为发送包含 SHA 算法列表的会话请求，则在存储节点重启时，新的安全算法将被激活，并且新的或重新连接的 iSCSI 会话将使用最安全的协议建立。升级过程中，所有现有的 iSCSI 会话都将从 MD5 转换为 SHA。如果您不更新主机 iSCSI 发起程序配置以请求 SHA，则现有的 iSCSI 会话将继续使用 MD5。稍后，在您更新主机 iSCSI 发起程序 CHAP 算法之后，iSCSI 会话应根据导致 iSCSI 会话重新连接的维护活动，逐渐从 MD5 过渡到 SHA。

例如，Red Hat Enterprise Linux (RHEL) 8.3 中的默认主机 iSCSI 发起程序具有以下特性： `node.session.auth.chap_algs = SHA3-256,SHA256,SHA1,MD5`该设置被注释掉，导致 iSCSI 发起程序仅使用 MD5。取消主机上此设置的注释并重新启动 iSCSI 发起程序，即可触发该主机上的 iSCSI 会话开始使用 SHA3-256。

如果需要，您可以使用 https://docs.netapp.com/us-en/element-software/api/reference_element_api_listiscsisessions.html["列出 ISCSI 会话"]API 方法，用于查看每个会话所使用的 CHAP 算法。



== 创建帐户

您可以创建帐户以允许访问卷。

系统中的每个账户名称都必须是唯一的。

. 选择“管理”>“帐户”。
. 点击“创建账户”。
. 请输入*用户名*。
. 在“CHAP 设置”部分，输入以下信息：
+

NOTE: 将凭据字段留空，即可自动生成任一密码。

+
** CHAP节点会话认证的*发起方密钥*。
** CHAP节点会话认证的目标密钥。


. 点击“创建账户”。




== 查看账户详情

您可以以图形格式查看各个账户的业绩活动。

图表信息提供帐户的 I/O 和吞吐量信息。平均活动水平和峰值活动水平以 10 秒的报告周期为增量显示。这些统计数据包括分配给该帐户的所有交易量的活动。

. 选择“管理”>“帐户”。
. 点击帐户的“操作”图标。
. 单击“查看详细信息”。


以下是一些细节：

* *状态*：账户的状态。可能值：
+
** 活跃账户：一个活跃的账户。
** 已锁定：一个已锁定的帐户。
** 已删除：已被删除并清除的帐户。


* *活动卷数*：分配给帐户的活动卷数。
* *压缩率*：分配给该帐户的卷的压缩效率得分。
* *重复数据删除*：分配给该帐户的卷的重复数据删除效率得分。
* *精简配置*：分配给帐户的卷的精简配置效率评分。
* *整体效率*：分配给该账户的业务量的整体效率得分。




== 编辑帐户

您可以编辑帐户以更改状态、更改 CHAP 密钥或修改帐户名称。

修改帐户中的 CHAP 设置或从访问组中删除发起程序或卷可能会导致发起程序意外失去对卷的访问权限。为验证卷访问不会意外丢失，请务必注销受帐户或访问组更改影响的 iSCSI 会话，并在完成对启动器设置和集群设置的任何更改后，验证启动器是否可以重新连接到卷。


IMPORTANT: 与管理服务关联的持久卷会被分配给在安装或升级期间创建的新帐户。如果您使用的是持久卷，请勿修改或删除其关联的帐户。

. 选择“管理”>“帐户”。
. 点击帐户的“操作”图标。
. 在出现的菜单中，选择“编辑”。
. *可选：* 编辑 *用户名*。
. *可选：*单击“状态”下拉列表，然后选择其他状态。
+

IMPORTANT: 将状态更改为 *已锁定* 将终止与该帐户的所有 iSCSI 连接，并且该帐户将无法再访问。与该帐户关联的卷已维护；但是，这些卷无法通过 iSCSI 发现。

. *可选：*在 *CHAP 设置* 下，编辑用于节点会话身份验证的 *发起方密钥* 和 *目标密钥* 凭据。
+

NOTE: 如果您不更改 *CHAP 设置* 凭据，则它们将保持不变。如果将凭据字段留空，系统将生成新密码。

. 点击“保存更改”。




== 删除帐户

不再需要账户时，您可以将其删除。

在删除帐户之前，请删除并清除与该帐户关联的所有卷。


IMPORTANT: 与管理服务关联的持久卷会被分配给在安装或升级期间创建的新帐户。如果您使用的是持久卷，请勿修改或删除其关联的帐户。

. 选择“管理”>“帐户”。
. 点击要删除的帐户旁边的“操作”图标。
. 在出现的菜单中，选择“删除”。
. 确认此操作。




== 查找更多信息

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire和 Element 软件文档"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element vCenter Server 插件"^]

