---
permalink: storage/task_data_protection_configure_custom_protection_domains.html 
sidebar: sidebar 
keywords:  
summary: 您可以配置自定义保护域来提高集群的弹性。 
---
= 配置自定义保护域
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
对于包含两个以上存储节点的 Element 集群，您可以为每个节点配置自定义保护域。配置自定义保护域时，必须将集群中的所有节点分配给一个域。


TIP: 分配保护域时，节点间会开始数据同步，在数据同步完成之前，某些集群操作将不可用。为集群配置自定义保护域后，添加新的存储节点时，必须先为该节点分配保护域并允许数据同步完成，才能为新节点添加驱动器。参观link:../concepts/concept_solidfire_concepts_data_protection.html#protection-domains["保护域文档"]了解更多关于保护域的信息。


NOTE: 要使自定义保护域方案对集群有用，每个机箱内的所有存储节点都必须分配到同一个自定义保护域。要实现这一点，您需要创建足够多的自定义保护域（最小的自定义保护域方案是三个域）。最佳实践是，为每个域配置相同数量的节点，并尽量确保分配给特定域的每个节点都是同一类型。

.步骤
. 点击“集群”>“节点”。
. 点击“配置保护域”。
+
在“配置自定义保护域”窗口中，您可以查看当前已配置的保护域（如果有）以及各个节点的保护域分配。

. 输入新自定义保护域的名称，然后单击“创建”。
+
对您需要创建的所有新保护域重复此步骤。

. 对于“分配节点”列表中的每个节点，单击“保护域”列中的下拉列表，然后选择要分配给该节点的保护域。
+

CAUTION: 在应用更改之前，请确保您了解您的节点和机箱布局、您配置的自定义保护域方案以及该方案对数据保护的影响。如果您应用了保护域方案，并且需要立即进行更改，则可能需要一段时间才能进行更改，因为应用配置后会发生数据同步。

. 点击“配置保护域”。


.结果
根据集群规模的大小，域之间的数据同步可能需要一些时间。数据同步完成后，您可以在“集群”>“节点”页面上查看自定义保护域分配，Element Web UI 仪表板会在“自定义保护域运行状况”窗格中显示集群的保护状态。

.可能出现的错误
以下是应用自定义保护域配置后可能会出现的一些错误：

|===


| 错误 | 描述 | 解决方法 


| 设置保护域布局失败：保护域布局会导致节点 ID {9} 无法使用。默认名称和非默认名称不能同时使用。 | 节点未分配保护域。 | 为节点分配保护域。 


| 设置保护域布局失败：保护域类型“custom”拆分了保护域类型“chassis”。 | 多节点机箱中的每个节点都被分配一个与其他节点不同的保护域。 | 确保机箱内的所有节点都分配到相同的保护域。 
|===


== 查找更多信息

* link:../concepts/concept_solidfire_concepts_data_protection.html#custom_pd["自定义保护域"^]
* link:../api/concept_element_api_about_the_api.html["使用 Element API 管理存储"^]

