---
permalink: storage/task_data_manage_volumes.html 
sidebar: sidebar 
keywords: element, solidfire, volume, create, edit, delete, purge, restore, clone, iscsi, fc clients 
summary: SolidFire系统使用卷来配置存储。卷是可通过网络由 iSCSI 或光纤通道客户端访问的块设备。 
---
= 管理卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire系统使用卷来配置存储。卷是可通过网络由 iSCSI 或光纤通道客户端访问的块设备。

在“管理”选项卡的“卷”页面上，您可以创建、修改、克隆和删除节点上的卷。



== 创建卷

您可以创建卷并将该卷与指定的帐户关联。每卷书籍都必须与一个账户关联。通过此关联，该帐户可以使用 CHAP 凭据通过 iSCSI 发起程序访问卷。

创建卷时可以指定 QoS 设置。

. 选择“管理”>“卷”。
. 点击“创建卷”。
. 在“创建新卷”对话框中，输入“卷名称”。
. 请输入体积总大小。
+

NOTE: 默认卷大小选择单位为 GB。您可以创建以 GB 或 GiB 为单位大小的卷：

+
** 1GB = 10亿字节
** 1GiB = 1,073,741,824 字节


. 选择体积的*块大小*。
. 点击“帐户”下拉列表，然后选择应该有权访问该卷的帐户。
+
如果账户不存在，请点击“创建账户”链接，输入新账户名称，然后点击“创建”。账户已创建并与新卷关联。

+

NOTE: 如果账户数量超过 50 个，则列表不会显示。开始输入后，自动完成功能会显示可供选择的值。

. 要设置*服务质量*，请执行以下操作之一：
+
.. 在“策略”下，您可以选择现有的 QoS 策略（如有）。
.. 在“自定义设置”下，设置 IOPS 的自定义最小值、最大值和突发值，或使用默认的 QoS 值。
+
最大 IOPS 或突发 IOPS 值大于 20,000 IOPS 的卷可能需要较高的队列深度或多个会话才能在单个卷上达到此 IOPS 水平。



. 点击“创建卷”。




== 查看成交量详情

. 选择“管理”>“卷”。
. 查看详细信息。
+
** *ID*：系统生成的卷 ID。
** *名称*：创建卷时赋予该卷的名称。
** *帐户*：分配给该卷的帐户名称。
** *访问组*：卷所属的卷访问组的名称。
** *访问权限*：创建卷时分配给该卷的访问类型。可能值：
+
*** 读/写：所有读写操作均被接受。
*** 只读：允许所有读取操作；不允许写入操作。
*** 已锁定：仅允许管理员访问。
*** ReplicationTarget：指定为复制卷对中的目标卷。


** *已用空间*：体积中已使用的空间百分比。
** *大小*：卷的总大小（以 GB 为单位）。
** *主节点 ID*：此卷的主节点。
** *辅助节点 ID*：此卷的辅助节点列表。在过渡状态下（例如次级节点发生变化时），可能存在多个值，但通常只有一个值。
** *QoS 节流*：识别卷是否因主存储节点负载过高而受到节流。
** *QoS策略*：用户定义的QoS策略的名称和链接。
** *最小 IOPS*：保证该卷的最小 IOPS 数。
** *最大 IOPS*：卷允许的最大 IOPS 数。
** *突发IOPS*：在短时间内允许达到的最大IOPS数量。默认值 = 15,000。
** *快照数*：为该卷创建的快照数量。
** *属性*：通过 API 方法以键/值对的形式分配给卷的属性。
** *512e*：指示卷上是否启用了 512e。可能值：
+
*** 是
*** 否


** *创建于*：卷的创建日期和时间。






== 查看单笔交易详情

您可以查看各个卷的性能统计信息。

. 选择“报告”>“销量表现”。
. 在音量列表中，单击音量对应的“操作”图标。
. 单击“查看详细信息”。
+
页面底部出现一个托盘，其中包含有关该卷的一般信息。

. 要查看有关销量的更多详细信息，请点击*查看更多详情*。
+
该系统会显示详细信息以及音量性能图表。





== 编辑活动卷

您可以修改卷属性，例如 QoS 值、卷大小以及计算字节值的计量单位。您还可以修改用于复制的帐户访问权限或限制对卷的访问。

当集群上有足够的空间且满足以下条件时，您可以调整卷的大小：

* 正常运行条件。
* 报告称出现容量错误或故障。
* 该卷正在被克隆。
* 音量正在重新同步。


.步骤
. 选择“管理”>“卷”。
. 在“活动”窗口中，单击要编辑的卷的“操作”图标。
. 单击“*编辑*”。
. *可选：*更改卷的总大小。
+
** 你可以增加体积，但不能减少体积。在一次调整大小的操作中，您只能调整一个卷的大小。垃圾回收操作和软件升级不会中断调整大小操作。
** 如果要调整复制卷的大小，应首先增加指定为复制目标的卷的大小。然后您可以调整源卷的大小。目标体积可以大于或等于源体积，但不能小于源体积。


+
默认卷大小选择单位为 GB。您可以创建以 GB 或 GiB 为单位大小的卷：

+
** 1GB = 10亿字节
** 1GiB = 1,073,741,824 字节


. *可选：*请选择以下不同的帐户访问级别：
+
** 只读
** 读写
** 已锁定
** 复制目标


. *可选：* 选择应该有权访问该卷的帐户。
+
如果账户不存在，请点击“创建账户”链接，输入新的账户名称，然后点击“创建”。账户已创建并与卷关联。

+

NOTE: 如果账户数量超过 50 个，则列表不会显示。开始输入后，自动完成功能会显示可供选择的值。

. *可选：*要更改“服务质量”中的选择，请执行以下操作之一：
+
.. 在“策略”下，您可以选择现有的 QoS 策略（如有）。
.. 在“自定义设置”下，设置 IOPS 的自定义最小值、最大值和突发值，或使用默认的 QoS 值。
+

NOTE: 如果您在卷上使用 QoS 策略，您可以设置自定义 QoS 以移除 QoS 策略与该卷的关联。自定义 QoS 将覆盖和调整卷 QoS 设置的 QoS 策略值。

+

TIP: 更改 IOPS 值时，应以十或百为单位递增。输入值必须为有效的整数。

+

TIP: 配置卷，使其突发值极高。这样一来，系统就能更快地处理偶尔出现的大块顺序工作负载，同时还能限制卷的持续 IOPS。



. 点击“保存更改”。




== 删除卷

您可以从 Element 存储集群中删除一个或多个卷。

系统不会立即清除已删除的卷；该卷在大约 8 小时内保持可用。如果在系统清除卷之前还原它，该卷将恢复联机并还原 iSCSI 连接。

如果用于创建快照的卷被删除，则其关联的快照将变为非活动状态。当删除源卷时，关联的非活动快照也会从系统中删除。


IMPORTANT: 在安装或升级过程中，会创建与管理服务关联的持久卷并将其分配给新帐户。如果您使用的是持久卷，请勿修改或删除卷或其关联的帐户。

.步骤
. 选择“管理”>“卷”。
. 要删除单个卷，请执行以下步骤：
+
.. 点击要删除的卷对应的“操作”图标。
.. 在出现的菜单中，单击“删除”。
.. 确认此操作。


+
系统会将卷移至“卷”页面上的“已删除”区域。

. 要删除多个卷，请执行以下步骤：
+
.. 在卷列表中，选中要删除的卷旁边的复选框。
.. 点击“批量操作”。
.. 在出现的菜单中，单击“删除”。
.. 确认此操作。
+
系统会将卷移至“卷”页面上的“已删除”区域。







== 恢复已删除的卷

如果系统中的某个卷已被删除但尚未被清除，则可以将其恢复。系统会在删除卷后大约八小时自动清除该卷。如果系统已清除该卷，则无法恢复。

. 选择“管理”>“卷”。
. 点击“已删除”选项卡查看已删除卷的列表。
. 单击要恢复的卷对应的“操作”图标。
. 在出现的菜单中，单击“恢复”。
. 确认此操作。
+
该卷被放入*活动*卷列表中，并且与该卷的 iSCSI 连接已恢复。





== 清除卷

当一个卷被清除时，它会从系统中永久删除。该卷中的所有数据都丢失了。

系统会在删除卷八小时后自动清除这些卷。但是，如果您想在预定时间之前清除卷，您可以这样做。

. 选择“管理”>“卷”。
. 点击“已删除”按钮。
. 执行以下步骤以清除单个卷或多个卷。
+
[cols="25,75"]
|===
| 选项 | 步骤 


 a| 
清除单个卷
 a| 
.. 单击要清除的卷的“操作”图标。
.. 点击“清除”。
.. 确认此操作。




 a| 
清除多个卷
 a| 
.. 选择要清除的卷。
.. 点击“批量操作”。
.. 在出现的菜单中，选择“清除”。
.. 确认此操作。


|===




== 克隆卷

您可以创建单个卷或多个卷的克隆，以创建数据在特定时间点的副本。克隆卷时，系统会创建卷的快照，然后创建快照引用的数据的副本。这是一个异步过程，该过程所需的时间取决于您要克隆的卷的大小和当前的集群负载。

集群一次最多支持每个卷运行两个克隆请求，一次最多支持八个活动卷克隆操作。超出这些限制的请求将被排队，稍后处理。


NOTE: 不同的操作系统对克隆卷的处理方式各不相同。 VMware ESXi 会将克隆卷视为卷副本或快照卷。该卷将是一个可用于创建新数据存储的设备。有关挂载克隆卷和处理快照 LUN 的更多信息，请参阅 VMware 文档。 https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EEFEB765-A41F-4B6D-917C-BB9ABB80FC80.html["挂载 VMFS 数据存储副本"]和 https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EBAB0D5A-3C77-4A9B-9884-3D4AD69E28DC.html["管理重复的 VMFS 数据存储"]。


IMPORTANT: 在通过克隆到较小大小来截断克隆卷之前，请确保已准备好分区，以便它们能够适应较小的卷。

.步骤
. 选择“管理”>“卷”。
. 要克隆单个卷，请执行以下步骤：
+
.. 在“活动”页面的卷列表中，单击要克隆的卷的“操作”图标。
.. 在出现的菜单中，单击“克隆”。
.. 在“克隆卷”窗口中，输入新克隆卷的卷名。
.. 使用“容量大小”微调框和列表选择容量的大小和测量单位。
+

NOTE: 默认卷大小选择单位为 GB。您可以创建以 GB 或 GiB 为单位大小的卷：

+
*** 1GB = 10亿字节
*** 1GiB = 1,073,741,824 字节


.. 选择新克隆卷的访问类型。
.. 从“帐户”列表中选择要与新克隆卷关联的帐户。
+

NOTE: 您可以在此步骤中创建帐户，方法是单击“创建帐户”链接，输入帐户名称，然后单击“创建”。创建账户后，系统会自动将其添加到“账户”列表中。



. 要克隆多个卷，请执行以下步骤：
+
.. 在“活动”页面的卷列表中，选中要克隆的任何卷旁边的复选框。
.. 点击“批量操作”。
.. 在出现的菜单中，选择“克隆”。
.. 在“克隆多个卷”对话框中，在“新卷名称前缀”字段中输入克隆卷的前缀。
.. 从“帐户”列表中选择要与克隆卷关联的帐户。
.. 选择克隆卷的访问类型。


. 点击“开始克隆”。
+

NOTE: 增加克隆的体积大小，会在新体积的末尾产生额外的可用空间。根据您对卷的使用方式，您可能需要扩展分区或在可用空间中创建新分区才能充分利用它。





== 了解更多信息

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire和 Element 软件文档"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element vCenter Server 插件"^]

