---
permalink: storage/task_data_protection_create_a_snapshot_schedule.html 
sidebar: sidebar 
keywords: snapshot schedule, create, volumes, recurring schedule 
summary: 您可以安排对一个或多个卷进行快照，使其按指定的时间间隔自动执行。 
---
= 创建快照计划
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以安排对一个或多个卷进行快照，使其按指定的时间间隔自动执行。

配置快照计划时，您可以选择基于星期几或月份几的时间间隔。您还可以创建重复计划，并指定下次快照发生的日期、小时和分钟。

如果您安排快照运行的时间段不能被 5 分钟整除，则快照将在下一个能被 5 分钟整除的时间段运行。例如，如果您安排快照在 UTC 时间 12:42:00 运行，它将在 UTC 时间 12:45:00 运行。您无法安排快照运行的间隔小于 5 分钟。

从 Element 12.5 开始，您可以从用户界面启用序列创建并选择按先进先出 (FIFO) 原则保留快照。

* *启用序列创建*选项指定一次只复制一个快照。当先前的快照复制仍在进行中时，创建新快照会失败。如果未选中该复选框，则允许在另一个快照复制仍在进行时创建快照。
* *FIFO* 选项增加了保留一致数量的最新快照的功能。选中该复选框后，快照将按先进先出 (FIFO) 的原则保留。当 FIFO 快照队列达到最大深度后，插入新的 FIFO 快照时，最旧的 FIFO 快照将被丢弃。


.步骤
. 选择“数据保护”>“日程安排”。
. 选择“创建日程”。
. 在“卷 ID CSV”字段中，输入单个卷 ID 或以逗号分隔的卷 ID 列表，以包含在快照操作中。
. 请输入新的课程表名称。
. 选择日程类型，并从提供的选项中设置日程。
. *可选：*选择*重复计划*可无限期重复快照计划。
. *可选：*在“新快照名称”字段中输入新快照的名称。
+
如果将此字段留空，系统将使用快照创建的时间和日期作为名称。

. *可选：*选中“配对时在复制中包含快照”复选框，以确保在配对父卷时，快照被捕获到复制中。
. *可选：*选中“启用序列创建”复选框，以确保一次只复制一个快照。
. 要设置快照的保留期限，请从以下选项中选择：
+
** *可选：*选中 *FIFO（先进先出）*复选框，以保留一致数量的最新快照。
** 选择“永久保留”可将快照无限期地保留在系统中。
** 选择“设置保留期限”，然后使用日期微调框选择系统保留快照的时间长度。


. 选择“创建日程”。

