---
permalink: storage/task_data_manage_vol_access_group_create_a_volume_access_group.html 
sidebar: sidebar 
keywords: volume access group, create, initiators 
summary: 您可以通过将发起程序映射到卷集合来创建卷访问组，从而实现安全访问。然后，您可以使用帐户 CHAP 发起程序密钥和目标密钥授予对组中卷的访问权限。 
---
= 创建卷访问组
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过将发起程序映射到卷集合来创建卷访问组，从而实现安全访问。然后，您可以使用帐户 CHAP 发起程序密钥和目标密钥授予对组中卷的访问权限。

如果使用基于发起方的 CHAP，则可以为卷访问组中的单个发起方添加 CHAP 凭证，从而提供更高的安全性。这样，您就可以将此选项应用于已存在的卷访问组。

.步骤
. 点击“管理”>“访问组”。
. 点击“创建访问组”。
. 在“名称”字段中输入卷访问组的名称。
. 可以通过以下方式之一将发起程序添加到卷访问组：
+
[cols="25,75"]
|===
| 选项 | 描述 


 a| 
添加光纤通道发起程序
 a| 
.. 在“添加发起程序”下，从“未绑定光纤通道发起程序”列表中选择一个现有的光纤通道发起程序。
.. 点击*添加FC发起者*。
+

NOTE: 在此步骤中，您可以点击“创建发起者”链接，输入发起者名称，然后点击“创建”，即可创建发起者。创建发起程序后，系统会自动将其添加到发起程序列表中。



格式示例如下：

[listing]
----
5f:47:ac:c0:5c:74:d4:02
----


 a| 
添加 iSCSI 发起程序
 a| 
在“添加发起方”下，从发起方列表中选择一个现有的发起方。 *注意：* 您可以在此步骤中创建发起者，方法是单击“创建发起者”链接，输入发起者名称，然后单击“创建”。创建发起程序后，系统会自动将其添加到发起程序列表中。

格式示例如下：

[listing]
----
iqn.2010-01.com.solidfire:c2r9.fc0.2100000e1e09bb8b
----

TIP: 您可以通过在“管理”>“卷”>“活动”列表中选择卷的“操作”菜单中的“查看详细信息”来查找每个卷的发起者 IQN。

修改发起程序时，可以将 requiredCHAP 属性切换为 True，这样就可以设置目标发起程序密钥。有关详细信息，请参阅 ModifyInitiator API 方法的 API 信息。

link:../api/concept_element_api_about_the_api.html["使用 Element API 管理存储"]

|===
. *可选：*根据需要添加更多启动器。
. 在“添加卷”下，从“卷”列表中选择一个卷。
+
该卷出现在“已附加卷”列表中。

. *可选：*根据需要添加更多卷。
. 点击“创建访问组”。




== 查找更多信息

xref:task_data_manage_vol_access_group_add_volumes.adoc[将卷添加到访问组]
