---
permalink: setup/concept_setup_configure_a_storage_node.html 
sidebar: sidebar 
keywords: configuring node,configure storage node,configuring using TUI,configuring using node UI 
summary: 必须先配置各个节点，然后才能将其添加到集群中。在机架单元中安装节点并连接线缆并通电后，可以使用每个节点的 UI 或节点终端用户界面配置节点网络设置。 
---
= 配置存储节点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
必须先配置各个节点，然后才能将其添加到集群中。在机架单元中安装节点并连接电缆并通电后，可以使用每个节点的 UI 或节点终端用户界面 (TUI) 配置节点网络设置。请确保您已具备节点所需的网络配置信息后再继续操作。

配置存储节点有两种方法：

* <<使用节点级用户界面配置存储节点。,每个节点的用户界面>>使用节点级用户界面 (`https://<node_management_IP>:442`）配置节点网络设置。
* <<使用 TUI 配置存储节点,途易>>使用节点终端用户界面（TUI）配置节点。


您不能将具有 DHCP 分配的 IP 地址的节点添加到集群中。您可以使用 DHCP IP 地址在每个节点的 UI、TUI 或 API 中对节点进行初始配置。在初始配置期间，您可以添加静态 IP 地址信息，以便将节点添加到集群中。

完成初始配置后，您可以使用节点的管理 IP 地址访问该节点。然后您可以更改节点设置、将其添加到集群，或者使用该节点创建集群。您还可以使用 Element 软件 API 方法配置新节点。


NOTE: 从 Element 版本 11.0 开始，节点可以配置 IPv4、IPv6 或两者的地址作为其管理网络。这适用于存储节点和管理节点，但管理节点 11.3 及更高版本除外，该版本不支持 IPv6。创建集群时，MVIP 只能使用单个 IPv4 或 IPv6 地址，并且必须在所有节点上配置相应的地址类型。



== 使用节点级用户界面配置存储节点。

您可以使用每个节点的用户界面来配置节点。

.关于此任务
* 您可以将节点配置为具有 IPv4 地址或 IPv6 地址。
* 您需要 TUI 中显示的 DHCP 地址才能访问节点。不能使用 DHCP 地址将节点添加到集群中。
+

IMPORTANT: 您应该为不同的子网配置管理（Bond1G）和存储（Bond10G）接口。如果 Bond1G 和 Bond10G 接口配置为同一子网，则通过 Bond1G 接口发送存储流量时会导致路由问题。如果必须使用同一子网进行管理和存储流量，请手动配置管理流量以使用 Bond10G 接口。您可以使用每个节点的 UI 的“集群设置”页面对每个节点执行此操作。



.步骤
. 在浏览器窗口中，输入节点的 DHCP IP 地址。
+
您必须添加扩展名 `:442` 访问节点；例如， `https://172.25.103.6:442`。

+
“网络设置”选项卡打开后，首先显示的是“Bond1G”部分。

. 进入1G管理网络设置。
. 单击“应用更改”。
. 点击 *Bond10G* 显示 10G 存储网络设置。
. 输入 10G 存储网络设置。
. 单击“应用更改”。
. 点击*集群设置*。
. 请输入 10G 网络的主机名。
. 请输入集群名称。
+

IMPORTANT: 在创建集群之前，必须将此名称添加到所有节点的配置中。集群中的所有节点必须具有相同的集群名称。集群名称区分大小写。

. 单击“应用更改”。




== 使用 TUI 配置存储节点

您可以使用终端用户界面 (TUI) 对新节点进行初始配置。

您应该为不同的子网配置 Bond1G（管理）和 Bond10G（存储）接口。如果 Bond1G 和 Bond10G 接口配置为同一子网，则通过 Bond1G 接口发送存储流量时会出现路由问题。如果必须使用同一子网进行管理和存储流量，请手动配置管理流量以使用 Bond10G 接口。您可以使用 Element UI 的“集群”>“节点”页面对每个节点执行此操作。

.步骤
. 将键盘和显示器连接到节点，然后打开节点电源。
+
NetApp存储的 TUI 主菜单出现在 tty1 终端上。

+

NOTE: 如果节点无法连接到您的配置服务器，TUI 将显示错误消息。检查配置服务器连接或网络连接以解决错误。

. 选择“网络”>“网络配置”。
+

TIP: 要浏览菜单，请按向上或向下箭头键。要从一个按钮移动到另一个按钮或从按钮移动到字段，请按 *Tab* 键。要在字段之间导航，请使用向上或向下箭头键。

. 选择 *Bond1G（管理）* 或 *Bond10G（存储）* 来配置节点的 1G 和 10G 网络设置。
. 对于“绑定模式”和“状态”字段，按 *Tab* 选择“帮助”按钮，即可查看可用选项。
+
集群中的所有节点必须具有相同的集群名称。集群名称区分大小写。如果网络上运行着 DHCP 服务器，并且有可用的 IP 地址，则 1GbE 地址会出现在地址字段中。

. 按 *Tab* 键选择 *OK* 按钮并保存更改。
+
该节点处于待定状态，可以添加到现有集群或新集群中。





== 查找更多信息

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire和 Element 软件文档"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element vCenter Server 插件"^]

