---
permalink: setup/task_setup_fc_create_a_new_cluster_with_fibre_channel_nodes.html 
sidebar: sidebar 
keywords:  
summary: 配置完各个光纤通道节点后，即可创建新集群。创建集群时，系统会自动为您创建一个集群管理员用户帐户。集群管理员有权管理所有集群属性，并且可以创建其他集群管理员帐户。 
---
= 创建包含光纤通道节点的新集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
配置完各个光纤通道节点后，即可创建新集群。创建集群时，系统会自动为您创建一个集群管理员用户帐户。集群管理员有权管理所有集群属性，并且可以创建其他集群管理员帐户。

在新节点配置期间，会为每个节点分配 1G 或 10G 管理 IP (MIP) 地址。您必须使用配置过程中创建的节点 IP 地址之一来打开“创建新集群”页面。您使用的 IP 地址取决于您为集群管理选择的网络。

.你需要什么
您已配置好各个光纤通道节点。

.步骤
. 在浏览器窗口中，输入节点 MIP 地址。
. 在“创建新集群”中，输入以下信息：
+
** 管理 VIP：1GbE 或 10GbE 网络上的可路由虚拟 IP，用于网络管理任务。
** iSCSI（存储）VIP：10GbE 网络上的虚拟 IP，用于存储和 iSCSI 发现。
+

NOTE: 创建集群后，无法更改 SVIP。

** 用户名：用于对集群进行身份验证访问的主集群管理员用户名。您必须保存用户名以备将来参考。
+

NOTE: 用户名可以使用大写字母、小写字母、特殊字符和数字。

** 密码：用于对集群进行身份验证访问的密码。您必须保存用户名以备将来参考。双向数据保护默认启用。您无法更改此设置。


. 请阅读最终用户许可协议，然后点击“我同意”。
. *可选*：在节点列表中，确保不应包含在集群中的节点的复选框未被选中。
. 点击“创建集群”。
+
根据集群中节点的数量，系统可能需要几分钟时间来创建集群。在配置正确的网络上，一个由五个节点组成的小集群应该在一分钟内完成。集群创建完成后，“创建新集群”窗口将重定向到集群的 MVIP URL 地址并显示 Web UI。





== 查找更多信息

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire和 Element 软件文档"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element vCenter Server 插件"^]

