---
permalink: api/concept_element_api_about_the_api.html 
sidebar: sidebar 
keywords: SolidFire,API,overview,about,Element 
summary: Element API 基于 HTTPS 上的 JSON-RPC 协议。 JSON-RPC 是一种基于轻量级 JSON 数据交换格式的简单文本 RPC 协议。所有主流编程语言都有相应的客户端库。 
---
= 了解如何使用 Element API 管理存储
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Element API 基于 HTTPS 上的 JSON-RPC 协议。 JSON-RPC 是一种基于轻量级 JSON 数据交换格式的简单文本 RPC 协议。所有主流编程语言都有相应的客户端库。

您可以通过 HTTPS POST 请求向 API 端点发出 API 请求。 POST 请求的主体是一个 JSON-RPC 请求对象。该 API 目前不支持批量请求（单个 POST 请求中包含多个请求对象）。提交 API 请求时，必须使用“application/json-rpc”作为请求的内容类型，并确保请求体未进行表单编码。


NOTE: Element Web UI 使用了本文档中描述的 API 方法。您可以通过启用 API 日志在用户界面中监控 API 操作；这样您就可以看到向系统发出的方法。您可以同时启用请求和响应，以查看系统如何响应发出的方法。

除非另有说明，API 响应中的所有日期字符串均为 UTC+0 格式。


NOTE: 当存储集群负载过重或您连续提交多个 API 请求而没有间隔时，方法可能会失败并返回错误“xDBVersionMismatch”。如果发生这种情况，请重试方法调用。



== 常见物品

Element软件API使用JSON对象来表示组织化的数据概念。这些 API 方法中有很多都利用这些对象进行数据输入和输出。本节介绍这些常用对象；仅在单个方法中使用的对象将与该方法一起进行文档说明，而不是在本节中说明。

link:../api/reference_element_api_account.html["了解常见物品"]



== 常用方法

常用方法是指用于检索有关存储集群、API 本身或正在进行的 API 操作的信息的方法。

link:../api/reference_element_api_getapi.html["了解常用方法"]



== 账户 API 方法

账户管理功能允许您添加、删除、查看和修改账户及安全信息。

link:../api/reference_element_api_addaccount.html["了解帐户 API 方法"]



== 管理员 API 方法

您可以使用管理员 API 方法创建、修改、查看和删除存储集群管理员，并为有权访问存储集群的用户分配访问级别和权限。

link:../api/reference_element_api_addclusteradmin.html["了解管理员 API 方法"]



== 集群 API 方法

Element 软件集群 API 方法使您能够管理存储集群及其所属节点的配置和拓扑。

某些集群 API 方法在属于集群的节点上操作，或者在已配置为加入集群的节点上操作。您可以向新集群或现有集群添加节点。准备添加到集群中的节点处于“待处理”状态，这意味着它们已经配置好，但尚未添加到集群中。

link:../api/reference_element_api_addnodes.html["了解集群 API 方法"]



== 集群创建 API 方法

您可以使用这些 API 方法创建存储集群。所有这些方法都需要在单个节点上针对 API 端点使用。

link:../api/reference_element_api_checkproposedcluster.html["了解集群创建 API 方法"]



== 驱动 API 方法

您可以使用驱动器 API 方法添加和管理存储集群中可用的驱动器。当您向存储集群添加存储节点或在现有存储节点中安装新驱动器时，这些驱动器即可添加到存储集群中。

link:../api/reference_element_api_adddrives.html["了解驱动 API 方法"]



== 光纤通道 API 方法

您可以使用光纤通道 API 方法添加、修改或删除存储集群的光纤通道节点成员。

link:../api/reference_element_api_getvolumeaccessgrouplunassignments.html["了解光纤通道 API 方法"]



== 发起方 API 方法

启动器方法允许您添加、删除、查看和修改 iSCSI 启动器对象，这些对象处理存储系统和外部存储客户端之间的通信。

link:../api/reference_element_api_createinitiators.html["了解发起方 API 方法"]



== LDAP API 方法

您可以使用轻量级目录访问协议 (LDAP) 对 Element 存储进行身份验证。本节介绍的 LDAP API 方法使您能够配置对存储集群的 LDAP 访问。

link:../api/reference_element_api_addldapclusteradmin.html["了解 LDAP API 方法"]



== 多因素身份验证 API 方法

您可以使用多因素身份验证 (MFA) 通过安全断言标记语言 (SAML) 使用第三方身份提供商 (IdP) 来管理用户会话。

link:../api/reference_element_api_addidpclusteradmin.html["了解多因素身份验证 API 方法"]



== 会话身份验证 API 方法

您可以使用基于会话的身份验证来管理用户会话。

link:../api/reference_element_api_listauthsessionbyclusteradmin.html["了解会话身份验证 API 方法"]



== Node API 方法

您可以使用节点 API 方法来配置各个节点。这些方法适用于需要配置的单个节点、已配置但尚未加入集群的节点，或者正在积极加入集群的节点。节点 API 方法允许您查看和修改单个节点以及用于与节点通信的集群网络的设置。必须针对单个节点运行这些方法；不能针对集群的地址运行每个节点的 API 方法。

link:../api/reference_element_api_checkpingonvlan.html["了解节点 API 方法"]



== 复制 API 方法

复制 API 方法使您可以连接两个集群以实现持续数据保护 (CDP)。连接两个集群后，集群内的活动卷可以持续复制到第二个集群，从而实现数据恢复。通过配对卷进行复制，您可以保护数据免受可能导致数据无法访问的事件的影响。

link:../api/reference_element_api_cluster_pairing_order_of_operations.html["了解复制 API 方法"]



== 安全 API 方法

您可以将 Element 软件与外部安全相关服务（例如外部密钥管理服务器）集成。这些与安全相关的方法使您能够配置 Element 的安全功能，例如静态加密的外部密钥管理。

link:../api/reference_element_api_addkeyservertoproviderkmip.html["了解安全 API 方法"]



== SnapMirror API 方法

Element Web UI 使用SnapMirror API 方法来管理与远程ONTAP系统镜像的快照。这些方法仅供 Element Web UI 使用。如果您需要使用 API 访问SnapMirror功能，请使用ONTAP API。  SnapMirror API 方法未提供请求和返回示例。

link:../api/reference_element_api_abortsnapmirrorrelationship.html["了解SnapMirror API 方法"]



== 系统配置 API 方法

系统配置 API 方法允许您获取和设置适用于集群中所有节点的配置值。

link:../api/reference_element_api_disablebmccoldreset.html["了解系统配置 API 方法"]



== 多租户网络 API 方法

Element 存储集群中的多租户网络允许位于不同逻辑网络上的多个客户端之间的流量连接到同一个 Element 存储集群，而无需 3 层路由。

通过使用 VLAN 标记，与存储集群的连接在网络堆栈中进行了隔离。



=== 建立多租户虚拟网络的前提条件

* 您必须已经确定要分配给存储节点上虚拟网络的客户端网络 IP 地址块。
* 您必须确定一个客户端存储网络 IP (SVIP) 地址，该地址将用作所有存储流量的端点。




=== 虚拟网络操作顺序

. 使用 AddVirtualNetwork 方法批量配置您输入的 IP 地址。
+
添加虚拟网络后，集群会自动执行以下操作：

+
** 每个存储节点都会创建一个虚拟网络接口。
** 每个存储节点都被分配一个 VLAN 地址，可以使用虚拟 SVIP 进行路由。
** 即使节点重启，VLAN IP 地址也会保留在每个节点上。


. 分配虚拟网络接口和 VLAN 地址后，即可将客户端网络流量分配给虚拟 SVIP。


link:../api/concept_element_api_virtual_network_naming_conventions.html["了解多租户网络 API 方法"]



== 容量 API 方法

Element 软件卷 API 方法使您能够管理位于存储节点上的卷。您可以使用这些方法创建、修改、克隆和删除卷。您还可以使用卷 API 方法来收集和显示卷的数据测量结果。

link:../api/reference_element_api_cancelclone.html["了解卷 API 方法"]



== 卷访问组 API 方法

卷访问组方法允许您添加、删除、查看和修改卷访问组，卷访问组是用户可以使用 iSCSI 或光纤通道发起程序访问的卷的集合。

link:../api/reference_element_api_addinitiatorstovolumeaccessgroup.html["了解卷访问组 API 方法"]



== 卷快照 API 方法

Element 软件卷快照 API 方法使您能够管理卷快照。您可以使用卷快照 API 方法创建、修改、克隆和删除卷快照。

link:../api/concept_element_api_snapshots_overview.html["了解卷快照 API 方法"]



== 虚拟卷 API 方法

Element 软件虚拟卷 API 方法使您能够管理虚拟卷 (VVol)。您可以使用这些 API 方法查看现有的 VVol，以及创建、修改和删除虚拟卷存储容器。虽然你不能使用这些方法来操作普通卷，但你可以使用普通卷 API 方法来列出有关 VVols 的信息。

link:../api/reference_element_api_createstoragecontainer.html["了解虚拟卷 API 方法"]



== 查找更多信息

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire和 Element 软件文档"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["NetApp SolidFire和 Element 产品早期版本的文档"^]

