---
permalink: api/reference_element_api_modifyvirtualnetwork.html 
sidebar: sidebar 
keywords: virtual,network,modify,modifying,change,changing,edit,editing,modifyvirtualnetwork 
summary: 您可以使用 ModifyVirtualNetwork 方法更改现有虚拟网络的属性。 
---
= 修改虚拟网络
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
你可以使用 `ModifyVirtualNetwork`更改现有虚拟网络属性的方法。

此方法允许您添加或删除地址块、更改子网掩码或修改虚拟网络的名称或描述。您还可以使用它来启用或禁用命名空间，以及在虚拟网络上启用命名空间时添加或删除网关。


NOTE: 此方法需要 virtualNetworkID 或 virtualNetworkTag 作为参数，但不能同时使用两者。

小心：

通过更改命名空间参数来启用或禁用现有虚拟网络的可路由存储 VLAN 功能，会中断虚拟网络处理的任何流量。最好在计划的维护窗口期间更改命名空间参数。



== 参数

该方法有以下输入参数：

|===


| 名称 | 描述 | 类型 | 默认值 | 必填项 


 a| 
虚拟网络 ID
 a| 
要修改的虚拟网络的唯一标识符。这是集群分配的虚拟网络 ID。
 a| 
整数
 a| 
无
 a| 
否



 a| 
虚拟网络标签
 a| 
用于标识要修改的虚拟网络的网络标签。
 a| 
整数
 a| 
无
 a| 
否



 a| 
地址块
 a| 
要为此虚拟网络设置的新地址块。这可能包括向现有对象添加新的地址块，或者省略需要删除的未使用的地址块。或者，您可以扩展或缩小现有地址块的大小。对于虚拟网络对象，您只能增加起始地址块的大小；您永远不能减少它。此对象必需的成员：

* 起始地址：IP 地址范围的起始地址。  （细绳）
* 大小：要包含在块中的 IP 地址数量。  （整数）

 a| 
JSON 对象
 a| 
无
 a| 
否



 a| 
网关
 a| 
虚拟网络网关的IP地址。仅当命名空间参数设置为 true 时，此参数才有效。
 a| 
string
 a| 
无
 a| 
否



 a| 
属性
 a| 
JSON 对象格式的名称-值对列表。
 a| 
JSON 对象
 a| 
无
 a| 
否



 a| 
name
 a| 
虚拟网络的新名称。
 a| 
string
 a| 
无
 a| 
否



 a| 
namespace
 a| 
设置为 true 时，通过重新创建虚拟网络并配置命名空间来启用可路由存储 VLAN 功能。设置为 false 时，禁用虚拟网络的 VRF 功能。更改此值会中断通过此虚拟网络的流量。
 a| 
布尔值
 a| 
无
 a| 
否



 a| 
netmask
 a| 
为此虚拟网络创建新的网络掩码。
 a| 
string
 a| 
无
 a| 
否



 a| 
svip
 a| 
此虚拟网络的存储虚拟 IP 地址。虚拟网络的 SVIP 无法更改。要使用不同的 SVIP 地址，必须创建一个新的虚拟网络。
 a| 
string
 a| 
无
 a| 
否

|===


== 返回值

此方法没有返回值。



== 请求示例

该方法的请求类似于以下示例：

[listing]
----
{
  "method": "ModifyVirtualNetwork",
  "params": {
    "virtualNetworkID": 2,
    "name": "ESX-VLAN-3112",
    "addressBlocks": [
     {
      "start": "10.1.112.1",
      "size": 20
     },
     {
      "start": "10.1.112.100",
      "size": 20
     }
   ],
    "netmask": "255.255.255.0",
    "gateway": "10.0.1.254",
    "svip": "10.1.112.200",
    "attributes": {}
  },
  "id":1
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
  "id": 1,
  "result": {
  }
}
----


== 自版本以来的新版本

9.6
