---
permalink: api/reference_element_api_createinitiators.html 
sidebar: sidebar 
keywords: create,creating,initiator,CreateInitiators,WWPN,IQN,initiators 
summary: '您可以使用 CreateInitiators 创建多个新的发起方 IQN 或全球端口名称 (WWPN)，并可选择为它们分配别名和属性。使用 CreateInitiators 创建新启动器时，还可以将其添加到卷访问组。' 
---
= 创建启动器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `CreateInitiators`创建多个新的发起方 IQN 或全球端口名称 (WWPN)，并可选择为其分配别名和属性。当你使用 `CreateInitiators`要创建新的发起程序，您还可以将其添加到卷访问组。

如果操作未能创建参数中提供的启动器之一，则该方法返回错误，并且不会创建任何启动器（不可能部分完成）。



== 参数

该方法具有以下输入参数：

|===
| 名称 | 描述 | 类型 | 默认值 | 必填项 


 a| 
发起者
 a| 
包含每个新发起者特征的对象列表。对象：

* `alias`（可选）要分配给此发起者的友好名称。  （细绳）
* `attributes`（可选）要分配给此启动器的 JSON 属性集。  （JSON 对象）
* `chapUsername`（可选）此发起者的唯一 CHAP 用户名。如果在创建期间未指定，则默认为发起者名称 (IQN)，并且 requireChap 为 true。  （细绳）
* `initiatorSecret`（可选）用于验证发起者的 CHAP 密钥。如果在创建时未指定且 requireChap 为 true，则默认使用随机生成的密钥。  （细绳）
* `name`（必填）要创建的发起者（IQN 或 WWPN）的名称。  （细绳）
* `requireChap`（可选）如果此发起方在会话登录期间需要 CHAP，则为 True。  （布尔值）
* `targetSecret`（可选）用于验证目标身份的 CHAP 密钥（在使用相互 CHAP 身份验证时）。如果在创建时未指定且 requireChap 为 true，则默认使用随机生成的密钥。  （细绳）
* `virtualNetworkIDs`（可选）与此启动器关联的虚拟网络标识符列表。如果您定义了一个或多个虚拟网络，则此发起程序只能登录到这些虚拟网络。如果没有定义任何虚拟网络，则此发起程序可以登录到所有网络。
* `volumeAccessGroupID`（可选）要将新创建的启动器添加到的卷访问组的 ID。  （整数）

 a| 
JSON 对象数组
 a| 
无
 a| 
是

|===


== 返回值

该方法返回以下值：

|===


| 名称 | 描述 | 类型 


 a| 
发起者
 a| 
描述新创建的启动器的对象列表。
 a| 
xref:reference_element_api_initiator.adoc[发起者]大批

|===


== 错误

此方法可能会返回以下错误：

|===


| 名称 | 描述 


 a| 
xInitiatorExists
 a| 
如果您选择的发起者名称已存在，则返回该名称。

|===


== 请求示例

该方法的请求类似于以下示例：

[listing]
----
{
  "id": 3291,
  "method": "CreateInitiators",
  "params": {
    "initiators": [
      {
        "name": "iqn.1993-08.org.debian:01:288170452",
        "alias": "example1"
      },
      {
        "name": "iqn.1993-08.org.debian:01:297817012",
        "alias": "example2"
      }
    ]
  }
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
  "id": 3291,
  "result": {
    "initiators": [
      {
        "alias": "example1",
        "attributes": {},
        "initiatorID": 145,
        "initiatorName": "iqn.1993-08.org.debian:01:288170452",
        "volumeAccessGroups": []
      },
      {
        "alias": "example2",
        "attributes": {},
        "initiatorID": 146,
        "initiatorName": "iqn.1993-08.org.debian:01:297817012",
        "volumeAccessGroups": []
      }
    ]
  }
}
----


== 自版本以来的新版本

9.6



== 查找更多信息

xref:reference_element_api_listinitiators.adoc[列表发起者]
