---
permalink: api/reference_element_api_rollbacktogroupsnapshot.html 
sidebar: sidebar 
keywords: rollbacktogroupsnapshot,snapshot,group,individual,creating,create,roll,back,rollback,roll back,existing 
summary: 您可以使用 RollbackToGroupSnapshot 将快照组中的所有单个卷回滚到每个卷的单独快照。 
---
= 回滚到组快照
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `RollbackToGroupSnapshot`将快照组中的所有卷回滚到每个卷的单独快照。

回滚到组快照会在组快照中为每个卷创建一个临时快照。

[NOTE]
====
* 如果集群容量处于第 1、2 或 3 阶段，则允许创建快照。当集群容量达到 4 或 5 级时，不会创建快照。
* 当切片同步正在进行时，将卷回滚到组快照可能会失败。重试 `RollbackToGroupSnapshot`同步完成后。


====


== 参数

该方法有以下输入参数：

|===
| 名称 | 描述 | 类型 | 默认值 | 必填项 


 a| 
`groupSnapshotID`
 a| 
群组快照的唯一标识符。
 a| 
整数
 a| 
无
 a| 
是



 a| 
`attributes`
 a| 
JSON 对象格式的名称-值对列表。
 a| 
JSON 对象
 a| 
无
 a| 
否



 a| 
`name`
 a| 
如果创建卷的当前状态，则创建该状态的组快照的名称。 `saveCurrentState`设置为 true。如果您不指定名称，则快照（组卷和单个卷）的名称将设置为回滚发生时的时间戳。
 a| 
string
 a| 
无
 a| 
否



 a| 
`saveCurrentState`
 a| 
指定是否保存先前活动卷映像。有效值：

* `true`：保留先前的活动卷映像。
* `false`：先前的活动卷映像已被删除。

 a| 
布尔值
 a| 
false
 a| 
否

|===


== 返回值

此方法具有以下返回值：

|===


| 名称 | 描述 | 类型 


 a| 
members
 a| 
包含组快照成员的卷 ID 和快照 ID 的数组。价值观：

* 校验和：存储快照中数据的简短字符串表示形式。之后可以使用此校验和来比较其他快照，以检测数据中的错误。  （细绳）
* snapshotID：用于创建新快照的快照的唯一 ID。  snapshotID 必须是给定卷上的快照。  （整数）
* volumeID：快照的源卷 ID。  （整数）

 a| 
JSON 对象数组



 a| 
组快照ID
 a| 
如果 `saveCurrentState`已设置为 false，此值为 null。

如果 `saveCurrentState`设置为 true，即新创建的组快照的唯一 ID。
 a| 
整数



 a| 
组快照
 a| 
如果 `saveCurrentState`已设置为 false，此值为 null。

如果 `saveCurrentState`被设置为 true，这是一个包含有关组快照信息的对象， `RollbackToGroupSnapshot`刚刚回滚到。
 a| 
xref:reference_element_api_groupsnapshot.adoc[组快照]

|===


== 请求示例

该方法的请求类似于以下示例：

[listing]
----
{
  "id": 438,
  "method": "RollbackToGroupSnapshot",
  "params": {
    "groupSnapshotID": 1,
    "name": "grpsnap1",
    "saveCurrentState": true
  }
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
  "id": 438,
  "result": {
    "groupSnapshot": {
      "attributes": {},
      "createTime": "2016-04-06T17:27:17Z",
      "groupSnapshotID": 1,
      "groupSnapshotUUID": "468fe181-0002-4b1d-ae7f-8b2a5c171eee",
      "members": [
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2016-04-06T17:27:17Z",
          "enableRemoteReplication": false,
          "expirationReason": "None",
          "expirationTime": null,
          "groupID": 1,
          "groupSnapshotUUID": "468fe181-0002-4b1d-ae7f-8b2a5c171eee",
          "name": "2016-04-06T17:27:17Z",
          "snapshotID": 4,
          "snapshotUUID": "03563c5e-51c4-4e3b-a256-a4d0e6b7959d",
          "status": "done",
          "totalSize": 1000341504,
          "virtualVolumeID": null,
          "volumeID": 2
        }
      ],
      "name": "2016-04-06T17:27:17Z",
      "status": "done"
    },
    "groupSnapshotID": 3,
    "members": [
      {
        "checksum": "0x0",
        "snapshotID": 2,
        "snapshotUUID": "719b162c-e170-4d80-b4c7-1282ed88f4e1",
        "volumeID": 2
      }
    ]
  }
}
----


== 自版本以来的新版本

9.6
