---
permalink: api/reference_element_api_createkeyserverkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,creating,create 
summary: '您可以使用 CreateKeyServerKmip 方法创建具有指定属性的密钥管理互操作协议 (KMIP) 密钥服务器。创建过程中不会联系服务器；使用此方法之前服务器无需存在。对于集群密钥服务器配置，您必须在 kmipKeyServerHostnames 参数中提供所有服务器节点的主机名或 IP 地址。您可以使用 TestKeyServerKmip 方法测试密钥服务器。' 
---
= 创建密钥服务器Kmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
你可以使用 `CreateKeyServerKmip`创建具有指定属性的密钥管理互操作协议 (KMIP) 密钥服务器的方法。创建过程中不会联系服务器；使用此方法之前服务器无需存在。对于集群密钥服务器配置，您必须在 kmipKeyServerHostnames 参数中提供所有服务器节点的主机名或 IP 地址。你可以使用 `TestKeyServerKmip`测试密钥服务器的方法。



== 参数

该方法有以下输入参数：

|===
| 名称 | 描述 | 类型 | 默认值 | 必填项 


 a| 
kmipCa证书
 a| 
外部密钥服务器根 CA 的公钥证书。这将用于验证外部密钥服务器在 TLS 通信中提供的证书。对于关键服务器集群，如果各个服务器使用不同的 CA，则提供一个包含所有 CA 根证书的连接字符串。
 a| 
string
 a| 
无
 a| 
是



 a| 
kmipClientCertificate
 a| 
Solidfire KMIP 客户端使用的 PEM 格式 Base64 编码 PKCS#10 X.509 证书。
 a| 
string
 a| 
无
 a| 
是



 a| 
kmipKeyServerHostnames
 a| 
与此 KMIP 密钥服务器关联的主机名或 IP 地址数组。只有当关键服务器处于集群配置中时，才需要提供多个主机名或 IP 地址。
 a| 
字符串数组
 a| 
无
 a| 
是



 a| 
kmipKeyServerName
 a| 
KMIP密钥服务器的名称。此名称仅用于显示目的，无需唯一。
 a| 
string
 a| 
无
 a| 
是



 a| 
kmipKeyServerPort
 a| 
与此 KMIP 密钥服务器关联的端口号（通常为 5696）。
 a| 
整数
 a| 
无
 a| 
否

|===


== 返回值

此方法具有以下返回值：

|===


| 名称 | 描述 | 类型 


 a| 
kmip密钥服务器
 a| 
包含有关新创建的密钥服务器详细信息的对象。
 a| 
link:reference_element_api_keyserverkmip.html["密钥服务器Kmip"]

|===


== 请求示例

该方法的请求类似于以下示例：

[listing]
----
{
  "method": "CreateKeyServerKmip",
  "params": {
    "kmipCaCertificate": "MIICPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
    "kmipClientCertificate": "dKkkirWmnWXbj9T/UWZYB2oK0z5...",
    "kmipKeyServerHostnames" : ["server1.hostname.com", "server2.hostname.com"],
    "kmipKeyServerName" : "keyserverName",
    "kmipKeyServerPort" : 5696
  },
"id": 1
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
   "id": 1,
   "result":
      {
        "kmipKeyServer": {
            "kmipCaCertificate":"MIICPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
            "kmipKeyServerHostnames":[
                "server1.hostname.com", "server2.hostname.com"
            ],
            "keyProviderID":1,
            "kmipKeyServerName":"keyserverName",
            "keyServerID":1
            "kmipKeyServerPort":1,
            "kmipClientCertificate":"dKkkirWmnWXbj9T/UWZYB2oK0z5...",
            "kmipAssignedProviderIsActive":true
        }
    }
}
----


== 自版本以来的新版本

11.7
