---
permalink: api/reference_element_api_deleteauthsessionsbyusername.html 
sidebar: sidebar 
keywords: auth sessions,username,delete,authentication sessions 
summary: 您可以使用 DeleteAuthSessionsByUsername 方法删除给定用户的所有身份验证会话。不在 AccessGroup ClusterAdmins/Administrator 中的调用者只能删除自己的会话。拥有 ClusterAdmins/Administrator 权限的调用者可以删除属于任何用户的会话。要查看可以删除的会话列表，请使用相同的参数调用 ListAuthSessionsByUsername。要查看可删除的会话列表，请使用相同的参数调用 ListAuthSessionsByUsername 方法。 
---
= 按用户名删除身份验证会话
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
你可以使用 `DeleteAuthSessionsByUsername`删除给定用户的所有身份验证会话的方法。不在 AccessGroup ClusterAdmins/Administrator 中的调用者只能删除自己的会话。拥有 ClusterAdmins/Administrator 权限的调用者可以删除属于任何用户的会话。要查看可以删除的会话列表，请使用 `ListAuthSessionsByUsername`参数相同。要查看可删除的会话列表，请使用以下方法： `ListAuthSessionsByUsername`使用相同参数的方法。



== 参数

该方法有以下输入参数：

|===
| 名称 | 描述 | 类型 | 默认值 | 必填项 


 a| 
认证方法
 a| 
要删除的用户会话的身份验证方法。只有属于 ClusterAdmins/Administrator AccessGroup 的调用者才能提供此参数。可能的值有：

* *authMethod=Cluster* 指定集群管理员用户名。
* *authMethod=Ldap* 指定用户的 LDAP DN。
* *authMethod=Idp* 指定用户的 IdP UUID 或 NameID。如果 IdP 未配置为返回任一选项，则此设置会指定在创建会话时颁发的随机 UUID。

 a| 
认证方法
 a| 
无
 a| 
否



 a| 
用户名
 a| 
用户的唯一标识符。
 a| 
string
 a| 
无
 a| 
否

|===


== 返回值

该方法返回以下值：

|===


| 名称 | 描述 | 类型 


 a| 
会议
 a| 
已删除身份验证会话的会话信息。
 a| 
link:reference_element_api_authsessioninfo.html["authSessionInfo"]

|===


== 请求示例

该方法的请求类似于以下示例：

[listing]
----
{
  "method": "DeleteAuthSessionsByUsername",
  "params": {
    "authMethod": "Cluster",
    "username": "admin"
  }
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== 自版本以来的新版本

12.0
