---
permalink: api/reference_element_api_addvirtualnetwork.html 
sidebar: sidebar 
keywords: addvirtualnetwork,cluster,add,adding,virtual,network 
summary: 您可以使用 AddVirtualNetwork 方法向集群配置中添加新的虚拟网络。 
---
= 添加虚拟网络
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
你可以使用 `AddVirtualNetwork`向集群配置中添加新虚拟网络的方法。

添加虚拟网络时，会为每个节点创建一个接口，每个接口都需要一个虚拟网络 IP 地址。您为此 API 方法指定的参数中指定的 IP 地址数量必须等于或大于集群中的节点数量。系统批量配置虚拟网络地址，并自动将其分配给各个节点。您无需手动为节点分配虚拟网络地址。


NOTE: AddVirtualNetwork 方法仅用于创建新的虚拟网络。如果要对现有虚拟网络进行更改，请使用xref:reference_element_api_modifyvirtualnetwork.adoc[修改虚拟网络]方法。



== 参数

该方法有以下输入参数：

|===
| 名称 | 描述 | 类型 | 默认值 | 必填项 


 a| 
地址块
 a| 
要包含在虚拟网络中的所有 IP 地址的唯一范围。对象必需成员：

* 起始地址：IP 地址范围的起始地址。  （细绳）
* 大小：要包含在块中的 IP 地址数量。  （整数）

 a| 
JSON 对象数组
 a| 
无
 a| 
是



 a| 
属性
 a| 
JSON 对象格式的名称-值对列表。
 a| 
JSON 对象
 a| 
无
 a| 
否



 a| 
网关
 a| 
虚拟网络网关的IP地址。仅当命名空间参数设置为 true 时，此参数才有效。
 a| 
string
 a| 
无
 a| 
否



 a| 
name
 a| 
用户为新虚拟网络自定义的名称。
 a| 
string
 a| 
无
 a| 
是



 a| 
namespace
 a| 
设置为 true 时，通过创建和配置命名空间及其包含的虚拟网络来启用可路由存储 VLAN 功能。
 a| 
布尔值
 a| 
无
 a| 
否



 a| 
netmask
 a| 
为正在创建的虚拟网络创建的唯一网络掩码。
 a| 
string
 a| 
无
 a| 
是



 a| 
svip
 a| 
为正在创建的虚拟网络分配唯一的存储 IP 地址。
 a| 
string
 a| 
无
 a| 
是



 a| 
虚拟网络标签
 a| 
唯一的虚拟网络（VLAN）标签。支持的值范围为 1 到 4094。
 a| 
整数
 a| 
无
 a| 
是

|===
*注意：*当命名空间设置为 false 时，每个虚拟网络的虚拟网络参数必须是唯一的。



== 返回值

该方法返回以下值：

|===


| 名称 | 描述 | 类型 


 a| 
虚拟网络 ID
 a| 
新虚拟网络的虚拟网络 ID。
 a| 
整数

|===


== 请求示例

该方法的请求类似于以下示例：

[listing]
----
{
  "method": "AddVirtualNetwork",
  "params": {
    "virtualNetworkTag": 2010,
    "name": "network1",
    "addressBlocks" : [
        { "start": "192.86.5.1", "size": 10 },
        { "start": "192.86.5.50", "size": 20 }
    ],
    "netmask" : "255.255.192.0",
    "gateway" : "10.0.1.254",
    "svip" : "192.86.5.200",
    "attributes" : {}
    "namespace" : true
  },
"id": 1
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
   "id": 1,
   "result":
      {
        "virtualNetworkID": 5
   }
}
----


== 自版本以来的新版本

9.6
