---
permalink: api/reference_element_api_testping.html 
sidebar: sidebar 
keywords: ping,test,TestPing 
summary: 您可以使用 TestPing 方法，通过 ICMP 数据包测试集群中所有节点在 1G 和 10G 接口上的网络连接。该测试根据网络配置中的 MTU 设置，为每个数据包使用合适的 MTU 大小。  TestPing 不会创建临时 VLAN 接口。 
---
= 测试Ping
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
你可以使用 `TestPing`使用 ICMP 数据包测试集群中所有节点在 1G 和 10G 接口上的网络连接的方法。该测试根据网络配置中的 MTU 设置，为每个数据包使用合适的 MTU 大小。 `TestPing`不会创建临时 VLAN 接口。



== 参数

该方法具有以下输入参数：

|===
| 名称 | 描述 | 类型 | 默认值 | 必填项 


 a| 
尝试
 a| 
指定系统应重复执行测试 ping 的次数。
 a| 
整数
 a| 
5
 a| 
否



 a| 
hosts
 a| 
指定要 ping 的设备地址或主机名的逗号分隔列表。如果没有指定主机，则该方法会 ping 存储集群中的主机。
 a| 
string
 a| 
无
 a| 
否



 a| 
界面
 a| 
现有（基础）接口，用于发送 ping 请求。可能值：

* `Bond10G`：从 Bond10G 接口发送 ping 请求。
* `Bond1G`：从 Bond1G 接口发送 ping 请求。

 a| 
string
 a| 
无
 a| 
否



 a| 
数据包大小
 a| 
指定发送到每个 IP 地址的 ICMP 数据包中要发送的字节数。字节数必须小于网络配置中指定的最大 MTU。
 a| 
整数
 a| 
无
 a| 
否



 a| 
ping超时毫秒
 a| 
指定等待每个 ping 响应的毫秒数。
 a| 
整数
 a| 
500毫秒
 a| 
否



 a| 
禁止碎片化
 a| 
启用 ICMP 数据包的 DF（不分片）标志。
 a| 
布尔值
 a| 
false
 a| 
否



 a| 
sourceAddressV4
 a| 
ICMP ping 数据包中使用的源 IPv4 地址。
 a| 
string
 a| 
无
 a| 
否



 a| 
sourceAddressV6
 a| 
ICMP ping 数据包中使用的源 IPv6 地址。
 a| 
string
 a| 
无
 a| 
否



 a| 
总超时时间秒
 a| 
指定 ping 命令在发出下一次 ping 尝试或结束进程之前应等待系统响应的时间（以秒为单位）。
 a| 
整数
 a| 
5
 a| 
否



 a| 
虚拟网络标签
 a| 
发送 ping 数据包时要使用的 VLAN ID。
 a| 
整数
 a| 
无
 a| 
否

|===


== 返回值

该方法返回以下值：

|===


| 名称 | 描述 | 类型 


 a| 
细节
 a| 
列出节点能够通信的每个 IP 地址以及 ping 响应统计信息。
 a| 
JSON 对象

|===


== 请求示例

该方法的请求类似于以下示例：

[listing]
----
{
    "method": "TestPing",
    "params": {
        "interface": "Bond1G",
        "hosts": "192.168.0.1"
    },
    "id" : 1
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
  "id": 1,
  "result": {
    "details": {
      "192.168.0.1": {
        "individualResponseCodes": [
          "Success",
          "Success",
          "Success",
          "Success",
          "Success"
        ],
        "individualResponseTimes": [
          "00:00:00.000304",
          "00:00:00.000123",
          "00:00:00.000116",
          "00:00:00.000113",
          "00:00:00.000111"
        ],
        "individualStatus": [
          true,
          true,
          true,
          true,
          true
        ],
        "interface": "Bond1G",
        "responseTime": "00:00:00.000154",
        "sourceAddressV4": "192.168.0.5",
        "successful": true
      }
    },
    "duration": "00:00:00.001747",
    "result": "Passed"
  }
}
----


== 自版本以来的新版本

5.0
