---
permalink: api/reference_element_api_checkpingonvlan.html 
sidebar: sidebar 
keywords: VLAN,pre-deployment,network,validation,validate,validating,check,checking,CheckPingOnVlan 
summary: 在执行部署前网络验证时，可以使用 CheckPingOnVlan 方法测试临时 VLAN 上的网络连接。  CheckPingOnVlan 创建一个临时 VLAN 接口，使用该 VLAN 接口向存储集群中的所有节点发送 ICMP 数据包，然后删除该接口。 
---
= 检查 VLAN 的 Ping
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
你可以使用 `CheckPingOnVlan`在执行部署前网络验证时，测试临时 VLAN 上的网络连接性的方法。 `CheckPingOnVlan`创建一个临时 VLAN 接口，使用该 VLAN 接口向存储集群中的所有节点发送 ICMP 数据包，然后删除该接口。



== 参数

该方法具有以下输入参数：

|===
| 名称 | 描述 | 类型 | 默认值 | 必填项 


 a| 
尝试
 a| 
指定系统应重复执行测试 ping 的次数。
 a| 
整数
 a| 
5
 a| 
否



 a| 
hosts
 a| 
指定要 ping 的设备地址或主机名的逗号分隔列表。
 a| 
string
 a| 
集群中的节点
 a| 
否



 a| 
界面
 a| 
现有（基础）接口，用于发送 ping 请求。可能值：

* Bond10G：从 Bond10G 接口发送 ping 请求。
* Bond1G：从 Bond1G 接口发送 ping 请求。

 a| 
string
 a| 
无
 a| 
是



 a| 
数据包大小
 a| 
指定发送到每个 IP 地址的 ICMP 数据包中要发送的字节数。字节数必须小于网络配置中指定的最大 MTU。
 a| 
整数
 a| 
无
 a| 
否



 a| 
ping超时毫秒
 a| 
指定等待每个 ping 响应的毫秒数。
 a| 
整数
 a| 
500毫秒
 a| 
否



 a| 
禁止碎片化
 a| 
启用 ICMP 数据包的 DF（不分片）标志。
 a| 
布尔值
 a| 
false
 a| 
否



 a| 
sourceAddressV4
 a| 
ICMP ping 数据包中使用的源 IPv4 地址。
 a| 
string
 a| 
无
 a| 
是



 a| 
sourceAddressV6
 a| 
ICMP ping 数据包中使用的源 IPv6 地址。
 a| 
string
 a| 
无
 a| 
是



 a| 
总超时时间秒
 a| 
指定 ping 命令在发出下一次 ping 尝试或结束进程之前应等待系统响应的时间（以秒为单位）。
 a| 
整数
 a| 
5
 a| 
否



 a| 
虚拟网络标签
 a| 
发送 ping 数据包时要使用的 VLAN ID。
 a| 
整数
 a| 
无
 a| 
是

|===


== 返回值

此方法具有以下返回值：

|===


| 名称 | 描述 | 类型 


 a| 
结果
 a| 
列出节点能够通信的每个 IP 地址以及 ping 响应统计信息。
 a| 
JSON 对象

|===


== 请求示例

该方法的请求类似于以下示例：

[listing]
----
{
    "method": "CheckPingOnVlan",
    "params": {
        "interface": "Bond10G",
        "virtualNetworkTag": 4001,
        "sourceAddressV4": "192.168.41.4",
        "hosts": "192.168.41.2"
},
"id": 1
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
  "id": 1,
  "result": {
    "192.168.41.2": {
      "individualResponseCodes": [
        "Success",
        "Success",
        "Success",
        "Success",
        "Success"
      ],
      "individualResponseTimes": [
        "00:00:00.000373",
        "00:00:00.000098",
        "00:00:00.000097",
        "00:00:00.000074",
        "00:00:00.000075"
      ],
      "individualStatus": [
        true,
        true,
        true,
        true,
        true
      ],
      "interface": "Bond10G",
      "responseTime": "00:00:00.000143",
      "sourceAddressV4": "192.168.41.4",
      "successful": true,
      "virtualNetworkTag": 4001
    }
  }
}
----


== 自版本以来的新版本

11.1
