---
permalink: api/reference_element_api_creategroupsnapshot.html 
sidebar: sidebar 
keywords: volume,volumes,snapshot,snapshots,CreateGroupSnapshot,group,create,creating 
summary: 您可以使用 CreateGroupSnapshot 创建一组卷的某个时间点的副本。 
---
= 创建组快照
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `CreateGroupSnapshot`创建一组卷的某个时间点的副本。

您可以稍后使用此快照作为备份或回滚，以确保卷组上的数据在您创建快照的时间点保持一致。

*集群满度*


NOTE: 如果集群容量处于第 1、2 或 3 阶段，则可以创建快照。当集群容量达到 4 或 5 级时，无法创建快照。



== 参数

该方法有以下输入参数：

|===
| 名称 | 描述 | 类型 | 默认值 | 必填项 


 a| 
`attributes`
 a| 
JSON 对象格式的名称-值对列表。
 a| 
JSON 对象
 a| 
无
 a| 
否



 a| 
`enableRemoteReplication`
 a| 
指定是否将快照复制到远程存储。可能值：

* `true`快照将被复制到远程存储。
* `false`快照不会复制到远程存储。

 a| 
布尔值
 a| 
false
 a| 
否



| `ensureSerialCreation`  a| 
指定如果先前的快照复制正在进行中，则不应创建快照。可能的值有：

* `true`这样可以确保一次只复制一个快照。如果之前的快照复制仍在进行中，则创建新快照将失败。
* `false`： 默认。如果另一个快照复制仍在进行中，则允许创建此快照。

| 布尔值 | `false` | 否 


 a| 
`expirationTime`
 a| 
指定快照可以删除的时间。不能与……一起使用 `retention`。如果两者都不是 `expirationTime`， 或者 `retention`如果指定了快照，则快照将不会过期。时间格式为 ISO 8601 日期字符串，用于基于时间的过期，否则将不会过期。一个值 `null`导致快照永久保留。一个值 `fifo`使得快照按照先进先出 (FIFO) 原则相对于卷上的其他 FIFO 快照进行保存。如果没有可用的FIFO空间，API将失败。
 a| 
ISO 8601 日期字符串
 a| 
无
 a| 
否



 a| 
`name`
 a| 
群组快照的名称。如果没有输入姓名，则使用拍摄群组快照的日期和时间。名称长度上限为 255 个字符。
 a| 
string
 a| 
无
 a| 
否



 a| 
`retention`
 a| 
此参数与以下参数相同： `expirationTime`参数，但时间格式为 HH:mm:ss。如果两者都不是 `expirationTime`也不 `retention`如果指定了快照，则快照将不会过期。
 a| 
string
 a| 
无
 a| 
否



 a| 
`snapMirrorLabel`
 a| 
SnapMirror软件用于指定SnapMirror端点上的快照保留策略的标签。
 a| 
string
 a| 
无
 a| 
否



 a| 
`volumes`
 a| 
要从中复制的卷映像的唯一 ID。
 a| 
volumeID 数组
 a| 
无
 a| 
是

|===


== 返回值

此方法具有以下返回值：

|===


| 名称 | 描述 | 类型 


 a| 
members
 a| 
列出组内每个成员的校验和、卷 ID 和快照 ID。有效值：

* 校验和：存储快照中数据的简短字符串表示形式。之后可以使用此校验和来比较其他快照，以检测数据中的错误。  （细绳）
* snapshotID：用于创建新快照的快照的唯一 ID。  snapshotID 必须来自给定卷上的快照。  （整数）
* volumeID：快照的源卷 ID。  （整数）

 a| 
JSON 对象数组



 a| 
组快照ID
 a| 
新群组快照的唯一 ID。
 a| 
组快照 ID



 a| 
组快照
 a| 
包含有关新创建的组快照信息的对象。
 a| 
xref:reference_element_api_groupsnapshot.adoc[组快照]

|===


== 请求示例

该方法的请求类似于以下示例：

[listing]
----
{
   "method": "CreateGroupSnapshot",
   "params": {
      "volumes": [1,2]
   },
   "id": 1
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
  "id": 1,
  "result": {
    "groupSnapshot": {
      "attributes": {},
      "createTime": "2016-04-04T22:43:29Z",
      "groupSnapshotID": 45,
      "groupSnapshotUUID": "473b78a3-ef85-4541-9438-077306b2d3ca",
      "members": [
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2016-04-04T22:43:29Z",
          "enableRemoteReplication": false,
          "expirationReason": "None",
          "expirationTime": null,
          "groupID": 45,
          "groupSnapshotUUID": "473b78a3-ef85-4541-9438-077306b2d3ca",
          "name": "2016-04-04T22:43:29Z",
          "snapshotID": 3323,
          "snapshotUUID": "7599f200-0092-4b41-b362-c431551937d1",
          "status": "done",
          "totalSize": 5000658944,
          "virtualVolumeID": null,
          "volumeID": 1
        },
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2016-04-04T22:43:29Z",
          "enableRemoteReplication": false,
          "expirationReason": "None",
          "expirationTime": null,
          "groupID": 45,
          "groupSnapshotUUID": "473b78a3-ef85-4541-9438-077306b2d3ca",
          "name": "2016-04-04T22:43:29Z",
          "snapshotID": 3324,
          "snapshotUUID": "a0776a48-4142-451f-84a6-5315dc37911b",
          "status": "done",
          "totalSize": 6001000448,
          "virtualVolumeID": null,
          "volumeID": 2
        }
      ],
      "name": "2016-04-04T22:43:29Z",
      "status": "done"
    },
    "groupSnapshotID": 45,
    "members": [
      {
        "checksum": "0x0",
        "snapshotID": 3323,
        "snapshotUUID": "7599f200-0092-4b41-b362-c431551937d1",
        "volumeID": 1
      },
      {
        "checksum": "0x0",
        "snapshotID": 3324,
        "snapshotUUID": "a0776a48-4142-451f-84a6-5315dc37911b",
        "volumeID": 2
      }
    ]
  }
}
----


== 自版本以来的新版本

9.6
