---
permalink: api/reference_element_api_startbulkvolumewrite.html 
sidebar: sidebar 
keywords: volume,bulk,start,starting,write,session,startbulkvolumewrite 
summary: 您可以使用 StartBulkVolumeWrite 方法在指定的卷上启动批量卷写入会话。 
---
= 启动批量卷写入
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
你可以使用 `StartBulkVolumeWrite`在指定卷上启动批量卷写入会话的方法。

一个卷上只能同时运行两个批量卷处理进程。初始化会话时，数据会从外部备份源写入 Element 存储卷。外部数据由运行在 Element 存储节点上的 Web 服务器访问。存储系统上运行的脚本会传递用于外部数据访问的服务器交互信息。



== 参数

该方法有以下输入参数：

|===
| 名称 | 描述 | 类型 | 默认值 | 必填项 


 a| 
格式
 a| 
容量数据的格式。可以是以下两种情况之一：

* `uncompressed`：卷中的每个字节都以未压缩的形式返回。
* `native`返回的是不透明数据，其体积更小，存储和写入效率更高，便于后续批量卷写入。

 a| 
string
 a| 
无
 a| 
是



 a| 
volumeID
 a| 
要写入的卷的 ID。
 a| 
整数
 a| 
无
 a| 
是



 a| 
script
 a| 
可执行脚本的名称。如果没有提供脚本名称，则需要密钥和 URL 才能访问 Element 存储节点。该脚本在主节点上运行，并将密钥和 URL 返回给脚本，以便可以联系本地 Web 服务器。
 a| 
string
 a| 
无
 a| 
否



 a| 
脚本参数
 a| 
要传递给脚本的JSON参数。
 a| 
JSON 对象
 a| 
无
 a| 
否



 a| 
属性
 a| 
JSON 对象格式的名称-值对列表。link:reference_element_api_attributes.html["了解更多"]。
 a| 
JSON 对象
 a| 
无
 a| 
否

|===


== 返回值

此方法具有以下返回值：

|===


| 名称 | 描述 | 类型 


 a| 
异步句柄
 a| 
要检查是否完成的异步进程的 ID。
 a| 
整数



 a| 
密钥
 a| 
用于唯一标识会话的不透明密钥。
 a| 
string



 a| 
网址
 a| 
访问节点 Web 服务器的 URL。
 a| 
string

|===


== 请求示例

该方法的请求类似于以下示例：

[listing]
----
{
   "method": "StartBulkVolumeWrite",
   "params": {
      "volumeID" : 5,
      "format"  : "native",
   },
   "id": 1
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
   "id" : 1,
   "result" : {
      "asyncHandle" : 1,
      "key" : "11eed8f086539205beeaadd981aad130",
      "url" : "https://127.0.0.1:44000/"
   }
}
----


== 自版本以来的新版本

9.6
