---
permalink: api/reference_element_api_createsnapmirrorrelationship.html 
sidebar: sidebar 
keywords: SnapMirror,relationship,relationships,create,creating,CreateSnapMirrorRelationship 
summary: Element Web UI 使用 CreateSnapMirrorRelationship 方法在源端点和目标端点之间创建SnapMirror扩展数据保护关系。 
---
= 创建快照镜像关系
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Element Web UI 使用 `CreateSnapMirrorRelationship`在源端点和目标端点之间创建SnapMirror扩展数据保护关系的方法。



== 参数

该方法有以下输入参数：

|===
| 名称 | 描述 | 类型 | 默认值 | 必填项 


 a| 
snapMirrorEndpointID
 a| 
与 Element 存储集群通信的远程ONTAP存储系统的端点 ID。
 a| 
整数
 a| 
无
 a| 
是



 a| 
源卷
 a| 
关系中的源量。
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeInfo]
 a| 
无
 a| 
是



 a| 
目的地卷
 a| 
该关系中的目的地流量。
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeInfo]
 a| 
无
 a| 
是



 a| 
关系类型
 a| 
关系类型。在运行 Element 软件的存储系统中，此值始终为“`extended_data_protection`”。
 a| 
string
 a| 
无
 a| 
否



 a| 
策略名称
 a| 
指定关系的ONTAP SnapMirror策略的名称。如果未指定，则默认策略名称为 MirrorLatest。
 a| 
string
 a| 
无
 a| 
否



 a| 
计划名称
 a| 
ONTAP系统上预先存在的 cron 计划的名称，用于更新SnapMirror关系。如果没有指定更新计划，snapMirror 更新将不会进行，必须手动更新。
 a| 
string
 a| 
无
 a| 
否



 a| 
最大转账率
 a| 
指定卷之间的最大数据传输速率，单位为千字节每秒。默认值 0 表示无限制，允许SnapMirror关系充分利用可用的网络带宽。
 a| 
整数
 a| 
无
 a| 
否

|===


== 返回值

此方法具有以下返回值：

|===


| 名称 | 描述 | 类型 


 a| 
snapMirror关系
 a| 
关于新建立的SnapMirror合作关系的信息。
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[snapMirror关系]

|===


== 自版本以来的新版本

10.1
