---
permalink: api/reference_element_api_enablemaintenancemode.html 
sidebar: sidebar 
keywords: maintenance,enable,mode 
summary: 您可以使用 EnableMaintenanceMode 方法来准备对存储节点进行维护。维护场景包括任何需要关闭节点电源或重启节点的任务。 
---
= 启用维护模式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
你可以使用 `EnableMaintenanceMode`用于准备存储节点以进行维护的方法。维护场景包括任何需要关闭节点电源或重启节点的任务。



== 参数

该方法有以下输入参数：

|===
| 名称 | 描述 | 类型 | 默认值 | 必填项 


 a| 
forceWithUnresolvedFaults
 a| 
即使存在阻塞集群故障，也强制为此节点启用维护模式。
 a| 
布尔值
 a| 
False
 a| 
否



 a| 
节点
 a| 
要置于维护模式的节点 ID 列表。一次只能支持一个节点。
 a| 
整数数组
 a| 
无
 a| 
是



 a| 
每分钟主交换限额
 a| 
每分钟要交换的主切片数量。如果未指定，则所有主切片将一次性交换。
 a| 
整数
 a| 
无
 a| 
否



 a| 
timeout
 a| 
指定维护模式在自动禁用前应保持启用状态的时间。格式为时间字符串（例如，HH:mm:ss）。如果未指定，维护模式将保持启用状态，直到明确禁用为止。
 a| 
string
 a| 
无
 a| 
否

|===


== 返回值

此方法具有以下返回值：

|===


| 名称 | 描述 | 类型 


 a| 
异步句柄
 a| 
您可以使用 GetAsyncResult 方法来检索此 asyncHandle，并确定维护模式转换何时完成。
 a| 
整数



 a| 
当前模式
 a| 
节点的当前维护模式状态。可能值：

* 已禁用：未收到维护请求。
* 恢复失败：节点未能从维护模式恢复。
* 正在从维护模式中恢复：节点正在从维护模式中恢复。
* 维护准备：正在采取措施准备对节点进行维护。
* 准备维护：该节点已准备好执行维护。

 a| 
维护模式（字符串）



 a| 
请求模式
 a| 
请求节点的维护模式状态。可能值：

* 已禁用：未收到维护请求。
* 恢复失败：节点未能从维护模式恢复。
* 正在从维护模式中恢复：节点正在从维护模式中恢复。
* 维护准备：正在采取措施准备对节点进行维护。
* 准备维护：该节点已准备好执行维护。

 a| 
维护模式（字符串）

|===


== 请求示例

该方法的请求类似于以下示例：

[listing]
----
{
  "method": "EnableMaintenanceMode",
  "params": {
    "forceWithUnresolvedFaults": False,
    "nodes": [6],
    "perMinutePrimarySwapLimit" : 40,
    "timeout" : "01:00:05"
  },
"id": 1
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
   "id": 1,
   "result":
      {
        "requestedMode": "ReadyForMaintenance",
        "asyncHandle": 1,
        "currentMode": "Disabled"
    }
}
----


== 自版本以来的新版本

12.2



== 查找更多信息

http://docs.netapp.com/us-en/hci/docs/concept_hci_storage_maintenance_mode.html["NetApp HCI存储维护模式概念"^]
