---
permalink: api/reference_element_api_modifyschedule.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,snapshot,schedule,scheduled,delete,pause,modifyschedule 
summary: 您可以使用 ModifySchedule 来更改计划快照发生的间隔。您也可以使用此方法删除或暂停日程安排。 
---
= 修改日程
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `ModifySchedule`更改计划快照发生的间隔。您也可以使用此方法删除或暂停日程安排。



== 参数

该方法有以下输入参数：

|===
| 名称 | 描述 | 类型 | 默认值 | 必填项 


 a| 
属性
 a| 
用于更改快照发生的频率。可能值：

* `Days of Week`
* `Days of Month`
* `Time Interval`

 a| 
JSON 对象
 a| 
无
 a| 
否



 a| 
小时
 a| 
在“星期”或“月份”模式下，两次快照之间的小时数或快照发生的小时数。有效值为 0 到 24。
 a| 
string
 a| 
无
 a| 
否



 a| 
name
 a| 
快照的名称。如果没有输入姓名，则使用拍摄群组快照的日期和时间。名称长度上限为 244 个字符。
 a| 
string
 a| 
无
 a| 
否



 a| 
分钟
 a| 
在“星期”或“月份”模式下，两次快照之间的分钟数或快照发生的分钟数。有效值为 0 到 59。
 a| 
整数
 a| 
无
 a| 
否



| 上次运行状态 | 上次计划快照创建的结果或状态。 | string | 无 | 否 


 a| 
暂停
 a| 
指示是否应暂停日程安排。有效值：

* `true`
* `false`

 a| 
布尔值
 a| 
无
 a| 
否



 a| 
再次发生的
 a| 
指示该日程安排是否会定期重复。有效值包括：

* `true`
* `false`

 a| 
布尔值
 a| 
无
 a| 
否



 a| 
下一个间隔
 a| 
用于选择下次调度程序处于活动状态时是否运行快照。有效值：

* `true`
* `false`


设置为 true 时，计划快照会在调度程序下次激活时运行，然后重置为 false。
 a| 
布尔值
 a| 
false
 a| 
否



 a| 
计划ID
 a| 
日程表的唯一标识符。
 a| 
整数
 a| 
无
 a| 
是



 a| 
计划名称
 a| 
为日程表起一个独特的名称。允许的最大日程名称长度为 244 个字符。
 a| 
string
 a| 
无
 a| 
否



 a| 
计划类型
 a| 
指示要创建的日程类型。唯一支持的值是 `snapshot`。
 a| 
string
 a| 
无
 a| 
是



 a| 
`scheduleInfo`
 a| 
为计划赋予的唯一名称、创建的快照的保留期限以及创建快照的卷的卷 ID。有效值：

* `enableRemoteReplication`：指示是否应将快照包含在远程复制中。  （布尔值）
* `ensureSerialCreation`：指定如果先前的快照复制正在进行中，是否应允许创建新的快照。  （布尔值）
* `name`要使用的快照名称。  （细绳）
* `retention`快照保留的时间。根据时间不同，它会以以下格式之一显示：
+
** `fifo`快照按先进先出 (FIFO) 原则保留。如果快照为空，则永久保留。  （细绳）
** 时:分:秒


* `volumeID`：要包含在快照中的卷的 ID。  （整数）
* `volumes`：要包含在组快照中的卷 ID 列表。  （整数数组）

 a| 
link:reference_element_api_schedule.html["日程"^]
 a| 
无
 a| 
否



 a| 
snapMirrorLabel
 a| 
SnapMirror软件用于指定SnapMirror端点上的快照保留策略的标签。
 a| 
string
 a| 
无
 a| 
否



 a| 
待删除
 a| 
指示该日程是否被标记为删除。有效值：

* `true`
* `false`

 a| 
布尔值
 a| 
无
 a| 
否



 a| 
起始日期
 a| 
表示该日程安排首次开始或即将开始的日期。
 a| 
ISO 8601 日期字符串
 a| 
无
 a| 
否



 a| 
月天
 a| 
每月拍摄快照的日期。有效值为 1 到 31。
 a| 
整数数组
 a| 
无
 a| 
是



 a| 
工作日
 a| 
创建快照的日期是星期几。一周中的某一天从星期日开始，值为 0，偏移量为 1。
 a| 
string
 a| 
无
 a| 
否

|===


== 返回值

该方法返回以下值：

|===


| 名称 | 描述 | 类型 


 a| 
日程
 a| 
包含修改后的日程属性的对象。
 a| 
xref:reference_element_api_schedule.adoc[日程]

|===


== 请求示例

[listing]
----
{
  "method": "ModifySchedule",
  "params": {
    "scheduleName" : "Chicago",
    "scheduleID" : 3
    },
  "id": 1
}
----


== 响应示例

[listing]
----
{
  "id": 1,
  "result": {
    "schedule": {
      "attributes": {
        "frequency": "Days Of Week"
            },
      "hasError": false,
      "hours": 5,
      "lastRunStatus": "Success",
      "lastRunTimeStarted": null,
      "minutes": 0,
      "monthdays": [],
      "paused": false,
      "recurring": true,
      "runNextInterval": false,
      "scheduleID": 3,
      "scheduleInfo": {
        "volumeID": "2"
            },
      "scheduleName": "Chicago",
      "scheduleType": "Snapshot",
      "startingDate": null,
      "toBeDeleted": false,
      "weekdays": [
        {
          "day": 2,
          "offset": 1
      }
      ]
    }
  }
}
----


== 自版本以来的新版本

9.6
