---
permalink: api/reference_element_api_modifysnapshot.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,snapshot,attributes,attribute 
summary: 您可以使用 ModifySnapshot 来更改当前分配给快照的属性。您还可以使用此方法将读/写（源）卷上创建的快照远程复制到运行 Element 软件的目标存储集群。 
---
= 修改快照
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `ModifySnapshot`更改当前分配给快照的属性。您还可以使用此方法将读/写（源）卷上创建的快照远程复制到运行 Element 软件的目标存储集群。



== 参数

该方法有以下输入参数：

|===


| 名称 | 描述 | 类型 | 默认值 | 必填项 


 a| 
启用远程复制
 a| 
用于将创建的快照复制到远程存储集群。可能值：

* `true`快照将被复制到远程存储。
* `false`快照不会复制到远程存储。

 a| 
布尔值
 a| 
false
 a| 
否



 a| 
过期时间
 a| 
指定快照可以删除的时间。不能与保留剂一起使用。如果既未指定 expirationTime，也未指定对原始快照的保留时间，则快照将不会过期。时间格式为 ISO 8601 日期字符串，用于基于时间的过期，否则将不会过期。值为空时，快照将被永久保留。 fifo 值会使快照按照先进先出 (FIFO) 原则保存，相对于卷上的其他 FIFO 快照而言。如果没有可用的FIFO空间，API将失败。
 a| 
ISO 8601 日期字符串
 a| 
无
 a| 
否



 a| 
name
 a| 
快照的名称。如果没有输入名称，则使用拍摄快照的日期和时间。名称长度上限为 255 个字符。
 a| 
string
 a| 
无
 a| 
否



 a| 
snapMirrorLabel
 a| 
SnapMirror软件用于指定SnapMirror端点上的快照保留策略的标签。
 a| 
string
 a| 
无
 a| 
否



 a| 
snapshotID
 a| 
快照标识符。
 a| 
string
 a| 
无
 a| 
是

|===


== 返回值

该方法返回以下值：

|===


| 名称 | 描述 | 类型 


 a| 
Snapshot
 a| 
包含有关新修改快照信息的对象。
 a| 
xref:reference_element_api_snapshot.adoc[Snapshot]

|===


== 请求示例

该方法的请求类似于以下示例：

[listing]
----
{
  "method": "ModifySnapshot",
  "params": {
    "snapshotID": 3114,
    "enableRemoteReplication": "true",
    "name" : "Chicago"
  },
  "id": 1
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
  "id": 1,
  "result": {
    "snapshot": {
      "attributes": {},
      "checksum": "0x0",
      "createTime": "2016-04-04T17:26:20Z",
      "enableRemoteReplication": true,
      "expirationReason": "None",
      "expirationTime": null,
      "groupID": 0,
      "groupSnapshotUUID": "00000000-0000-0000-0000-000000000000",
      "name": "test1",
      "snapshotID": 3114,
      "snapshotUUID": "5809a671-4ad0-4a76-9bf6-01cccf1e65eb",
      "status": "done",
      "totalSize": 5000658944,
      "virtualVolumeID": null,
      "volumeID": 1
    }
  }
}
----


== 自版本以来的新版本

9.6
