---
permalink: api/reference_element_api_startbulkvolumeread.html 
sidebar: sidebar 
keywords: volume,read,session,start,starting,bulk,startbulkvolumeread 
summary: 您可以使用 StartBulkVolumeRead 方法对指定的卷启动批量卷读取会话。 
---
= 启动批量读取
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
你可以使用 `StartBulkVolumeRead`在指定卷上启动批量卷读取会话的方法。

一个卷上只能同时运行两个批量卷处理进程。初始化会话时，数据将从SolidFire存储卷读取并存储在外部备份源上。外部数据由运行在 Element 存储节点上的 Web 服务器访问。存储系统上运行的脚本会传递用于外部数据访问的服务器交互信息。

在批量卷读取操作开始时，会创建卷的快照，读取完成后会删除该快照。您还可以通过输入快照 ID 作为参数来读取卷的快照。读取先前的快照时，系统不会创建新的卷快照，也不会在读取完成后删除先前的快照。


NOTE: 如果没有提供现有快照的 ID，则此过程将创建一个新的快照。如果集群容量达到第 2 或第 3 阶段，则可以创建快照。当集群容量达到 4 或 5 级时，不会创建快照。



== 参数

该方法有以下输入参数：

|===
| 名称 | 描述 | 类型 | 默认值 | 必填项 


 a| 
格式
 a| 
容量数据的格式。可以是以下两种情况之一：

* `uncompressed`：卷中的每个字节都以未压缩的形式返回。
* `native`返回的是不透明数据，其体积更小，存储和写入效率更高，便于后续批量卷写入。

 a| 
string
 a| 
无
 a| 
是



 a| 
volumeID
 a| 
要读取的卷的 ID。
 a| 
整数
 a| 
无
 a| 
是



 a| 
snapshotID
 a| 
用于批量卷读取的先前创建的快照的 ID。如果没有输入 ID，则会创建当前活动卷映像的快照。
 a| 
整数
 a| 
无
 a| 
否



 a| 
script
 a| 
可执行脚本的名称。如果没有提供脚本名称，则需要密钥和 URL 才能访问 Element 存储节点。该脚本在主节点上运行，并将密钥和 URL 返回给脚本，以便可以联系本地 Web 服务器。
 a| 
string
 a| 
无
 a| 
否



 a| 
脚本参数
 a| 
要传递给脚本的JSON参数。
 a| 
JSON 对象
 a| 
无
 a| 
否



 a| 
属性
 a| 
JSON 对象格式的名称-值对列表。link:reference_element_api_attributes.html["了解更多"]。
 a| 
JSON 对象
 a| 
无
 a| 
否

|===


== 返回值

此方法具有以下返回值：

|===


| 名称 | 描述 | 类型 


 a| 
异步句柄
 a| 
要检查是否完成的异步进程的 ID。
 a| 
整数



 a| 
密钥
 a| 
用于唯一标识会话的不透明密钥。
 a| 
string



 a| 
网址
 a| 
访问节点 Web 服务器的 URL。
 a| 
string

|===


== 请求示例

该方法的请求类似于以下示例：

[listing]
----
{
   "method": "StartBulkVolumeRead",
   "params": {
      "volumeID" : 5,
      "format"  : "native",
      "snapshotID" : 2
   },
   "id": 1
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
      "id" : 1,
   "result" : {
      "asyncHandle" : 1,
      "key" : "11eed8f086539205beeaadd981aad130",
      "url" : "https://127.0.0.1:44000/"
   }
}
----


== 自版本以来的新版本

9.6
